### ISSUE TITLE
Add me on your Slack chat group

### ISSUE THREAD

**Issue by khusroohayat** [quran/quran.com-frontend#1003]
email: khusroo.hayat@gmail.com

**Comment by naveed-ahmad** [comment]
You were already invited, can't invite again but here is the link to join. 

https://join.slack.com/t/quran/shared_invite/enQtNDAzMzUzNzIyNTMxLTA3ZDY5OWY1MDI2NDUzMzJhYjJkNjRmOTE2ODQ4NDkxY2MxY2M5ZjEyNDNkMTdmNjYyM2QyOGNhMDM4YmFiZjc

WELCOME!
