### ISSUE TITLE
Broken link on legacy site

### ISSUE THREAD

**Issue by c16u** [quran/quran.com-frontend#1016]
**I'm submitting a ...**

- [X] bug report
- [ ] feature request
- [ ] other

**Current behavior:**

Broken Alpha link in the top right corner of https://legacy.Quran.com.

**Expected / new behavior:**

Modify link to simply Quran.con (remove Alpha.) because the new design is the default design.

**For issue, please provide steps to reproduce it:**
- Go to https://legacy.quran.com
- Click 'New : Alpha.quran.com 

**Anything else:**

**Comment by mmahalwy** [comment]
CC @ahmedre

**Comment by naveed-ahmad** [comment]
I tried fixing this, but we're fetching links from database: https://github.com/quran/quran.com-framework/blob/master/lib/model/ToolbarTable.php 

@ahmedre
