### ISSUE TITLE
Mistranslation still not fixed after multiple reports

### ISSUE THREAD

**Issue by c16u** [quran/quran.com-frontend#1038]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [x] other

**Details**
Already reported via

- https://quran.com/contact
- https://quran.zendesk.com/hc/en-us/articles/205780729-I-found-a-translation-bug-where-do-I-file-it- 
    - Is anyone monitoring this Google form anymore?

Location:
https://quran.com/56/85
http://corpus.quran.com/translation.jsp?chapter=56&verse=85
 
Translation: Sahih International
 
Correction (official): And We (i.e., Our angels) are nearer to him than you, but you do not see –
 
Source: Page 493 (PDF)/497 (viewer) of https://www.kalamullah.com/Books/Quran%20-%20Saheeh%20International%20Translation%20.pdf

**Comment by c16u** [comment]
When will this be fixed?

**Comment by naveed-ahmad** [comment]
@c16u soon. Need to setup an easy way to fix translation and keep history of what's been changed. This is taking some time but will be ready in a week inshAllah.

**Comment by naveed-ahmad** [comment]
Fixed, here is the current translation: 
> And We [i.e., Our angels] are nearer to him than you, but you do not see.
