### ISSUE TITLE
bad chars in API links - exception handling required 

### ISSUE THREAD

**Issue by udotag** [quran/quran.com-frontend#1043]
بسم الله الرحمان الرحيم

**I'm submitting a ...**

- [x] bug report
- [x] feature request
- [ ] other

**Current behavior:**

takes too long to respond
https://quran.com/21/22%EF%BF%BD

**Expected / new behavior:**

should automatically redirect to
https://quran.com/21/22

**For issue, please provide steps to reproduce it:**

just go and paste this in the browser 
https://quran.com/21/22%EF%BF%BD

**Anything else:**

class String
   
   INT_ONLY_CHARS = ['0','1','2','3','4','5','6','7','8','9']
   def non_int_chars
      non_int_chars = []
      self.chars.each do |c|
          if INT_ONLY_CHARS.index(c) != nil 
             non_int_chars << c 
          end
      end
      return non_int_chars.join("").to_i
   end

   def remove_non_int
   end

end

p """this case happened in real life, after copy pasting links from a pages file, junk characters came in due to inbuilt formatting in pages"""

params = "21/22%EF%BF%BD".split("/")
p params[0].non_int_chars
p params[1].non_int_chars

p """wanted to write 22 and pressed a w in between by mistake"""

params = "21/2w2".split("/") 
p params[0].non_int_chars
p params[1].non_int_chars

p """wanted to write 22 and pressed a w before by mistake"""

params = "21/w22".split("/") 
p params[0].non_int_chars
p params[1].non_int_chars

p """wanted to write 22 and pressed a w after by mistake"""

params = "21/22w".split("/") 
p params[0].non_int_chars
p params[1].non_int_chars

p """a very mixed case"""

params = "dsfsdf2gbngfhj1uilkj/hjh2vb2tyuytu".split("/") 
p params[0].non_int_chars
p params[1].non_int_chars

**Comment by naveed-ahmad** [comment]
Already fixed on staging. 
https://staging.quran.com/21/22%EF%BF%BD

**Comment by udotag** [comment]
is defaulting to ayah number 1 and not going to 22
