### ISSUE TITLE
Turkish surah names

### ISSUE THREAD

**Issue by oyilmaztekin** [quran/quran.com-frontend#1058]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other

**Current behavior:**

When the user selects the Turkish language, nothing changes at the website except the menu links.   

**Expected / new behavior:**

Most of the people don't know the English names of the surahs. It has a standard in Turkish. You can check everything about the Turkish usage at the website of the official Islamic foundation of Turkey. 

http://kuran.diyanet.gov.tr/mushaf 

**Anything else:**

I did not see anything about the surah names in **quran.com-api** nor in XHR response.  Then I decided to open the issue in here. If you allow me, I will be glad to help this or anything related to this language issue.

**Comment by naveed-ahmad** [comment]
@oyilmaztekin can you send simple text file with surah name is each line?

**Comment by oyilmaztekin** [comment]
@naveed-ahmad Hope this helps. [surahNames.txt](https://github.com/quran/quran.com-frontend/files/2670762/surahNames.txt)

Also, I uploaded a JSON file which shows how Diyanet holds the surah list.  
[surahListJSON.txt](https://github.com/quran/quran.com-frontend/files/2670773/surahListJSON.txt)
