### ISSUE TITLE
local api returns 500

### ISSUE THREAD

**Issue by Hartha-aloufi** [quran/quran.com-frontend#1059]
Salam alykoom

I have a problem with running the project locally, all api requests returns 500.

server log:
> /api/api/v3/chapters?language=en 500 8866.412 ms - 4887

request example from chrome console :
> Request URL: http://localhost:8000/api/api/v3/chapters/67/info?language=en
> Request Method: GET
> Status Code: 500 Internal Server Error
> Remote Address: [::1]:8000
> Referrer Policy: no-referrer-when-downgrade

**Comment by naveed-ahmad** [comment]
Wa Alakim o Salam, can you send the server logs?

**Comment by Hartha-aloufi** [comment]
@naveed-ahmad  Thank you  for replay, I don't have the server locally, I just cloned  the repo and tried to run the development server, but it seems like the app use the local API by default, so it request http://localhost:8000/api/api/v3/.

I tied to use the staging api but it is also down, in the read me file you side the url could changed in app.json file but I don't find it.

should I clone quran.com-api and run a local server ?

**Comment by naveed-ahmad** [comment]
Staging api is fixed, you can start using it. Sorry we've been trying to upgrade rails version and migrate to new build system. Which took a while.
