### ISSUE TITLE
Toggling the translation doesn't change the tool tip version

### ISSUE THREAD

**Issue by nasir-scalestack** [quran/quran.com-frontend#1075]
Bismillah.

**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other

**Current behavior:**

Changing the translation still shows sahih when you hover over the word instead of the translation you picked

**Expected / new behavior:**

The tooltip should show the same version as the translation you picked from the drawer menu

**For issue, please provide steps to reproduce it:**
- Select any surah
- Select a translation other than sahih
- Hover over one of the words
- The tooltip shows a different version

**Anything else:**

Insha'allah this might not be a bug and rather something still a WIP. Also i would like to contribute my free time on working with this repo and no one has replied back to me for the backend-api request.

**Comment by naveed-ahmad** [comment]
Salam brother @nasir-scalestack 

> The tooltip should show the same version as the translation you picked from the drawer menu

We only have one word by word english translation, so this isn't possible. 

> I would like to contribute my free time on working with this repo
Awesome, can you send your email? Let's discuss the issues and backend api on slack.
