### ISSUE TITLE
Quick link to Ayatul Kursi isn’t working

### ISSUE THREAD

**Issue by alia0021** [quran/quran.com-frontend#1076]
**I'm submitting a ...**

- [ x ] bug report
- [ ] feature request
- [ ] other

**Current behavior:**

The quick link to ayatul kursi isn’t working on responsive web mobile version. When its clicked on it remains on the same page.
**Expected / new behavior:**
 The link should work once clicked on just like the others.

**For issue, please provide steps to reproduce it:**
- Make sure the link is linked to the surah and the specified ayat. 

**Anything else:**

**Comment by melwaraki** [comment]
For anyone who can fix this, the link should probably be https://quran.com/2/255 rather than the current https://quran.com/ayatul-kursi. I think that should fix it

**Comment by naveed-ahmad** [comment]
Fixed, and will be live before ramdan inshAllah.
