### ISSUE TITLE
I want access to database

### ISSUE THREAD

**Issue by AmidexIT** [quran/quran.com-frontend#1082]
I'm trying to make an application for our local community in Bangladesh.
My email id is info@amidex.it

**Comment by naveed-ahmad** [comment]
aSalam o alakim brother. Does this app has some special features? How about contributing those features back to quran.com? 

There are lots of issues sharing the full db, we keep updating translations and typos. There isn't any way we can let people( who are using our data) know that the db is changed. Plus, people have been using this data and code for publishing the clones with ads and what not. 

You can use quran.com api if your app has extra features, but again ill ask you to maybe contribute those features back to quran.com.
