### ISSUE TITLE
Slack invite

### ISSUE THREAD

**Issue by abdallahamin** [quran/quran.com-frontend#1085]
assalamu alykom wa rahmatu Allah wa barakatuh.

I am very interested to contribute to this project. I have just finished a similar project so I have good experience insha'Allah.

Jazakum Allah khairan.

Ramadan Mubarak !

**Comment by naveed-ahmad** [comment]
waAlakim o salam, khair mubarak :) 

Please post your email here for the invite.

**Comment by abdallahamin** [comment]
abdallahaminm@gmail.com
