### ISSUE TITLE
Share Icons display prob

### ISSUE THREAD

**Issue by atefBB** [quran/quran.com-frontend#1086]
In the mobile version of the site `facebook` and `twitter` icons didn't appear in the top right of the page (see image). I'm using `brave` browser in Android phone.
![Screenshot_20190509-235440](https://user-images.githubusercontent.com/10966925/57491811-945d3580-72be-11e9-832b-8757c59258d5.png)

**Comment by shakirandagire** [comment]
Asalaam Aleikum,
I am going to pick up this issue

**Comment by atefBB** [comment]
<p dir="rtl">وعليكم السلام، جزاك الله خيرا</p>

**Comment by naveed-ahmad** [comment]
@shakirandagire walAkaim o salam, can you please hold-on for few days. The new version is coming in few days inshAllah with some new features and lots of fixes. I'm sure this issue is already fixed. Will update all issues after the build.

**Comment by atefBB** [comment]
Ok! Thx.
