### ISSUE TITLE
[Bug report]Quran data directory "Disabled"

### ISSUE THREAD

**Issue by thoraiia** [quran/quran.com-frontend#1103]
I have Lenovo tab2
the Quran data directory option is **disabled**
1)I uninstalled and reinstalled the app many times, but still the same issue.
 2)I tried to move the Quran android folder from the internal storage to the SD card, but the 
   application can't read it and asks me to install the data again, and it consumes about 4GB from 
   the internal storage and slows down the tablet (audio files + Translations ).
  3)I tried by (factory resetting the tablet ) but still the same Problem

**Comment by ahmedre** [comment]
i'd like to ask some clarification, but may you move this issue to [quran/quran_android](https://github.com/quran/quran_android) first?

**Comment by thoraiia** [comment]
@ahmedre done
