### ISSUE TITLE
Hover - Word by word translation in other language

### ISSUE THREAD

**Issue by shral** [quran/quran.com-frontend#1104]
**I'm submitting a:**

- [ ] bug report
- [x] feature request
- [ ] other

**Current behavior:**
Hover translation (word by word translation) only in English

**Expected / new behavior:**
The user should be able to show another language in hover (word by word translation) and the developers should have the possibility to add new languages depending on English or the user should have the possibility to suggest a link between the words in the translation (besides of English) and the words of the Aayah (or the English translation of word by word)

**Comment by naveed-ahmad** [comment]
@shral change site language to Urdu, and you'll get Urdu wbw translation.  Wbw translation isn't available for all languages.

**Comment by shral** [comment]
Thank you for the response @naveed-ahmad! How can I add another language that's not there for Example Albanian or German Language (Those ara the Languages that I could help with)?

**Comment by naveed-ahmad** [comment]
@shral send me an email here naveedahmada036@gmail.com we've developed a tool where contributors can type wbw translation. 

And if already have data in csv( actually in any format), please send me and i'll import it.
