### ISSUE TITLE
Surah dropdown on header does not work properly when clicked on next surah button

### ISSUE THREAD

**Issue by sohailamar** [quran/quran.com-frontend#1115]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other

**Current behavior:**
When a surah is finished and you click on next surah button, after ajax request on new page the surah dropdown on header still shows old surah name in dropdown, refreshing tha page fixed it

**Expected / new behavior:**
it should display next surah name in dropdown (Header)
Quran.com -->

**For issue, please provide steps to reproduce it:**
click on next surah button
https://www.screencast.com/t/LssU4m28WH
On next page that dropdown still shows the last surah name
https://www.screencast.com/t/efwotjZ8F

**Anything else:**
checked on google chrome.

**Comment by AsharSheikh** [comment]
Hi, I can fix this. Kindly tell me the steps in order to access the file.

**Comment by suhaibaffan** [comment]
I am working on this!
