### ISSUE TITLE
[Feature] - Easy implementation

### ISSUE THREAD

**Issue by elvirmuslic** [quran/quran.com-frontend#1117]
Feature -

Add the tooltip translation when the seikh is reciting for each word(make it a toggable option)-
Steps to reproduce - Play Ayah example: https://quran.com/3/199 - it it highlightes each word - add the translation above the word like on mouse hover. 
Picture example included.

https://i.postimg.cc/KcLRQ6Qd/Screenshot-2.png
https://i.postimg.cc/kXmDHTpD/Screenshot-3.png

**Comment by naveed-ahmad** [comment]
Can you please any real use of this feature, other than it will look cool :)

**Comment by elvirmuslic** [comment]
Yes, I actually use it for learning. Correlate a word to a meaning not just the whole translation and then depict what is what. I try to understand it by learning the meaning of each word that is my primary use. I didnt notice that it looks cool but that is a good point too 😁

**Comment by elvirmuslic** [comment]
I can actually build a tampermonkey script to simulate a :hover action on each word, however this would not be useful for the mass. 
Any news if this is going to be feature?

**Comment by naveed-ahmad** [comment]
Yep, will add this in beta.

Saw some videos where users record the screen while playing surah. This is perfect use case for showing translation, you can see wbw translation with hover in the video :)

**Comment by elvirmuslic** [comment]
You're awesome! Thank you very much. Let me know if there's something I can do to help out.

**Comment by naveed-ahmad** [comment]
You're welcome bro, keep praying for contributors. Also, please suggest features/bugs etc to new repo
https://github.com/quran/quran.com-frontend-v2/
