### ISSUE TITLE
[bug] "Support Quran.com" link doesn't work

### ISSUE THREAD

**Issue by farahalyasari** [quran/quran.com-frontend#1122]
I'm submitting a report for a small bug

**Current behavior:** and **For issue, please provide steps to reproduce it:**
From the menu Navigate to "Contribute"
Scroll down to the button "Support Quran.com"
The button opens a new tab and the link is broken
The following message is seen:

Error message on edge
> Hmmm...can’t reach this page
> Try this
> Make sure you’ve got the right web address: https://quran.tilt.com
> Search for "https://quran.tilt.com" on Bing
> Refresh the page
> Details 
> Report this issue

Error Message on Firefox

> The connection has timed out
> 
> The server at quran.tilt.com is taking too long to respond.
> 
>     The site could be temporarily unavailable or too busy. Try again in a few moments.
>     If you are unable to load any pages, check your computer’s network connection.
>     If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

**Anything else:**
I do not think this is a browser issue. The link is not working on any of my browsers.

**Comment by naveed-ahmad** [comment]
Asalamu alaikum borther, yeah we were using tilt.com for donation. This platform was acquired by Airbnb and shutdown. Never has chance to remove this link :( 

Beta is coming soon inshAllah, hopefully in Jan next year. Don't have donation link in beta, and I don't think we'll need donations. 

Checkout beta.quran.com ( the upcoming version of quran.com ) it still have need some UI fixes and search need to be implemented. Working on it.
