### ISSUE TITLE
Feature Request PWA Installable

### ISSUE THREAD

**Issue by AbdulBsit** [quran/quran.com-frontend#1139]
**I'm submitting a ...**

- [ ] bug report
- [x ] feature request
- [ ] other

**Current behavior:**

**Expected / new behavior:**

Add PWA Support to make it more faster and more handy to access

**For issue, please provide steps to reproduce it:**
- Steps 
- to
- reproduce 

**Anything else:**

**Comment by naveed-ahmad** [comment]
https://beta.quran.com is PWA and more :)
