### ISSUE TITLE
Polish Translation of the meaning.

### ISSUE THREAD

**Issue by tasmeemcreative-com** [quran/quran.com-frontend#1140]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other

**Current behavior:**

There used to be a Polish language version, but it is no longer available. Why is that?

**Expected / new behavior:**

How can we re-add the Polish language version? I would like to help/assist.

**Anything else:**

Please contact me on marek@tasmeemcreative.com.au jzkAllah khairun

**Comment by naveed-ahmad** [comment]
https://beta.quran.com/1/1?translations=131,42

We do have a Polish translation.
