### ISSUE TITLE
please make the verses and the text and calligraphy(if_possible) selectable,, so that they can be used in other places with SVG format or any else way.. I AM AVAILABLE FOR ANY GRAPHICAL HELP. please allow me to work with you if possible.

### ISSUE THREAD

**Issue by MDSabbirAhmed** [quran/quran.com-frontend#1142]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other

**Current behavior:**

**Expected / new behavior:**

**For issue, please provide steps to reproduce it:**
- Steps 
- to
- reproduce 

**Anything else:**

**Comment by tamermaarouf** [comment]
Asalamu Alykom,
Dear Mr,
Good day, i want to work with you, how can i help you

**Comment by naveed-ahmad** [comment]
Salam brothers, please send your email address. Let's get you added to our slack group. 

Selecting text is a bit hard, beta.quran.com is slightly better then the current site. If we can modify font glyph that'll be huge.

**Comment by tamermaarouf** [comment]
tamermaarouf@gmail.com
thank you my brother

**Comment by naveed-ahmad** [comment]
Please use this app for invitaiton: https://quranslack.herokuapp.com/
