### ISSUE TITLE
Add option for single aya playback vs. continuous

### ISSUE THREAD

**Issue by kal-el83** [quran/quran.com-frontend#1148]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other

**Current behavior:**
When you want to play the audio of an aya, it plays it then goes on to play the next aya. This is very tedious for people trying to memorize aya by aya, as currently you have to manually stop it. Loop works but doesn't function well in this context either because it doesn't allow for one to repeat an aya after the reciter, but instead just plays it again right away.

**Expected / new behavior:**
There should be an option to just play an aya once then stop instead of forcing continuous playback.

Also perhaps add a "Pause before playback option" that pauses for the same amount of time as the duration of the recitation before looping or continuing playback. 
ie.
-an aya is recited by the reciter (12 seconds)
-the user then repeats the aya on their own in roughly the same amount of time without having to press anything (12 seconds)
-the next aya plays (or the next iteration of the same aya in case loop is on)

**Comment by naveed-ahmad** [comment]
You can now add "pause" between ayah loop. Hopefully, this will serve the purpose.
