### ISSUE TITLE
Love that you keep the tech stack modern.

### ISSUE THREAD

**Issue by aniquedavla** [quran/quran.com-frontend#1151]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other

**Current behavior:**

**Expected / new behavior:**

**For issue, please provide steps to reproduce it:**
- Steps 
- to
- reproduce 

**Anything else:**

Would love to help iA
Add me to slack: aniquedavla@gmail.com.

**Comment by naveed-ahmad** [comment]
Please use this app for invitaiton: https://quranslack.herokuapp.com/
