### ISSUE TITLE
Add me to slack channel 

### ISSUE THREAD

**Issue by redmancodes** [quran/quran.com-frontend#1153]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [ x] other

**Current behavior:**

**Expected / new behavior:**

**For issue, please provide steps to reproduce it:**
- Steps 
- to
- reproduce 

**Anything else:**

Please add me to the slack channel 

redmancodes@gmail.com. جَزَاكُمُ اللهُ خَيْرًا

**Comment by naveed-ahmad** [comment]
Please use this app for invitaiton: https://quranslack.herokuapp.com/
