### ISSUE TITLE
Add to Slack channel: abdelrahmannader@gmail.com

### ISSUE THREAD

**Issue by NaderAbdelrahman** [quran/quran.com-frontend#1159]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [ ] other

**Current behavior:**

**Expected / new behavior:**

**For issue, please provide steps to reproduce it:**
- Steps 
- to
- reproduce 

**Anything else:**

**Comment by naveed-ahmad** [comment]
Please use this app for invitaiton: https://quranslack.herokuapp.com/
