### ISSUE TITLE
Slack Channel

### ISSUE THREAD

**Issue by Anasss** [quran/quran.com-frontend#1160]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other

Salam,

Could you please add me to the slack channel?
Email: **anas.rach@gmail.com**

Thank you!

**Comment by s3audi** [comment]
Could you Please add ME to slack channel?

S3audi@hotmail.com

**Comment by s3audi** [comment]
And one more offer:

Corpus.quran.com

Syntactic Treebank!

The verse 8-59 (between)
Verses does not exist!

THANK YOU very much!

**Comment by osamasayed** [comment]
Could you add me to the slack channel? osama.sayed.abdelazim@gmail.com

**Comment by leadersheir** [comment]
I'd like to be added to the slack channel too. The heroku app returns an application error. My email is warisulimam@gmail.com

**Comment by naveed-ahmad** [comment]
Please use this app for invitaiton: https://quranslack.herokuapp.com/

App was fixed last week :)
