### ISSUE TITLE
Add to Slack channel: ehsan.masud@gmail.com

### ISSUE THREAD

**Issue by machinedialogue** [quran/quran.com-frontend#1163]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [ ] other

**Current behavior:**

**Expected / new behavior:**

**For issue, please provide steps to reproduce it:**
- Steps 
- to
- reproduce 

**Anything else:**

**Comment by ahmedre** [comment]
Invited.

**Comment by AbdullahiAbdulkabir** [comment]
I would love to contribute  @ahmedre. here is my email: abdullahiabdulkabir1@gmail.com.

**Comment by ahmedre** [comment]
invited.
