### ISSUE TITLE
Please add to Slack Channel

### ISSUE THREAD

**Issue by Syednur642** [quran/quran.com-frontend#1165]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other

**Current behavior:**

**Expected / new behavior:**

**For issue, please provide steps to reproduce it:**
- Steps 
- to
- reproduce 

**Anything else:**

**Comment by Syednur642** [comment]
Assalamu Aaalaikum, I like to contribute as a team member.

**Comment by Syednur642** [comment]
Assalamu Aaalaikum, I like to contribute as a team member.

**Comment by naveed-ahmad** [comment]
waAlakim o salam @Syednur642 slack invite app is working now.
