### ISSUE TITLE
There's a very big mistake the site in Surah Al-Ma'idah, verse 71

### ISSUE THREAD

**Issue by Qataada** [quran/quran.com-frontend#1173]
Surah Al-Ma'idah verse 71 is missing the word وحسبوا

![Screenshot_٢٠٢٠٠٨٠٧-٠٧١١٢٣](https://user-images.githubusercontent.com/58090592/89612907-a8109680-d889-11ea-9227-da752b79d03b.png)

Compare it with the Mushaf:

![Screenshot_٢٠٢٠٠٨٠٧-٠٧١٢١٢](https://user-images.githubusercontent.com/58090592/89612921-b78fdf80-d889-11ea-896c-f76765cf15c9.png)

**Comment by naveed-ahmad** [comment]
Fixed in beta
