### ISSUE TITLE
Mistake

### ISSUE THREAD

**Issue by Qataada** [quran/quran.com-frontend#1183]
I want to change the title to "Possible mistake"

In Yusuf Ali translation of Surah Al-Qalam, 41

![Screenshot_٢٠٢٠٠٨٠٧-٠٩١٩٢٦~2](https://user-images.githubusercontent.com/58090592/89615407-38050f00-d88f-11ea-9260-129a10d7f8e1.png)

What is this? "Allahhead"

**Comment by naveed-ahmad** [comment]
https://quranyusufali.com/68/
> Or have they some “ Partners ” (in Godhead) ? Then let them produce Their “ partners ”, If they are truthful !

http://tanzil.net/#trans/en.yusufali/68:41
> Or have they some "Partners" (in Allahhead)? Then let them produce their "partners", if they are truthful!

Looks like we imported this from tanzil :( 

Fixed.
