### ISSUE TITLE
Ayah out of range

### ISSUE THREAD

**Issue by whatsadebugger** [quran/quran.com-frontend#1185]
Whenever I pick Al-Mulk and select an ayah that is too far from the first one i get an error.
Open the surah and then select 25 for example. 

![image](https://user-images.githubusercontent.com/18469591/89980849-4d37c000-dc38-11ea-9f70-ea3a9422aba2.png)

**Comment by whatsadebugger** [comment]
tabba.ahmad@gmail.com if you could add me to slack.

**Comment by whatsadebugger** [comment]
On a similar note I can't load past ayah 10 in the bottom left corner.
![image](https://user-images.githubusercontent.com/18469591/89981993-82dda880-dc3a-11ea-826f-ad563661f38b.png)
can't click after 10

**Comment by mh453Uol** [comment]
Seems to be a UI defect: Inside the console I see the following error `Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22`

You can easily reproduce this bug by going to 
1. https://quran.com/67 
2. Selecting "Play" on verse 11
3. "Loading..." appears on the audio player
4. Audio does not play

However going to https://quran.com/67/11?translations=20 (Url route which loads verse 11) the audio plays correctly. In addition the audio is available for verses 10+ see https://verses.quran.com/Alafasy/mp3/067011.mp3
