### ISSUE TITLE
Project seems halted

### ISSUE THREAD

**Issue by bilalkhanqadri** [quran/quran.com-frontend#1195]
[Slack link](https://quranslack.herokuapp.com/) is broken. 

I am writing this by considering this app (site) a central hub for reading/ understanding Quran, foreseeing its potential to give more indulging encounter with the word of Almighty.

It feels good to come on this site and read some short Surah. App is very simple yet gives very pleasant experience but once in a while I long for a feature to enhance my experience. It is in the nature that I tend to be more productive when I settled for something.

It is very unsettling that project is not moving forward, I am not talking about whole bunch of new features but asking for opening the portal of ideas. I am sure a whole bunch of new ideas can be incorporated while maintaining the simplicity.

**Comment by ahmedre** [comment]
the slack link is dead, but the project is not dead - this particular repository is dead, yes, but that's because most work is happening in either [here](https://github.com/quran/quran.com-frontend-v2) and [here](https://github.com/quran/quran.com-frontend-next).

**Comment by ahmedre** [comment]
if you send your email we can add you to Slack in sha' Allah.

**Comment by osamasayed** [comment]
@ahmedre can you please add me? osama.sayed.abdelazim@gmail.com

**Comment by ahmedre** [comment]
@osamasayed - it says
> This person is already in your workspace.

**Comment by osamasayed** [comment]
> @osamasayed - it says
> 
> > This person is already in your workspace.

I just joined using the link in the frontend-next repo. Thanks a lot!
