### ISSUE TITLE
Two translations the same? Dr. Mustafa Khattab and Dr. Mustafa Khattab, The Clear Quran

### ISSUE THREAD

**Issue by mandazi** [quran/quran.com-frontend#1198]
<img width="343" alt="Screen Shot 2020-09-17 at 8 10 27 PM" src="https://user-images.githubusercontent.com/340385/93540510-e043d400-f921-11ea-809d-c32d03edd000.png">
I believe these two translations are the same, correct?

**Comment by naveed-ahmad** [comment]
Yes, they're the same. The first translation is a simple, second has footnotes.  The next release will remove the simple one.
