### ISSUE TITLE
Can you please add me in the slack?

### ISSUE THREAD

**Issue by hahasuperking** [quran/quran.com-frontend#1212]
My email is hahasuperking@gmail.com, thanks.

**Comment by hahasuperking** [comment]
Salaam, can any one help me? Thanks.

**Comment by hahasuperking** [comment]
@naveed-ahmad Ping :)

**Comment by naveed-ahmad** [comment]
waAlakim o salam sent the invitation. You can always join using our auto-invite app as well https://quranslack.herokuapp.com/
