### ISSUE TITLE
Any way to improve the Quran UI?

### ISSUE THREAD

**Issue by microart-inc** [quran/quran.com-frontend#1221]
The UI of the quran.com website seems very rushed and inconsistent (the scaling, margins, font size). I have some ideas on how to improve it. Is there like a discord or slack where I can send my versions of the websites with fixed margins, paddings, and font sizes.

**Comment by farooqu** [comment]
You can sign up to the Slack from https://quranslack.herokuapp.com/. Also, I believe that this is the old repo. The current versions repo is: https://github.com/quran/quran.com-frontend-v2. I'm sure a PR would be much appreciated there!

**Comment by naveed-ahmad** [comment]
Feel free to open the PR [here](https://github.com/quran/quran.com-frontend-v2)
