### ISSUE TITLE
Bad Gateway 502

### ISSUE THREAD

**Issue by abdelouali** [quran/quran.com-frontend#124]
Hello brothers,

I found a new bug.

If I go directly to the link http://quran.com/46. Then I get a gateway error. But if I go through the home page to surah 46, It will operate normaly.

Shokran.

**Comment by abdelouali** [comment]
An screenshot of the action:

![image](https://cloud.githubusercontent.com/assets/13354388/9996318/c96f7ee8-6086-11e5-9698-f132a03968a3.png)

**Comment by ahmedre** [comment]
JazakAllah khairan for reporting, restarted the backend, but still need to investigate and find out the root cause since this keeps happening...
