### ISSUE TITLE
SITE IS DOWN

### ISSUE THREAD

**Issue by ATouhou** [quran/quran.com-frontend#127]
Salam.
The site is currently down.
First error i got when typing www.quran.com,  was:
![image](https://cloud.githubusercontent.com/assets/6802820/10045694/0a7e5808-6205-11e5-9cf6-ece684d9b386.png)
then after opening another tab and going to the url, I managed to get the regular frontpage. 
When entering a surah I get this error:
![image](https://cloud.githubusercontent.com/assets/6802820/10045718/2010b670-6205-11e5-9335-0ddf07cd0267.png)

**Comment by ATouhou** [comment]
![image](https://cloud.githubusercontent.com/assets/6802820/10045737/4242e2d6-6205-11e5-93c8-a943bb957d38.png)

**Comment by ahmedre** [comment]
one of the backends went down - restarted it. the changes we've made so far al7amdulillah improved the situation a lot (it's been running for almost 2 days without crashing now), but we still have more work to do. jazakAllah khairan for sending this.

**Comment by mmahalwy** [comment]
I filed an issue: https://github.com/phusion/passenger/issues/1619
