### ISSUE TITLE
Include ayah translation and link in text when "Copy" is clicked

### ISSUE THREAD

**Issue by aam1r** [quran/quran.com-frontend#132]
Salam,

Is there a reason why we don't include the translations visible along with the hyperlink to the ayah when Copy is clicked? I usually have to copy those in manually myself.

Example: With Sahih International translation, clicking Copy for 41:32 should copy:

> نزلا من غفور رحيم
> As accommodation from a [Lord who is] Forgiving and Merciful."
> http://quran.com/41/32

Right now, it just copies:

> نزلا من غفور رحيم

Thoughts?

**Comment by mmahalwy** [comment]
Hmm, very interesting. I never thought about that. Right now people complained about the tashkeel thing. they just want to have _just_ the arabic text but it seems logical to have copies for them in different places (ie copy text, copy translation, etc)
