### ISSUE TITLE
Going to an exact ayah via hyperlink does not allow scrolling up

### ISSUE THREAD

**Issue by aam1r** [quran/quran.com-frontend#133]
1. Go to http://quran.com/41/32
2. Ayah 41:32 should load as the first ayah on the screen (with the bismillah above it)

The page lets you scroll down to see latter ayahs, but you can't scroll up to see the prior ones.

![screen shot 2015-10-09 at 22 32 19](https://cloud.githubusercontent.com/assets/566418/10408768/a5b3238a-6ed5-11e5-9d2e-1c4e27327a1d.png)

**Comment by ahmedre** [comment]
just to add my $0.02 - the old quran.com used to restrict to that one ayah given that url (http://legacy.quran.com/41/32, http://legacy.quran.com/41/32-35).

that having been said, i am torn about this. from the perspective of sharing, sharing one ayah or 2 or 3 ayat sometimes makes a lot of sense (just those ayat exclusively, nothing else, unless the user explicitly says, "show me more.").

from a personal perspective, i usually open an ayah, and more often than not, i want to see the next ones.

my personal opinion, and just throwing this out there for discussion, etc:
1. if a single ayah in the url (/41/5), keep today's behavior of showing to the end, but preface the list with a load more button to load previous entries.
2. if an explicit range (/41/5-7), just show that range (with "load more" somewhere to load the entire range).

**Comment by ATouhou** [comment]
What about having a  button in the top and bottom saying show more, and then it can load dynamicly (AJAX) both ways (not only down, but also up?)

**Comment by mmahalwy** [comment]
@ahmedre i think we should change it to the same result as legacy - /2/3 => single ayah and not range.
I also agree with you all about having a load previous button. That being said, it hasn't been an issue that's been recurring in support and I suggest we spend the time adding data to find out how often people go to a ranged or a specific ayah.

**Comment by reshadn** [comment]
*Salams. I was invited to this repo a while back and have been meaning to contribute. Alhamdulillah I'm finally taking the leap. It's a comment but I hope to start by picking up some bugs iA.*

My 2 cents. Show a single ayah but allow up and down scroll to display more. I imagine more people (like me) are using this site on their mobile device and I personally would appreciate "swipe" actions vs clicking links or buttons.

**Comment by mmahalwy** [comment]
@reshadn woooot!!! Thanks for coming back! It says you're an owner: 
![image](https://cloud.githubusercontent.com/assets/3749095/10507401/0145c998-72d5-11e5-80f2-2bcf39a69798.png)

Let me readd you. 

I agree.. I think the low hanging fruit is a button for load more on top or load more on the bottom.
