### ISSUE TITLE
Clicking the "See information for this surah" icon does not reset vertical scroll to display content

### ISSUE THREAD

**Issue by reshadn** [quran/quran.com-frontend#140]
**Summary**: After scrolling down the page and then clicking the "See information for this surah" icon
<img width="161" alt="screen shot 2015-10-15 at 1 27 18 pm" src="https://cloud.githubusercontent.com/assets/425101/10526599/c332542a-7340-11e5-9098-3036ffcdbd8b.png"> 
the content is displayed at the top of the page but is not visible in the viewport. 

**Screenshot**: 
<img width="1303" alt="screen shot 2015-10-15 at 1 33 07 pm" src="https://cloud.githubusercontent.com/assets/425101/10526721/511fad0a-7341-11e5-8ab8-5b8242e60632.png">

**Suggested fix**:
Make the "See information for this surah" content component overlap an existing content in the view. Possibly change where the component is attached to the DOM so that it drops down or pops up from where the "info" icon is clicked rather than at the top of the surah content section.

**Comment by mmahalwy** [comment]
Yeah, we need to fix that :) 

In fluxible-router you can, I am pretty sure
