### ISSUE TITLE
Search  ( SearchInput.js ) 

### ISSUE THREAD

**Issue by ATouhou** [quran/quran.com-frontend#143]
I don't have skills in react so I can't really contribute to the fix,  but when clicking search and the input box is empty it will say: "-0 OF 0 SEARCH RESULTS FOR:"  and say "loading"  forever...
Maybe make the input "glow"/shake/focus  if it is empty? :D

**Comment by mmahalwy** [comment]
Ah! @ATouhou, @reshadn or @aam1r if you want to tackle this to get you into the react world? 

What you need to do is: https://github.com/quran/quran.com-frontend/blob/master/src/scripts/components/header/SearchInput.js#L10 detect what the value is, and perhaps throw an alert if empty?

**Comment by aam1r** [comment]
@mmahalwy I can look at this weekend if no one has worked on this yet. I was planning to look at a few other pending issues and this one over the weekend but was feeling a bit under the weather.

**Comment by mmahalwy** [comment]
hey no worries man! we finally got alot of the new search stuff out

**Comment by reshadn** [comment]
I'll take a look at this today iA.
Goal: Don't allow search function to be called via "enter" button or "search magnifying glass" click when the input field is empty.
