### ISSUE TITLE
BISMILLAH TEXT DOSENT EXIST / LOAD!!!

### ISSUE THREAD

**Issue by ATouhou** [quran/quran.com-frontend#144]
![skaermbillede 2015-10-16 18 25 50](https://cloud.githubusercontent.com/assets/6802820/10547228/693fb41e-7433-11e5-9fb6-2f3e88415552.png)

**Comment by mmahalwy** [comment]
Yeah, it's broken for some reason @ahmedre we need to deploy

**Comment by mmahalwy** [comment]
@ATouhou is this fixed now?

**Comment by ATouhou** [comment]
Yes it is fixed :-) But the text is not high resolution and looks blurry on my screen. I think I posted another issue about this
