### ISSUE TITLE
SEARCH ENGINE IS DEAD

### ISSUE THREAD

**Issue by ATouhou** [quran/quran.com-frontend#153]
![image](https://cloud.githubusercontent.com/assets/6802820/10710121/6bb124ae-7a4a-11e5-8d3b-26b12a086e59.png)

**Comment by ahmedre** [comment]
fixed it for now by restarting - will try to look into these issues this weekend insha'Allah.

**Comment by ahmedre** [comment]
jazakAllah khairan for opening this
