### ISSUE TITLE
Reading Mode Is Only Toggling Expand/Collapse Navigation Menu

### ISSUE THREAD

**Issue by tysteiman** [quran/quran.com-frontend#160]
Trying to toggle reading mode toggles navigation menu collapse instead.

![reading](https://cloud.githubusercontent.com/assets/11522852/10846523/f474f7a2-7f18-11e5-8894-4fd2bda59e17.JPG)

**Comment by mmahalwy** [comment]
Hmm... that is not correct... hmm will fix inshallah

**Comment by mmahalwy** [comment]
This will be fixed with new rewrite
