### ISSUE TITLE
Unlimited scrolling not working. Gets stuck saying 'Loading...'

### ISSUE THREAD

**Issue by AskYous** [quran/quran.com-frontend#165]
I went to http://quran.com/60, then scrolled down to load more *Ayaahs*, but it's been saying "Loading..." for 10 minutes now without loading the next *Aayahs*.

I'm refreshing the page, and they're still not loading.

![image](https://cloud.githubusercontent.com/assets/791996/10882828/ca5e1500-8122-11e5-85fe-55ff957c221b.png)

**Comment by AskYous** [comment]
I just did a hard reload in Chrome (`Ctrl` `Shift` `R`) and it worked. Maybe that solved it for me. So it could be that it's pulling some files from my cache instead of the latest version.

I know a fix for forcing a user's browser to load the latest version of JavaScript files on demand if you would like it.

**Comment by mmahalwy** [comment]
@AskYous thanks for the heads up - this is an identified bug we have found and fixed in staging:
staging.quran.com

Can you confirm you don't have the same problem? 
@ahmedre we need to deploy to prod. Got many tickets about this problem

**Comment by AskYous** [comment]
Works for me in staging.

**Comment by mmahalwy** [comment]
Okay awesome! Thanks @AskYous I will push tonight inshallah
