### ISSUE TITLE
Bug: "Loading" at the end of a Sura

### ISSUE THREAD

**Issue by ahmedre** [quran/quran.com-frontend#176]
saw this today - this is the last ayah and yet we have "Loading..."

<img width="931" alt="screen shot 2015-11-10 at 8 31 18 pm" src="https://cloud.githubusercontent.com/assets/47771/11083952/0ec62da4-87ea-11e5-8d68-895000464c73.png">

**Comment by mmahalwy** [comment]
Resolved
