### ISSUE TITLE
Abu Bakr Ash-Shatri reciting soorat Al Hashr sounds horrible

### ISSUE THREAD

**Issue by AskYous** [quran/quran.com-frontend#177]
Assalaamu 'Alaikum,

Please listen to Abu Bakr "reciting" Soorat Al-Hashr:
http://quran.com/59

On Chrome and Firefox, it sounds scary and broken.

**Comment by ATouhou** [comment]
The files are broken:

http://verses.quran.com/Shatri/ogg/059012.ogg

**Comment by mmahalwy** [comment]
Thanks for noting this @AskYous i probably wont get to this for a while unforunately
