### ISSUE TITLE
Clicking on the Aayah number after searching does nothing

### ISSUE THREAD

**Issue by AskYous** [quran/quran.com-frontend#179]
![image](https://cloud.githubusercontent.com/assets/791996/11213731/7d34bea6-8cf2-11e5-85c1-8418ba944518.png)

Assalaamu 'Alaikum,

When I click on the *Aayah* number after I [search](http://quran.com/search?q=ridicule) for a word, 3 things happen:

1. The page scrolls to that *Aayah* number I clicked on (which is OK).
2. There is an error on the console log: `Uncaught TypeError: Cannot read property 'addEventListener' of undefined`.
3. The audio player gets stuck loading.

This happens on Chrome, Firefox, and IE.

**Comment by mmahalwy** [comment]
@AskYous thanks for the heads up! Hmm, I will fix this inshallah. I have an idea of what the problem is.
