### ISSUE TITLE
SITE IS DEAD ::: ERROR 504

### ISSUE THREAD

**Issue by ATouhou** [quran/quran.com-frontend#183]
![image](https://cloud.githubusercontent.com/assets/6802820/11555810/2e6a52d2-99a3-11e5-9c8c-9158b542c15f.png)

**Comment by ahmedre** [comment]
jazakAllah khairan - it recovered on its own, but i restarted it just in case.

**Comment by mmahalwy** [comment]
@ahmedre probably search again?

**Comment by AskYous** [comment]
I'm getting a 502 gateway error on http://quran.com/.
![image](https://cloud.githubusercontent.com/assets/791996/11611121/22539ea6-9b72-11e5-9c07-3e5d5e828056.png)

**Comment by mmahalwy** [comment]
fixed!
