### ISSUE TITLE
Exploring search UX

### ISSUE THREAD

**Issue by reshadn** [quran/quran.com-frontend#184]
I think the search functionality is incredibly powerful. I'm interested in refining the search UX in general. I don't know the answer yet but wanted to start a discussion around this and hopefully capture some concrete features to prototype, test and possibly build out.
- How can we return the most relevant ayat?
- How can we provide additional data/graphs, etc to help visualize the results of a search?
- Would people like to see the inter-relationships between ayat with similar words and ayat across various surahs?
- How to integrate search into the reading/learning experience itself?
- How to improve the relevance of search?
- Searching the arabic words even when an english word is entered. Might help with distinguishing various arabic words that have a similar translation.

**Comment by mmahalwy** [comment]
Salam! 

Firstly, great questions! + @ahmedre 

Here is the state of search:
- It's alright
- it could be better
- there is a lot to uncover and many more awesome things to do to make search way more powerful (perfect match for example)
- in some ways, the current search is more powerful than legacy. in others, legacy is more powerful (for example, again, perfect match)

This is purely from a technical standpoint. There is a lot of room for improvement but a challenge i experienced is time. Search takes time to get it right. Indexing takes time. etc etc etc. Also, elasticsearch is so vast and very difficult to learn in the beginning. @ahmedre today suggested rewriting search into it's own service in sphinx. I think there are two valuable things here: 1. its something he is comfortable with, 2. own service is GREAT! I love the idea of this. 

As a UX problem, we haven't done much to be honest with you and SHOULD do way more. Search is something that people really care about. So I am open to suggestions and creating quick iterations on it. So any good idea, lets do it.

What I will do in the coming weeks is rewriting quran.com frontend to make it more pluggable and better in general. It should be more stable once i am done inshallah. I will also write a ton more tests. 

There is a ton of cool things to do with search, just need to do it :)

**Comment by reshadn** [comment]
+1 on the service oriented approach. It'll empower us to do more with current site and potential other sites/apps in the future. I like modularization. =)

From my side I'll spend more time thinking about the UX and share some thoughts with the group.

**Comment by AskYous** [comment]
> Would people like to see the inter-relationships between ayat with similar words and ayat across various surahs?

Yes. I second this.

**Comment by ATouhou** [comment]
When performing search with example 15 pages (on word هذ) it breaks the design make the site too wide on a phone

**Comment by mmahalwy** [comment]
@AskYous I have now imported all of corpus.quran.com's word data in the database and available. What suggestions do you and @reshadn have for this? I think it's cool

**Comment by mmahalwy** [comment]
@ATouhou we need to do some fixing for search and mobile.
