### ISSUE TITLE
Multiple issues with Quran audio playback

### ISSUE THREAD

**Issue by TariqP** [quran/quran.com-frontend#185]
Salam!

Maybe it's because I primarily use Safari, but I have multiple issues with audio playback. For example if I select a specific ayah and then hit play, it'll instead play from the first ayah visible on the page. Sometimes the audio will get stuck and when I hit play again, instead of continuing, it'll start over (from the first ayah visible on the page). If I select a different reciter, it'll instead stay on the same reciter when I hit play again UNTIL I refresh the page (at which point it'll load for several seconds before I can hit play again to start the new reciter). A lot of issues in one issue report, sorry if I sound nitpicky, but just trying to help out. Jazakallah khairan for your efforts.

**Comment by mmahalwy** [comment]
salam @TariqP all good feedback! The audio player needs to be completely rewritten. I will do that in te next 2 weeks inshallah

**Comment by mmahalwy** [comment]
Salam @TariqP will be fixed soon inshallah. Will let you know when

**Comment by AskYous** [comment]
I'm having another issue with the playback similar to the original post above. When I go to http://quran.com/2/40, the change the Aayah number to listen to the audio, it still plays the audio for /2/40 (Soorat Al-Baqarah).

**Comment by dashohoxha** [comment]
I am adding two more issues (sorry if you are already aware of them):
 - The last verse is played in double voice (seems like two players are runing at the same time).
 - The list of verses does not work (at least from the icon it looks like a list that should allow you to select a verse).

I am trying to look at the code to locate the problems, but I am not familiar with React. Besides this, when I run it locally with `npm run dev` , it does not play the audio at all (maybe it is just a temporary issue).
