### ISSUE TITLE
description meta tag needs improvement

### ISSUE THREAD

**Issue by ahmedre** [quran/quran.com-frontend#186]
compare:

http://legacy.quran.com/1/1
`<meta name="description" content="Surat Al-Fatihah [verse 1] - In   the name of Allah , the Entirely Merciful, the Especially Merciful."/>`

and
http://quran.com/1/1
`<meta name="description" content="The Noble Qur&#x27;an in many   languages in an easy-to-use interface."/>`

let's put the verse in the meta description, insha'Allah that should improve SEO.

**Comment by mmahalwy** [comment]
new version will have:

![image](https://cloud.githubusercontent.com/assets/3749095/12069538/c904fb86-afeb-11e5-92de-dbd73ca12562.png)

**Comment by mmahalwy** [comment]
Need to do the verse view though.
