### ISSUE TITLE
"Contact us" redirecting to nothing

### ISSUE THREAD

**Issue by assem-ch** [quran/quran.com-frontend#188]
When clicking on Contact us, it redirect to : https://quran.zendesk.com/hc/en-us which is showing a blank page with message: Account not active

**Comment by mmahalwy** [comment]
Hmm, zendesk took down our account mysteriously.... @ahmedre I am really unhappy with this!

**Comment by abdelouali** [comment]
I do see content on the page at zendesk

**Comment by ahmedre** [comment]
this has been fixed now.
