### ISSUE TITLE
Some verses not displayed correctly when adblocker is used

### ISSUE THREAD

**Issue by yazinsai** [quran/quran.com-frontend#189]
Check it out:

![image](https://cloud.githubusercontent.com/assets/1846034/12700173/f9a68d46-c7f0-11e5-96f3-c722caa108f3.png)

The adBlocker is uBlock, and only seems to affect the formatting on some of the verses. I've since disabled it on quran.com, and it works fine -- just sharing this for the benefit of others that might face the same issue.

**Comment by ATouhou** [comment]
Yes, I experienced this too with "Ghostery", because I blocked google analytics.  The google analytics code is minified into one file with all other JS.  This blocks the entire file.

**Comment by yazinsai** [comment]
Ah -- but why then does it only apply to some verses .. are the verses loaded via AJAX (where one request might have been blocked)?

**Comment by AskYous** [comment]
I experienced this same issue on Chrome and only on Chrome back when beta.quran.com was still up. But now that I see this issue posted, I know think the reason was because I had an ad blocker installed.

It happened on every verse.

**Comment by mmahalwy** [comment]
@yazinsai it's weird that it happens to some ayahs... it's probably our CDN getting blocked, @ahmedre any ideas?

**Comment by AskYous** [comment]
There should be an error message in the console log if an ad blocker blocked it. It would be helpful for @yazinsai to click F12 on your keyboard and post a screenshot if there is an error message.

**Comment by mmahalwy** [comment]
There should be if adblock blocks fonts...

**Comment by mmahalwy** [comment]
Please reopen if still an issue
