### ISSUE TITLE
sunnah.com 

### ISSUE THREAD

**Issue by ATouhou** [quran/quran.com-frontend#191]
assalama aleykoum wa rahmatullahi wa barakatuh.
I wanted to ask if any of you know how the brothers behind www.sunnah.com is?  Is the site still being developed on?

**Comment by ahmedre** [comment]
wa3laikum alsalam wa ra7matullahi wa barakatuh,
i know the brothers working on the site and yes, it's still being maintained (though perhaps at a slow pace these days).
walsalam 3alaikum.

**Comment by ATouhou** [comment]
Okay please let them know if they need some extra help, making the site responsive or other functions

**Comment by ahmedre** [comment]
sure, will do insha'Allah. closing this issue for now.

**Comment by abdelrahman-elkady** [comment]
@ahmedre do you provide any source for public contribution somewhere or not ? 

As I can see, this organization doesn't contain any repos for Sunnah.com projects yet.

**Comment by ahmedre** [comment]
most of quran.com's code is open source, as are our iOS and Android apps, all on Github. most projects have a `CONTRIBUTING.md` file (and we all look at pull requests, though it's good to either do something that has an issue assigned or ask before doing it if it's a new feature, etc).

sunnah.com is currently not open source - if you want to help those brothers out, i can put you in contact, however.

**Comment by abdelrahman-elkady** [comment]
Great, I was just making sure that the source is not there. :+1:  If I got some time and I thought that I can contribute I will contact you inshaAllah
