### ISSUE TITLE
Surah AL-BAQARAH does not load after 240.

### ISSUE THREAD

**Issue by azizur** [quran/quran.com-frontend#192]
I have been trying to get to the last few verse so I started at the top verse 1, and scrolling when I get to verse 240 it says loading... but nothing happens.

I wonder if there is some protection mechanism to stop rapid scrolling?

Loading http://quran.com/2/284 or http://quran.com/2/285 or http://quran.com/2/286 directly works.

There are few other issues, I am seeing when you move about quickly (because I am searching for text to find the correct verse) I know roughly where verses are but search seems not that good matching it for me.

When you also have transliterations on scrolling also very slow.

**Comment by mmahalwy** [comment]
@azizur thanks for the heads up! I will fix this in #187 

The problem for the 240 is probably a silly check on my part to see if you reached end of surah.

**Comment by sharabash** [comment]
seemed to work for me on master

**Comment by mmahalwy** [comment]
closing
