### ISSUE TITLE
Night Mode

### ISSUE THREAD

**Issue by AskYous** [quran/quran.com-frontend#201]
Assalaamu 'Alaikum,

This is a suggestion. I ask you to put a night mode version, which makes the background dark and the foreground (text) white. This makes it easy for me to read Qur`aan after _Fajr_.

**Comment by mmahalwy** [comment]
@AskYous thanks for the suggestion. Need any help implementing this feature?

**Comment by AskYous** [comment]
I wish I had more freetime. I don't plan to implement it myself. Maybe sometime in the future I will.

**Comment by mmahalwy** [comment]
Okay sounds good.

**Comment by sabeurthabti** [comment]
Rather than having another toggle button, any thoughts on maybe having this based on a timer so say from 9pm it will go dark until 4am?

@mmahalwy Can you assign this to me.

**Comment by sabeurthabti** [comment]
Actually a toggle would be better, it might be annoying for it to automatically happen.

**Comment by AskYous** [comment]
I have an chrome extension that inverts colors on pages for night mode. In case someone wants ideas:

![image](https://cloud.githubusercontent.com/assets/791996/17843858/907a598c-67e7-11e6-9e1c-40a4abf8f895.png)

**Comment by mmahalwy** [comment]
Oh nice! that looks good @AskYous

**Comment by UmarOutstanding** [comment]
![colorschemesuggestionnight](https://cloud.githubusercontent.com/assets/4945049/20979638/9838bf34-bca5-11e6-8b50-65bcfbac255e.PNG)
 I can suggest this color scheme

**Comment by arshdkhn1** [comment]
@sabeurthabti Are u working on this ?

**Comment by arshdkhn1** [comment]
@sabeurthabti @mmahalwy I have created this color design for night mode - what are your thoughts ? 
## Mobile 
![mob](https://cloud.githubusercontent.com/assets/16819670/20986345/491b892e-bcee-11e6-81f2-8f7d377013c3.png)
## Tablet
![ipad](https://cloud.githubusercontent.com/assets/16819670/20986356/5adb8038-bcee-11e6-95c8-47c032d16b74.png)
## PC
![comp](https://cloud.githubusercontent.com/assets/16819670/20986371/68a94e5c-bcee-11e6-83a0-2dcde3659c60.png)

**Comment by AskYous** [comment]
@arshdkhn1 Looks good.  I'd like the background even darker, and I the inner box with that lighter shade of gray to go away.

**Comment by mmahalwy** [comment]
+1 on @AskYous suggestion

**Comment by arshdkhn1** [comment]
@AskYous okay.

**Comment by arshdkhn1** [comment]
##mob

![mob](https://cloud.githubusercontent.com/assets/16819670/20996631/df6439b8-bd24-11e6-9929-7e8a4a45d131.png)

##tab
![tab](https://cloud.githubusercontent.com/assets/16819670/20996633/e35fee9a-bd24-11e6-99a4-d207663f98e6.png)

##pc
![pc](https://cloud.githubusercontent.com/assets/16819670/20996638/e92cdd6a-bd24-11e6-8fe0-444834918ac9.png)

**Comment by arshdkhn1** [comment]
I prefer the previous one with some changes for pc layout

**Comment by sabeurthabti** [comment]
@arshdkhn1 I am not working on this. Last design looks +1.

**Comment by mmahalwy** [comment]
+1
