### ISSUE TITLE
update README.md with information about trello board, other things...

### ISSUE THREAD

**Issue by sharabash** [quran/quran.com-frontend#204]
> On an open source project, this kind of information should be open in the public to encourage people to contribute. It could be from suggesting a new feature to I want a challenge myself and implement a feature or fix an issue that is annoying me. Without all those details in public space it hard to know what the team is working on and where a new contributor can help.

Question: is there anything else we can do besides just updating the README.md with "this kind of information" to encourage people to contribute

**Comment by mmahalwy** [comment]
README only although i encourage we make a page on the website itself

**Comment by sharabash** [comment]
I second that motion, maybe stick an Octocat somewhere inconspicuous and a
faded link "did you know this project is open-source?"

**Comment by sharabash** [comment]
waffle.io board is at https://waffle.io/quran/quran.com-frontend, trello is at https://trello.com/b/nzAua2tA/quran-com-frontend -- which do you think is best for our needs as for as project management goes?

trello has better mobile support, waffle has better issue integration
