### ISSUE TITLE
Arabic Aayaat Do Not Fit In Browser

### ISSUE THREAD

**Issue by AskYous** [quran/quran.com-frontend#213]
![image](https://cloud.githubusercontent.com/assets/791996/13749254/c1fe09c0-e9bd-11e5-8587-ca4c1cbc07d7.png)

They cut off at the end. This happens in Chrome and IE Edge, but not Firefox and Opera.

**Comment by mmahalwy** [comment]
hmm, this will be fixed soon.

**Comment by abdelouali** [comment]
i think this one is already fixed:
![image](https://cloud.githubusercontent.com/assets/13354388/15095153/7b7f95b8-14ba-11e6-802d-b521f861af49.png)

**Comment by AskYous** [comment]
Yes, it's working for me now.
