### ISSUE TITLE
explain how to proxy api in README.md

### ISSUE THREAD

**Issue by sharabash** [quran/quran.com-frontend#214]
otherwise the app/frontend "doesn't work"

**Comment by sharabash** [comment]
i had to put up three docker containers: elasticsearch, postgres, and the api.
next, i had to mkdir /var/log/nginx/api.quran.com in the api container to make the api start serving
at that point the localhost:3000 API_URL proxy worked. I'm assuming if I had changed that setting in development.conf to `API_URL=http://api.quran.com:3000` that might also have worked. in any case, developers coming in won't generally have access to those docker containers and seeing as having the api proxy work is a pre-condition to running successfully locally, this bit needs to be explained

**Comment by azizur** [comment]
@sharabash looks like you are the second person to hit that wall just like me.

**Comment by mmahalwy** [comment]
I think we shouldn't use docker in development. we never set it up for that - only for production. That being said, inshallah i will find time today to change how our proxy api works

**Comment by sharabash** [comment]
this is resolved since we're pointing to http://quran.com:3000
