### ISSUE TITLE
put surah info feature on hold until we have a non-wikipedia source

### ISSUE THREAD

**Issue by sharabash** [quran/quran.com-frontend#215]
The problem with wikipedia is that the authors are not necessarily Sunni and even if they were Sunni that doesn't necessarily guarantee that what is written will be correct.

**Comment by sharabash** [comment]
related to #82

**Comment by ATouhou** [comment]
https://muflihun.com/quran/intro/2  Assalamu aleykoum. There is this resource which is  a sunni resource  .  Tafheem-ul-Quran

**Comment by ATouhou** [comment]
Also here is the same resource + 1 more Malik Sura introduction (also sunni(  http://www.alim.org/library/quran/surah/introduction/1/MAL
