### ISSUE TITLE
remove fonts and tafsir from the presentation of search results

### ISSUE THREAD

**Issue by sharabash** [quran/quran.com-frontend#222]
![remove](https://cloud.githubusercontent.com/assets/21639/13980819/324c36ac-f0e9-11e5-8517-29f21e61061d.png)

**Comment by mmahalwy** [comment]
this seems like a backend issue no?

**Comment by sharabash** [comment]
yeah

**Comment by sabeurthabti** [comment]
Closing based on the last comment.
