### ISSUE TITLE
implement search-as-you-type suggestions

### ISSUE THREAD

**Issue by sharabash** [quran/quran.com-frontend#224]
this should match surah names as well as ayah text and translations. if a surah name is the suggestion, clicking that should take you to that surah; if an ayah is suggested, clicking that ayah should take you to that ayah. this is coupled with quran/quran.com-api#27

**Comment by ahmedre** [comment]
we should use Karim's autocomplete api just like we did in legacy. no need to re-implement the backend of this a second time (especially when we're short staffed and have so much to do!)

**Comment by sharabash** [comment]
i want to give a shot with elasticsearch first
