### ISSUE TITLE
Site breaks on long ayah

### ISSUE THREAD

**Issue by ATouhou** [quran/quran.com-frontend#226]
![image](https://cloud.githubusercontent.com/assets/6802820/14064854/e17fa24a-f412-11e5-870e-df56020f4185.png)

**Comment by ATouhou** [comment]
Been like this 1-2 weeks+

**Comment by ATouhou** [comment]
Happens in chrome Version 49.0.2623.87 m

**Comment by mmahalwy** [comment]
being fixed with #221
