### ISSUE TITLE
User can change the text mode

### ISSUE THREAD

**Issue by sharabash** [quran/quran.com-frontend#238]
I don't think we should force word font glyphs, especially because the king fahd quran complex has new quranic fonts that are character based (not word). we could incorporate that font and have an inconspicuous option buried deep under 'advanced settings' somewhere to swap from word font to text (i.e. using the KFQPC font)

**Comment by sharabash** [comment]
but i definitely think now is not the right time to implement this

**Comment by mmahalwy** [comment]
We had this initially no? Then we decided to just go fonts as it's better/easier for us to do more no?

**Comment by sharabash** [comment]
yes that's right, this is a reconsideration for the future in light of
recent development

**Comment by sharabash** [comment]
consider this low priority if we decide we want to do it
