### ISSUE TITLE
loading ayahs upwards

### ISSUE THREAD

**Issue by sharabash** [quran/quran.com-frontend#243]
i.e. if i go to ayah /2/255 i want to be able to scroll up or click something to load more ayahs above without necessarily messing up my scroll position... do we have already have a bug filed for this?

**Comment by azeezolaniran2016** [comment]
Hello all, I would like to take a shot at this. What I've done is search for ayah /2/255 and I noticed that once it fetches it I can't scroll up to ayahs before /2/255. I guess that's the issue.
Now, I just want to ask, is there any expected way to implement this or I can just use my discretion ?
Also, I would appreciate any hint on where to start from ?

**Comment by sabeurthabti** [comment]
@azeezolaniran2016 this might be a tricky first task to start with. Can I recommend: #653? would allow you get some experience with the app. Pleas ping me/us on slack if you require anything.

**Comment by azeezolaniran2016** [comment]
Thanks @sabeurthabti. I'll do #653 then.
