### ISSUE TITLE
UI: Reading mode needs improvement on mobile

### ISSUE THREAD

**Issue by sharabash** [quran/quran.com-frontend#244]
i would personally love if text in reading mode elastically filled out to the page width. also there are various alignment and width issues here and there, like if you start in the middle of a surah the alignment should be left aligned not centered

**Comment by mdsadiq** [comment]
Also It would be nice , When the font size is changed , the verses wrap neatly.
Right now , when font size is decreased or when screen size is small ,the line breaks at the end of verse and next verse starts in new line.

**Comment by mmahalwy** [comment]
Looks great on desktop, but not great on mobile!
