### ISSUE TITLE
internationalizing the application

### ISSUE THREAD

**Issue by sharabash** [quran/quran.com-frontend#245]
we could start with arabic but incorporate a general system for i18n strings; i think the milestone here would be deploying ar.quran.com

**Comment by mmahalwy** [comment]
Could use this: https://github.com/yahoo/react-intl

**Comment by ichigo92** [comment]
Assalam-u-Alaikum!
A really great site MashaAllah, i wanted to ask if you have added or plan to add any other languages for surah info or is the surah info just in english. I couldn't find anything about it in the issues. I would love to help out.

**Comment by mmahalwy** [comment]
@ichigo92 thanks for reaching out - I think before we can have different languages for the surah info, we want to internationalize all the other text (for example 'Next Surah') etc.

**Comment by ichigo92** [comment]
@mmahalwy alright

**Comment by atalebagha** [comment]
I would love to help out in this task.  Also would love to add a feature for tooltips in Arabic langauge that looks up the word in 5+/- known dictionaries:  Lisan Al-3arab, Qamus al Mu7ee6, Maqayees al-Lughah (mainly from baheth.info or other sites) but it would be a lot of work.

**Comment by ATouhou** [comment]
Sounds amazing @atalebagha  :-) Is their db publicly available? Would be better to serve the data from the same application, instead of depending on external API...

**Comment by mmahalwy** [comment]
That would be amazing @atalebagha

**Comment by mmahalwy** [comment]
What I can do is create a PR for the internationalization and let someone take over from there? Or get it running for only english. Happy to do whatever works for whoever wants to take it over.

**Comment by atalebagha** [comment]
ASAK,
@ATouhou I don't think so, but I'm sure we can get our hands on the data since it's public rights.
@mmahalwy sounds good, jazaks

**Comment by naveed-ahmad** [comment]
I'm going to work on i18n Quran.com inshAllah

**Comment by ATouhou** [comment]
We could ask them @atalebagha   for the database.
They have:  Lessan Al-Arab, Maqayyes Allogha, Al-Sahhah, Al-Qamoos Al-Moheet and Al-Ebab Azakher. 
info@baheth.info
https://www.facebook.com/baheth.info/?fref=ts

When having an indexed DB, rest should be easy :-)
