### ISSUE TITLE
Should not let user select ayah past end of Surah

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#248]
For example /1/8 is not possible.

**Comment by abiodun0** [comment]
is someone working on this?. If no I would love to work on it

**Comment by mmahalwy** [comment]
Salam @abiodun0, no one is currently! Would you like to grab it? How can I help guide you?

**Comment by abiodun0** [comment]
Wa Alai Kum salam. I am willing to work on it . I have ran ``` npm run dev``` on the forked repo. But I still do have error generating the main.js file on the repo. Can you help me on setting this up properly on my system?

**Comment by abiodun0** [comment]
Do I need some sort of secret keys? @mmahalwy

**Comment by abiodun0** [comment]
I'm contineously having this error. And the page doesn't seem to display well on my localhost @mmahalwy 
<img width="1670" alt="screen shot 2016-06-13 at 6 49 36 am" src="https://cloud.githubusercontent.com/assets/7931839/15998088/21cf84de-3133-11e6-8f63-40f54cbab253.png">

**Comment by ahmedre** [comment]
set an environment variable for `API_URL` to be `http://api.quran.com:3000`.
make sure you ran `npm install` and `npm run build`

**Comment by mmahalwy** [comment]
@abiodun0 what url are you going to? `localhost:8000` or `localhost:8001`? 8001 is the dev one, not 8000!

**Comment by abiodun0** [comment]
Thanks @ahmedre That was the missing link the `npm run build` I guess someone has to update the read me

**Comment by abiodun0** [comment]
Jazzakumu Lahu Khairan @ahmedre The `npm run build` was what I was missing. Yes @mmahalwy I was using localhost:8001. I guess someone has to update the read me. Let me get to work on it. If either of you have time I would need someone to work me through the code and development process

**Comment by mmahalwy** [comment]
@abiodun0 happy to help. But `nam run build` is not the solution... it is when you're ready to push to production

**Comment by abiodun0** [comment]
Can you drop your skype id or any IM i can send a message?

**Comment by mmahalwy** [comment]
@abiodun0 you can ping me on google hangouts: mmahalwy@gmail.com
