### ISSUE TITLE
surah ayah range URLs don't seem to route

### ISSUE THREAD

**Issue by sharabash** [quran/quran.com-frontend#261]
the request just hangs. i.e., checkout master and try going to /2/100

something between these two commits broke the ability to navigate to an ayah range e.g. /2/100 https://github.com/quran/quran.com-frontend/compare/a1189aa956c34214cde9a2ee82b5d7a32476230c...0356ee68f281c70ed70bea9bdd0602f1041dd716

**Comment by mmahalwy** [comment]
i will look at it when i get home..

**Comment by sharabash** [comment]
fixed
