### ISSUE TITLE
Delete development branches that are already merged to master

### ISSUE THREAD

**Issue by dashohoxha** [quran/quran.com-frontend#262]
I would suggest to delete the development branches (corresponding to pull requests) that are already merged to master (PR closed). Keeping them around serves no purpose and their presence only helps to increase the confusion.

For example I am trying to understand what is going on, what is the current state of the project, and I see a huge number or branches. Most of them (maybe all of them) seem to be related to closed PRs.

Note that when you delete a branch related to a PR, the PR will not be affected, it will still be there (on the list of closed PRs) with all details related to it. So, the development history is still maintained by the closed PRs, although the corresponding branches have been deleted.

**Comment by ahmedre** [comment]
good point - i've closed the merged ones - @mmahalwy can you check the rest?

**Comment by mmahalwy** [comment]
Done. Closing
