### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by azizur** [quran/quran.com-frontend#267]
I was trying to get directly to this http://quran.com/50/53

When I got the `504 Gateway Time-out` error.

<img width="927" alt="screen shot 2016-04-08 at 12 23 46" src="https://cloud.githubusercontent.com/assets/114551/14382342/ebc53b90-fd84-11e5-8538-5770fa343220.png">

**Comment by ahmedre** [comment]
we should fix this.
note that the verse you're referencing doesn't exist (sura only has 45 verses).

**Comment by azizur** [comment]
@ahmedre Yes, I found the correct verse by searching for it.
We need to handle those exceptions.
