### ISSUE TITLE
show plain text until the page fonts load

### ISSUE THREAD

**Issue by sharabash** [quran/quran.com-frontend#268]
this is just an idea, but I think it would be nice -- rather than a flash of garbage characters users see the ayah itself then 2 seconds later it swaps into madani font (e.g. assuming it just loaded)

**Comment by mmahalwy** [comment]
this would be awesome! I have no idea how to implement this though :(

**Comment by mmahalwy** [comment]
I mean, i might have a way but I don't like it...

**Comment by sharabash** [comment]
i've done it before (determining when the font is ready), some kind of
magic -- i forgot how but i'm sure i could recall if i thought hard enough

**Comment by mmahalwy** [comment]
Can use this: https://fontfaceobserver.com/

**Comment by mahboob-awan** [comment]
Salam, guys You are doing great, i am thinking to start contributing this holy project. So i start implemented this feature as my first commit. right?

Then i have a question:
Q: how to do we ensure that two persons are not working on same problem?

**Comment by mmahalwy** [comment]
@mahboob-awan good suggestion, as I am already working on it here!

**Comment by mmahalwy** [comment]
I think a good way to do this is to tag the issue in a PR as early as possible?

**Comment by mmahalwy** [comment]
Okay, just as I have here ^^

**Comment by mahboob-awan** [comment]
@mmahalwy aha, so just create a "wip" and tag the issue and keep working on. Yes, seems a nice plan. Thanks

**Comment by mmahalwy** [comment]
Thank you sir!

**Comment by mmahalwy** [comment]
this is done!
