### ISSUE TITLE
Improving existing translations

### ISSUE THREAD

**Issue by dashohoxha** [quran/quran.com-frontend#272]
I have built a system that helps to improve the translations of (open source) programs: https://btranslator.net/ It allows users to suggest improvements to existing translations.

I think that it can be customized and adopted for the Quran and its translations. We can have a site like qtranslate.org or translate.quran.com with all the verses and their translations. Then, when somebody wants to suggest a fix or a better translation on quran.com, they click on it (or an icon next to it) and are redirected to the translation site (similar to this example: https://btranslator.net/translation-context). Their suggestion is reviewed by the moderators (at least one for each language) and they decide to accept it and make it official (and transfer it to quran.com).

I can start by trying it first with just English and Albanian languages, and later we can add other languages. But I will need the data for these two languages first (and the Arabic text of the Quran). Anyway, for a month or two I will be busy with some other things, but this should not stop us from discussing and planing it right now.

**Comment by dashohoxha** [comment]
Some other issues related to fixing/improving translations:
 - https://github.com/quran/quran.com-frontend/issues/145
 - https://github.com/quran/quran.com-frontend/issues/37
 - https://github.com/quran/quran.com-frontend/issues/38

**Comment by sharabash** [comment]
i like this issue, i'm :+1: on it

**Comment by mmahalwy** [comment]
@dashohoxha I am a fan of this too. It's something we wanted to build previously but no time. I almost see it to be much like stackoverflow; answers and upvotes.

**Comment by dashohoxha** [comment]
Yes, it is somewhat similar to stackoverflow, but not so much.

Forget about building it yourself, it is much more complex than it seems to be. It is easier to start with an existing application and to customize it.

However it is also separated into a back-end (database) and a front-end (UI), which communicate through an API. So, if you don't like the interface, it is quite possible (and maybe quite easy) to build another UI (for example with React). For example, vocabulary (http://v.btranslator.org/) is a simple javascript app that uses this API.

**Comment by abdelouali** [comment]
i like this also @dashohoxha

**Comment by dashohoxha** [comment]
I have started this: https://github.com/Q-Translate
which is basically a clone of this: https://github.com/B-Translator
(with some renaming).

It still needs some work to make it run properly.
Then, maybe it will need some customizations, since it is a bit different from translating programs.

When done, we should have a translating server and API like this: https://btranslator.org/
and also a translating web interface like this: https://btranslator.net/

**Comment by dashohoxha** [comment]
I have installed it here: https://qtranslate.org/ and https://qtranslate.net/
Of course it does not do yet what it is supposed to do.

**Comment by dashohoxha** [comment]
I have made some progress:
 - https://qtranslate.net/qtr/
 - http://info.qtranslate.org/api/
But there is still lots of things to done and to be fixed.
Anybody would like to help, or at least to encourage me by subscribing (watching the project on github)?

**Comment by dashohoxha** [comment]
I have some problems displaying correctly the Arabic text (verses of the Quran).
For example look at this: https://qtranslate.net/qtr/en/2/3 I see there some empty boxes.
The same here: http://info.qtranslate.org/api-examples-js/#translations/get.js 
I also see the same thing on phpMyAdmin when I look at the content of the DB.
And this is very common, not just a single isolated case, for example see this:
https://qtranslate.net/qtr/search?words=unseen&lng=en
I use utf8 as character encoding and the mysql DB is of type utf8-general-ci.
Does anybody know what may be wrong and how to fix it?

P.S. Maybe this is not the propper place to ask for help on this, but I don't know any better place.

**Comment by dashohoxha** [comment]
For your information, the text of the Quran needs the font `me_quran` to be rendered correctly (like this: https://github.com/Q-Translate/qtrclient/commit/508e2c7b520c35ea0010c03312c9c5f2835a60ab)

**Comment by dashohoxha** [comment]
This feature (correcting or improving existing translations) can be implemented simply by adding a link to the corresponding verse on qtranslate.net
For example, to correct the English translation of (2,3), the link should be: https://qtranslate.net/qtr/en/2/3

**Comment by ATouhou** [comment]
Would be better to have this internally and then admin should look through if people submitted valid responses (such as typos etc.) then when he accepts them, they should update a revision nr, and that should be passed in API as well, as well as new feed.  There are multiple english translations and other languages... Other languages will be added to quran.com in the future, so it should use an unique identifier, to connect to the correct translation. (i.e. the shuyukh here are working on a Danish translation, so that should be added at some point when released... I got 3 indexed danish quran translations that are popular here, but they are all translated by some doubtfull individuuals and have some mistakes in them...).
I think it is too early to close this "issue" at its current state

**Comment by dashohoxha** [comment]
@ATouhou  The aim of the site https://qtranslate.net is precisely to double check translations, fix any mistakes or typos, and encourage people to think and discuss about the right translation of the Quran verses. (I also think that this is a useful mental excercise that may help people to understand better the real meaning of the Quran.)

This may include Danish translations as well, if there are people interested about them.

For the time being https://qtranslate.net is on the testing phase and there are also a few things still to be done, before it becomes fully functional. If anybody is interested, we can continue the discussion here: https://github.com/Q-Translate/qtr_server/issues (testing, finding and fixing bugs, improvements, etc.)
If you wish, we can add the Danish translation for testing.

However, related to quran.com, it can just add a link to https://qtranslate.net, in case that somebody wants to correct a translation. This is why I closed the issue. Do you think we should reopen it?

**Comment by ATouhou** [comment]
Yes.  
Most people aren't qualified to translate any verse, so their changes should not be activated right away. I was refering to typos or mixups in quran translations, which there are some dousin reports in the quran-android repo. 

However if the purpose was for adding benefitial tafseer / quotes, / examples to ponder,   i.e. any fawaaid really from any verse,  that would then also be double checked by admin with correct aqeedah and knowledge, before posting, then that would be great :-)   


This way, there would lot's of info about each verse.  
Reason of revealing (azbaal ul nuzol),  commentary from sahaba, any beneficial tafseer and relation to other verses,  if is mansookh or not ,  the miracle of the elequoence of the ayah,  anathing beneficial,  that would be great...
So maybe the qtranslate.org should  pivot into this model and the correcting / report error/mistake  should be implemented directly into quran.com :-)   What do you think ?

**Comment by dashohoxha** [comment]
Before I can understand your speech, you have to explain me what is: tafseer, fawaaid, aqeedah, mansookh, etc. Sorry, I still belong to the domain of the ignorants, not to the people with high knowledge.

> So maybe the qtranslate.org should pivot into this model and the correcting / report error/mistake should be implemented directly into quran.com :-) What do you think ?

I am glad to leave that model to quran.com for implementing, and to stick to the humble goal of fixing translations only.

**Comment by ATouhou** [comment]
Very bad translations below: 
Tafseer: explanation.
Fawaaid: Benefits.
Aqeedah: Matters of belief.
Mansookh: Quranic verses that has been replaced by new verse.


It's good to fix the translations, like in a danish translation somebody just found a typo which made the ayah "hide the truth, while you know" as "hide falsehood, while you know"  
and as you see in these 2 github repos (quranandroid and this)  , there are several typos etc. in many of the popular translations.  

However I do not think anything should be replaced without it being looked upon by an admin. 
There are many sects and many wish to replace ayat such as "istawa 3la l-arsh" to something other than it's real meaning etc.    




So for fixing translations, this should be internal where they just click an "report error / improvement", and it will ask them for details.
Sunnah.com already has this:

![image](https://cloud.githubusercontent.com/assets/6802820/17085713/424b9c26-51df-11e6-8c11-a002acc8a47e.png)


could work as an email, or as an automated system, that when admin edits/updates it will update api and increase revision nr etc, :-)

**Comment by dashohoxha** [comment]
> However I do not think anything should be replaced without it being looked upon by an admin.

In qtranslate.net, it is not a matter of replacing a translation, it is like adding another, alternative, translation. Then it is the community which decides which translation is the most correct and the best one.
But in the end, still it is a qualified/authorized person (you may call him admin), who decides which translations should be transferred to tanzil.net.

I don't understand that thing with revision numbers and api, that you are trying to explain. Why don't you try to understand how qtranslate.net works?

**Comment by ATouhou** [comment]
I do understand how it works brother.

However there are 2 things to be aware of with community driven sites.

Sufi and shiaa will try to edit whatever they don't like.
Allah scorns the majority, multiple places in the Quran and we can't make decisions based on the majority, this concept in itself is flawed.

The version numbers are so that people that had local copies, can do automated system update from API, with new version - or just keep track on fixes.

**Comment by dashohoxha** [comment]
> I do understand how it works brother.

Maybe. But I feel that there are a few important details that you have missed. You can fully understand it only if you try it.

> Sufi and shiaa will try to edit whatever they don't like.

We cannot force our understanding to them, and they cannot force their understanding to us. There is no compulsion in religion. The program can accomodate the views of everybody. Wherever we agree it renforces the agreement, wherever we disagree it allows the diversity.

> Allah scorns the majority, multiple places in the Quran and we can't make decisions based on the majority, this concept in itself is flawed.

The question is: the majority of what? I agree that in questions of personal believes and personal understanding the majority plays little role, although it may be quite useful in other cases.
Anyway, the program can accomodate the views of minorities as well, so there is no need to "fight" about who is right and who is wrong.

> The version numbers are so that people that had local copies, can do automated system update from API, with new version - or just keep track on fixes.

I still think that this is not relevant to qtranslate.net. It leaves versioning up to tanzil.net, as a central authority for translations. Because after being corrected, translations can be exported and re-submitted back to tanzil.net.

However there are means of keeping track of what is going on, what has been changed recently. One of them is RSS feeds.

**Comment by dashohoxha** [comment]
I have made the first release of Q-Translate and some testing is needed:
 - https://github.com/Q-Translate/Q-Translate.github.io/issues/1
 - https://github.com/Q-Translate/Q-Translate.github.io/issues/2

Anybody can help?
