### ISSUE TITLE
transliterate the title instead of translate, i.e. `Al-Qur'an Al-Kareem - القرآن الكريم`

### ISSUE THREAD

**Issue by sharabash** [quran/quran.com-frontend#274]
what do you think @mmahalwy @ahmedre ? I think "the noble qur'an" isn't very familiar in english and doesn't convey the meaning of kareem completely, so I propose changing the site title to `Al-Qur'an Al-Kareem - القرآن الكريم` instead of `The Noble Qur'an - القرآن الكريم`. Also, I don't really care if there's an apostrophe in the Qur'an or not :+1:

**Comment by mmahalwy** [comment]
This looks good, but there should be no `'` and `-`. So `AlQuran AlKareem` as people don't search `al-quran`.

**Comment by sharabash** [comment]
i disagree, i think the hyphen is aesthetically pleasing, just my opinion :)

**Comment by abdelouali** [comment]
It's a good idea @sharabash
