### ISSUE TITLE
Transliteration not showing in new version

### ISSUE THREAD

**Issue by abdelouali** [quran/quran.com-frontend#281]
Salamoualikoem,

I found a new bug, the Transliteration is not showing in the menu of translation in the new version. I went to the legacy version and there it still is viewing.

Not viewing here:
![image](https://cloud.githubusercontent.com/assets/13354388/14588032/9df15ce0-04bf-11e6-8643-bac391f9b3e4.png)

Viewing here:
![image](https://cloud.githubusercontent.com/assets/13354388/14588039/cb08bc78-04bf-11e6-8622-a54f47975e0e.png)

Shokran

**Comment by mmahalwy** [comment]
should be fixed in staging.quran.com

**Comment by abdelouali** [comment]
Thnx Mohamed, i't is indeed fixed in staging.quran.com

Shokran

**Comment by abdelouali** [comment]
it was fixed in the staging.quran.com but it is not fixed in the root website.
