### ISSUE TITLE
"loading ..." appearing after the surah is finished

### ISSUE THREAD

**Issue by ajalger** [quran/quran.com-frontend#286]
I noticed that when a surat is finished, in particular surats that require ayat to load, that "loading ..." appears at the bottom of the page. Other surats do not have this issue because they are short and do not require ayat to load.

**Comment by mmahalwy** [comment]
@ajalger thanks for filing. I noticed this too. Do you want to write a failing test?

**Comment by ajalger** [comment]
@mmahalwy I'll get on it.

**Comment by mmahalwy** [comment]
thanks @ajalger :)

Let me know how I can help
