### ISSUE TITLE
Proposal: Use Mocha for tests

### ISSUE THREAD

**Issue by azizur** [quran/quran.com-frontend#292]
This is proposal is was the result of me trying to put tother a PR for #276.

Since there are hardly much unit tests in the project this is a proposal to introduce unit tests into the project.

- [ ] Setup Mocha tests for unit testing
- [ ] Use chai assertion library
- [ ] Use Sinon.JS for spies, stubs and mocks

@mmahalwy let me know your thoughts

**Comment by mmahalwy** [comment]
Salam! 

Thanks for reporting this. Already one step ahead of you. We use Karma to run the tests in the browser and already have mocha + chai + sinon for testing. See: https://github.com/quran/quran.com-frontend/blob/master/karma.conf.js#L21

As a good reference, take a look at: https://github.com/quran/quran.com-frontend/blob/master/src/components/LazyLoad/spec.js
