### ISSUE TITLE
autocomplete broken

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#294]

**Comment by abiodun0** [comment]
Is anybody working on this?

**Comment by ahmedre** [comment]
this should already be fixed - please re-open if you find that it isn't working!
jazakumAllah khairan.

<img width="813" alt="screen shot 2016-06-11 at 7 04 15 pm" src="https://cloud.githubusercontent.com/assets/47771/15988478/4e9ee9f0-3007-11e6-88eb-3ec5bdd8e7e1.png">
