### ISSUE TITLE
Internal server issue 500 

### ISSUE THREAD

**Issue by mumtazaiet** [quran/quran.com-frontend#296]
When listening Surah Kahf at http://quran.com/18 
found some internal server error at when requesting
this url - http://quran.com/api/v2/surahs/18/ayahs?from=10&to=20&audio=8&quran=1&content%5B%5D=19

.please follow the attached file.
Thanks.

![kahf_2](https://cloud.githubusercontent.com/assets/1639023/15239614/a5b788b8-1901-11e6-8833-8705b4be03f4.png)
![kahf_1](https://cloud.githubusercontent.com/assets/1639023/15239615/a5bebb24-1901-11e6-810b-c96c97020b26.png)

**Comment by mmahalwy** [comment]
Fixed now
