### ISSUE TITLE
[UX] No visual cues on error from server (keeps saying loading...)

### ISSUE THREAD

**Issue by m-adilshaikh** [quran/quran.com-frontend#301]
**CANNOT REPRODUCE**

Have been using the app for a while. I must say the UX is pretty good but one thing bugs me.

When there is an error on response from server, it stays stuck on loading...
I think this is unexpected behavior.

![screenshot from 2016-05-18 00 00 55](https://cloud.githubusercontent.com/assets/8544814/15335422/b6b6379e-1c8b-11e6-9b50-fa9b56dcecaa.png)
## 
### Components Involved
- containers/Surah
- components/LazyLoad

**Comment by mmahalwy** [comment]
@designabyss thanks for filing this. Do you mind helping out with this?

**Comment by designabyss** [comment]
@mmahalwy certainly wouldn't mind but it would be a week till I get free from college and pull my coding keyboard!

**Comment by mmahalwy** [comment]
Okay sounds good! Ping me here when ready :)

**Comment by m-adilshaikh** [comment]
@mmahalwy hey!

I have forked and cloned the project locally, ran npm install (btw it gave some errors in the end about some dependencies whining due to unsupported webpack version). Just point me in the right direction for build now... :)

**Comment by mmahalwy** [comment]
@m-adilshaikh sorry i didnt see your last comment. Would love some help on this :)
