### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by a58221** [quran/quran.com-frontend#304]
The website is not working properly.

**Comment by mmahalwy** [comment]
Can you describe please?

**Comment by a58221** [comment]
![screen](https://cloud.githubusercontent.com/assets/2216621/15340809/16334684-1c51-11e6-9d22-17ee3dfb1b70.png)
I am stuck at this in firefox. Checked in internet explorer, it is working just fine.

But, the transliteration never works for me.

**Comment by mmahalwy** [comment]
Yes, we are finding some really weird problems happening. We are trying to fix it inshallah
