### ISSUE TITLE
Developers helping out on Quran.com

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#307]
I thought I'd create this to solicit feedback on how to best organize a way for developers to help out on the project and how to communicate goals, roadmap, priorities, etc. 

Thoughts? 

CC @ahmedre @sharabash

**Comment by dashohoxha** [comment]
Maybe I am explaining what is obvious, but GitHub issues can be used  for managing tasks as well, not only for reporting bugs.
Tasks can reference or relate to each-other with # (for example #307). Milestones can be used for project planing. Labels can be used to organize and categorize issues/tasks. For eaxample you can create a red label for critical bugs, a brown label for small bugs, a green label for a new feature (to be implemented soon), a blue label for a nice to have feature (to be done sometime in the future, etc.)
You can also use the wiki to describe some guides or rules or steps, etc.

**Comment by ATouhou** [comment]
Trello is a fine tool. 
It can be used as kanban SCRUM  management. 
Make an column of "To be made",  create the tasks.  A developer can sign him self on the task and put an estimated date.

**Comment by mmahalwy** [comment]
I do like the idea of relying heavy on Github for communication. I think many open-source projects do a wonderful job at it! I think the only thing that still, even using tools like Trello, will not solve is communication. Thoughts on that?

**Comment by dashohoxha** [comment]
Trello seems to be great, but it is a general tool (for any kind of project, for any kind of people). I suspect that GitHub is more suitable for developers and software development. I have never used Trello though, so I can't be sure. I can only say that I never needed more features than those offered by GitHub.

**Comment by designabyss** [comment]
I have been using Trello for a while but as said by @dashohoxha , most of it is being handled well here on github.

However for rich communication, have you considered [Slack](https://slack.com/pricing) or [Hipchat](https://www.hipchat.com/pricing) ?

**Comment by AbirFaisal** [comment]
The new Quran.com does not work on mobile phones. However the original legacy.quran.com works perfectly fine. Please stop using flash-player, this is the reason it does not work on mobile phones or on browsers that have flash-player disabled.

**Comment by mmahalwy** [comment]
@designabyss we do have a slack team. Perhaps we should figure out how to open it to everyone

**Comment by ahmedre** [comment]
another suggestion (unrelated to the communications aspect) - but i've seen this on a few projects and loved it - basically add a label for "need help" or "starter task" etc - tasks that we want to do that are good starting points for someone who wants to get started with the code base.

often times, when contributing to other projects, i look for this, and if some things are labeled as such, these are things i know i can start with that are needed but that the team hasn't gotten around to.

**Comment by mmahalwy** [comment]
@ahmedre i am +1 on that

**Comment by ATouhou** [comment]
It is possible to use the kanban structure while keeping Issues in Github using a tool such as huboard.com, which makes trello & 3rd party tools for managing tasks obsolet for this project.
This could help categorizing things in "Urgent, Discussions, Feature suggestions, Bugs,  In-work, , Bugs, Work in progress, Testing,  Completed, etc. " categories.
Assigning developers, dates etc. on each task will help keep the broader overview.

**Comment by mmahalwy** [comment]
I think another order of discussion is getting developers involved. I find it, or perhaps we don't do a good job at it, allowing developers to help out. We haven't had much external help for a while now and wanted to get some feedback on how we can improve this experience?

**Comment by reshadn** [comment]
Salams. Returning after a not-so-short hiatus. 
Although I do see advantages of Slack and other tools I'm always a fan of fewer places/tools/apps.

As for getting more devs involved, some people aren't aware of this project or the fact that you can contribute in a technical capacity. I would start by modifying the "Contribute" page to include the opportunity to get involved in a technical capacity. I'd even push for a call-out on the main page. I'm interested in a weekend "hack-a-thon", virtual or in person, to meet you wonderful people and other devs.

**Comment by mmahalwy** [comment]
@redhae i do agree - we could push more on the website for involvement

**Comment by sharabash** [comment]
one barrier to entry:
the learning curve for reactjs + redux is steep

**Comment by sharabash** [comment]
you could put up a banner ad campaign, and maybe we could hold office hours
to hangout with and help newbies

**Comment by mmahalwy** [comment]
@sharabash good idea. Yes, the learning is unfortunately steep :(

**Comment by dashohoxha** [comment]
I think that the motivation is also important. For example I cannot learn ReactJS just to fix a few bugs in a project. But maybe I would learn it if there were some reusable components that I could use in my project.

**Comment by sabeurthabti** [comment]
I would love to get involved, I think the "starter task" label would be great to get people involved. 

I've been doing React/Redux for a year.

**Comment by mmahalwy** [comment]
@sabeurthabti @dashohoxha @sharabash @ahmedre @reshadn  I added a label to this issue and will use it for the future

**Comment by naveedhd** [comment]
I would like to get involved but don't know where to start :)

**Comment by mmahalwy** [comment]
@naveedhd thanks for offering your help! Check out some of the issues that have the `Great for starters` label

**Comment by suhaibmalik** [comment]
Also, why not have a dedicated page for interested devs that outlines this. I've been using Quran.com for years and just now found out it's on Github.

**Comment by mmahalwy** [comment]
Good idea @suhaibmalik I will add that as a todo list!

**Comment by mmahalwy** [comment]
@sabeurthabti wow! https://github.com/quran/quran.com-frontend/issues/307#issuecomment-226366263

Mashallah, look at you now :)

**Comment by sabeurthabti** [comment]
haha time flies - inshallah we will get more people.
