### ISSUE TITLE
Quran.com does not work on mobile devices.

### ISSUE THREAD

**Issue by AbirFaisal** [quran/quran.com-frontend#308]
The new Quran.com does not work on mobile phones. However the original legacy.quran.com works perfectly fine. Please stop using flash-player, this is the reason it does not work.

**Comment by mmahalwy** [comment]
Salam @AbirFaisal

Thanks for reporting. What mobile device are you using? What's not working? Any more details would help us debug the problem.

Also, we removed flash-player so that's not the root.

**Comment by AbirFaisal** [comment]
Oh sorry your right. Perhaps this is the problem, many of us use adblock which interferes with something:

<img width="1520" alt="screen shot 2016-05-22 at 2 40 42 pm" src="https://cloud.githubusercontent.com/assets/8818686/15455726/2530a522-202b-11e6-8ccf-88d5b4d3e103.png">

**Comment by AbirFaisal** [comment]
Here is another screenshot:

<img width="1519" alt="screen shot 2016-05-22 at 2 47 22 pm" src="https://cloud.githubusercontent.com/assets/8818686/15455756/fd407c6c-202b-11e6-8925-9de66a4d1ae0.png">

**Comment by mmahalwy** [comment]
@AbirFaisal okay, I see what the problem is. There is a bug where if you select no content it throws an error. Please select at least one translation to fix this.
