### ISSUE TITLE
http://quran.com/2/185 returns nothing

### ISSUE THREAD

**Issue by AskYous** [quran/quran.com-frontend#315]
Assalaamu 'Alaikum,

When I navigate to http://quran.com/2/185, it just gets stuck loading.

What's weird is that http://quran.com/2/184 works. I'm having this problem in Internet Explorer and Firefox. The console log was empty:

![image](https://cloud.githubusercontent.com/assets/791996/15560134/6949c42c-229d-11e6-9f15-b6ac1881a340.png)

**Comment by mmahalwy** [comment]
@AskYous thanks for the heads up. Should be fixed now. WE have a cache bug happening.

**Comment by AskYous** [comment]
Yes it's fixed. May Allaah reward you.
