### ISSUE TITLE
Unnecessary extra calls are made to the API

### ISSUE THREAD

**Issue by azizur** [quran/quran.com-frontend#316]
Unnecessary extra calls are made to the API.

Given I am on surahs/114
And all the 6 ayahs have been loaded already
Then I should not see any call to backend API

Actual:
We are making calls to backend API, since I am seeing the following in the log:
`/api/v2/surahs/114/ayahs?from=6&to=12&audio=8&quran=1&content%5B%5D=19`.

**Comment by mmahalwy** [comment]
@azizur this is happening locally?

**Comment by mmahalwy** [comment]
Closing for now. This will happen when disabling server-side rendering and on development env
