### ISSUE TITLE
Surah 114 does not show up on left nav

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#33]

**Comment by abdelouali** [comment]
I think this has to do with the css code.

**Comment by mmahalwy** [comment]
Yep. CSC. @abdelouali can you put a push for this? 

I think the footer needs to be done better.

**Comment by abdelouali** [comment]
as soon as I get home from work I look at it . Insha'Allah

**Comment by muhsinali** [comment]
Please see #41 as this seems to fix it. It seems we just weren't taking into consideration the surah-nav was being dropped down lower disappearing. The scrollbar is also fully visible now which is nice.

**Comment by muhsinali** [comment]
#41 Merged

**Comment by abdelouali** [comment]
Sorry guys but we are moving to another home and I don't have always internet because thé installer needs to come.  Next week I will be back available.

**Comment by muhsinali** [comment]
No worries, barakallahu feekum :)
