### ISSUE TITLE
word by word audio improvements

### ISSUE THREAD

**Issue by ahmedre** [quran/quran.com-frontend#333]
in the last release, @sharabash added a great new hidden feature, which is the word by word data for some of the qaris (such that clicking a word would recite just that word).

i'd like to propose one change, which is instead of playing the word when it's clicked, to instead highlight each word as it plays. since these are still parts of recitation, this will be more accurate (from a listening perspective), and will also add a hugely beneficial feature, which is highlighting whatever is playing (including the words).

**Comment by mmahalwy** [comment]
Fixed by https://github.com/quran/quran.com-frontend/pull/360
