### ISSUE TITLE
Text not clearly rendered in Quran 5 vs 76

### ISSUE THREAD

**Issue by andela-ijubril** [quran/quran.com-frontend#339]
<img width="1271" alt="screen shot 2016-06-17 at 5 22 26 am" src="https://cloud.githubusercontent.com/assets/13223950/16140719/89e21274-344b-11e6-9ddc-40ec6f1a9d67.png">

The text that is highlighted in the picture

**Comment by mmahalwy** [comment]
@ahmedre you saw this right?

**Comment by mmahalwy** [comment]
@ahmedre bump!

**Comment by ahmedre** [comment]
hmm this isn't a font we changed but i can repro this too - i'll look and see if there's anything we can do to the glyph

**Comment by mmahalwy** [comment]
Yeah, confirmed its a font problem
