### ISSUE TITLE
Surahs nav visible above footer

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#34]
![image](https://cloud.githubusercontent.com/assets/3749095/8689831/c9bb4144-2a61-11e5-87ee-d1ef1bd44c6d.png)

**Comment by muhsinali** [comment]
@mmahalwy I don't seem to be having this problem in Firefox...

**Comment by muhsinali** [comment]
@mmahalwy I had previously posted this wasn't happening for me, I was wrong I looked at it incorrectly, afwaan. 

I'm currently working on this.

Would it be good to just pull the footer over also, covering the nav as well?

**Comment by mmahalwy** [comment]
Footer should go over everything @muhsinali

**Comment by mmahalwy** [comment]
going to close this
