### ISSUE TITLE
Facebook/Twiter share

### ISSUE THREAD

**Issue by sabeurthabti** [quran/quran.com-frontend#341]
Ramadam to-do list #312

Some possible designs:

Ayah Share:
![ayahshare](https://cloud.githubusercontent.com/assets/2606228/16167763/1620e850-34f1-11e6-8f47-71a3299f0e90.png)

Surah share:

![surah](https://cloud.githubusercontent.com/assets/2606228/16167796/9ea6dc34-34f1-11e6-8a1a-4d8ad6d261e3.png)

Or we can use the popover for the surah share, similar to the font size popover.

<img width="232" alt="screen shot 2016-06-18 at 01 12 09" src="https://cloud.githubusercontent.com/assets/2606228/16167804/d44f042e-34f1-11e6-923f-8112f69b9ecd.png">

Thoughts? 

- [ ] Twitter/Facebook icons
- [x] Twitter card and Facebook opengraph

**Comment by mmahalwy** [comment]
@sabeurthabti looks awesome mashallah! :)
