### ISSUE TITLE
JS error on local execution 

### ISSUE THREAD

**Issue by mahboob-awan** [quran/quran.com-frontend#348]
After project forked/cloned/npm-installed, executed via following command

``` npm run dev ```

On main page, getting JS error after clicking 1st Surah at:

https://github.com/quran/quran.com-frontend/blob/70fbbfd3e20fd50cb90994b00918ce68355c0c22/src/containers/Surah/index.js#L175

**Comment by mmahalwy** [comment]
@mahboob-awan yep, we found this bug, i'd suggest you checkout https://github.com/quran/quran.com-frontend/pull/343

**Comment by mahboob-awan** [comment]
Fixed in #349
