### ISSUE TITLE
Uncaught TypeError: ayahIds.first is not a function

### ISSUE THREAD

**Issue by mahboob-awan** [quran/quran.com-frontend#359]
![js_error_on_scroll](https://cloud.githubusercontent.com/assets/2077078/16359132/b39382d0-3b42-11e6-8aa9-130b307efc0e.gif)

**Comment by mmahalwy** [comment]
hmmm weird...

**Comment by mmahalwy** [comment]
okay all `ayahIds.first()` need to be replaced with `this.getFirst()` and all `ayahIds.last()` to `this.getLast()`... must have happened with the merge conflicts

**Comment by mmahalwy** [comment]
I can fix it or if you'd like to jump on it?

**Comment by mahboob-awan** [comment]
Please move forward to fix this, what about [eslint errors](https://github.com/quran/quran.com-frontend/issues/357)?

**Comment by mmahalwy** [comment]
okay sounds good. Inshallah the eslint errors will be fixed in that PR/relating PRs
