### ISSUE TITLE
Lint SCSS/CSS files

### ISSUE THREAD

**Issue by mahboob-awan** [quran/quran.com-frontend#361]
[Stylelint] is a modern linter that helps you enforce consistent conventions  and avoid errors in your stylesheets.  Powered by [PostCSS], [Stylelint] can understand any syntax that PostCSS can parse, including SASS and SCSS.

Developer will consider [stylelint-webpack-plugin] for webpack integration.

[Stylelint]: http://stylelint.io
[PostCSS]: https://github.com/postcss/postcss
[stylelint-webpack-plugin]: https://github.com/vieron/stylelint-webpack-plugin

**Comment by mmahalwy** [comment]
yes please!

**Comment by mahboob-awan** [comment]
#403

**Comment by sabeurthabti** [comment]
@mahboob-awan can you close this issue? thanks bro,

**Comment by mahboob-awan** [comment]
should we not merge #403 first?

**Comment by mahboob-awan** [comment]
@sabeurthabti

**Comment by ahmedre** [comment]
merged brother @mahboob-awan's patch #403  - closing this

**Comment by mahboob-awan** [comment]
@ahmedre شکرا
