### ISSUE TITLE
Scroll on reading mode

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#368]

**Comment by sabeurthabti** [comment]
Notice a bug on develop branch for reading mode:

![Uploading Screen Shot 2016-07-03 at 02.57.57.png…]()

**Comment by mmahalwy** [comment]
@sabeurthabti noticed this too - fixed here: https://github.com/quran/quran.com-frontend/pull/377

**Comment by sabeurthabti** [comment]
I might have a solution for this, I'll see if I can spike something. How do you imagine the UI? and Would it just auto scroll on `readingMode` triggered?

**Comment by mmahalwy** [comment]
yep, auto scroll when the reading mode and the audioplayer's scroll mode is turned on
