### ISSUE TITLE
Dutch translation Surah a Nur, Ayah 4

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#37]
There's a little mistake in the translation in dutch of Surah a Nur. 
In Aya 4 in dutch it says "vier en tachtig zweepslagen worden gestraft." which means 84 lashes, but the Aya says 80 lashes.

Could you please let get somebody to change that into: "tachtig zweepslagen" en remove the "vier en"

**Comment by abdelouali** [comment]
Selam brother,
There is a lot wrong with the Dutch translation. We have to do this all over again. Here you have the correct translation of Surah a Nur Aya 4.

"En degenen die de kuise vrouwen valselijk beschuldigen en vervolgens niet met vier getuigen komen, gesel hen dan met tachtig (zweep)slagen en accepteer nooit (meer) een getuigenis van hen. En zij zijn de verdorvenen."

Regards, 

Abdelouali Benkheil

**Comment by mmahalwy** [comment]
Hmm, it may be worth removing the dutch translation then for now?

**Comment by abdelouali** [comment]
No that's not necessary , there are not so many mistakes to completely remove the Dutch Translation . We can bit by bit correct the mistakes.
