### ISSUE TITLE
UI: Add hizb and juz in ayah and reading mode

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#371]

**Comment by maryamklabib** [comment]
@mmahalwy @sabeurthabti Did any tests run with these changes?

**Comment by sabeurthabti** [comment]
I reverted the changes I made for this feature it was not easy as I thought and would require some time. Happy for anyone else to pick it up. 

@maryamklabib It had basic component unit tests.

**Comment by mmahalwy** [comment]
@sabeurthabti @maryamklabib so I created a pages routes: https://github.com/quran/quran.com-api/blob/master/app/controllers/v2/pages_controller.rb

we don't use it and we just make the pages layout using what's already in the frontend store. It might be worth while actually doing it via the API. Thoughts?
