### ISSUE TITLE
Russian translation 39:28

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#38]
I found a incorrect spelling in verse 39:28 of Russian translation. It reads :

Мы ниспослали Коран, в котором нем кривды, на арабском языке, чтобы они устрашились.

It has to read:

Мы ниспослали Коран, в котором нет кривды, на арабском языке, чтобы они устрашились.

Russian word 'нет' means negative in this context it means Quran is without any deviance. And right now your translation reads 'в котором нем кривды' which is incorrect.

**Comment by azizur** [comment]
@mmahalwy How can I help so that simple things like this can be fixed faster. I a bit surprised that an issue like this one not been fixed?

**Comment by mmahalwy** [comment]
@azizur we worry about translations - we are not the authors of the translations nor do we speak Russian, so we are trying to log them for now until one day we have the ability to (whether we have a better system to take care of these potential errors or have someone who speaks Russian). Also, many people interpret things differently, for example 'sodoor' in old english means 'breasts' but some people are offended by that and think breasts = boobs (sorry about the word) when really it's meant for commonly said as 'chest'

**Comment by azizur** [comment]
@mmahalwy I am totally with you. I assumed that we already had links with scholars who speaks native Russian and the above suggestion comes from them.
