### ISSUE TITLE
Analytics : How is share performing 

### ISSUE THREAD

**Issue by sabeurthabti** [quran/quran.com-frontend#382]
Hi, 

Noticed we have segment.io for analytics, we should somehow expose some of the data to help us make data-driven development. I want to know how is the share on surah pages performing, are they getting a decent number of clicked?

`data-metrics-event-name="Share:Twitter"`
`data-metrics-event-name="Share:Facebook"`

**Comment by mmahalwy** [comment]
@sabeurthabti good question. We are not using Segment.io or Mixpanel unfortunately since, well, we won't be able to afford it. We have so many users and events that we really quickly surpass the free tier

**Comment by mmahalwy** [comment]
@sabeurthabti send me an email at mmahalwy@gmail.com
