### ISSUE TITLE
[BUG] Ayah play button not working

### ISSUE THREAD

**Issue by sabeurthabti** [quran/quran.com-frontend#383]
Clicking Play next to the Ayah doesn't work. 

<img width="378" alt="screen shot 2016-07-09 at 19 57 45" src="https://cloud.githubusercontent.com/assets/2606228/16709693/952c6ec4-460f-11e6-9692-d27dfa3e5b4f.png">

Would it be possible to introduce a repository project that would hold a set of functional tests? I introduced functional testing using Webdriver.io(JS) at the company I work for. If possible can we setup a repository `quran/quran.com-functional-tests`. I don't mind owning this.

**Comment by mmahalwy** [comment]
Yes, that has been known for a while and hasnt worked for a while now :S

**Comment by sabeurthabti** [comment]
Ah that's due to it not being implemented https://github.com/quran/quran.com-frontend/blob/develop/src/components/Ayah/index.js#L48

Should be triggering an audio player action for the `next` action with ayahNum

**Comment by sabeurthabti** [comment]
I will submit a PR for this tomorrow inshallah.

**Comment by mmahalwy** [comment]
Yes. Sounds good!

**Comment by sabeurthabti** [comment]
Closing as a fix has been pushed to master, awaiting release.

**Comment by mmahalwy** [comment]
thank you!
