### ISSUE TITLE
Make `Reading mode` in UI more intuitive for new users

### ISSUE THREAD

**Issue by maryamklabib** [quran/quran.com-frontend#389]
I don't find the `Reading` Boolean switch in the UI intuitive.
<img width="186" alt="screen shot 2016-07-09 at 11 30 25 pm" src="https://cloud.githubusercontent.com/assets/4147717/16712061/e88f57ca-462d-11e6-85d1-601b67e8f0f1.png">
<img width="191" alt="screen shot 2016-07-09 at 11 30 40 pm" src="https://cloud.githubusercontent.com/assets/4147717/16712062/e8933908-462d-11e6-85c1-aee50938b9d5.png">

I would find it more clear if I saw something that says **`You are in Verse Mode. Turn on Page Mode`** or something like that. Thoughts? I reckon some people might not know about this feature when they need it.

**Comment by sabeurthabti** [comment]
The `Reading` text might not do the feature justice, but the toggling UI is pretty good consider many users might not be English speakers/readers. Maybe we should introduce an icon of a book or a page and change the text to `Page Mode`.

**Comment by mmahalwy** [comment]
I agree, maybe we need to spell it out more such as 'Page Mode'

**Comment by mmahalwy** [comment]
@maryamklabib you should take over that one :)

**Comment by mmahalwy** [comment]
Going to suggest a checkbox and not the ios switch

**Comment by mmahalwy** [comment]
ty @naveed-ahmad
