### ISSUE TITLE
I just played Surah Al-Nur with recitation of Sheikh Mishrey AlAfsay, but the first ayah was not from Surah Al-Nur.. please check

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#39]

**Comment by abdelouali** [comment]
Selam, 
I just played it to and it seems to work properly. I get the first verse of Surah Al-Nur by Sheikh Mishrey AlAfsay.

Regards,

Abdelouali Benkheil

**Comment by mmahalwy** [comment]
@abdelouali thanks for confirming. Closing
