### ISSUE TITLE
basmallah broken on ie

### ISSUE THREAD

**Issue by ahmedre** [quran/quran.com-frontend#396]
internet explorer 11 has the basmala as broken
<img width="838" alt="screen shot 2016-07-10 at 7 53 29 pm" src="https://cloud.githubusercontent.com/assets/47771/16718810/13bb9f6c-46d8-11e6-916b-01a8047869fe.png">

if i had to guess, the eot file is missing.

**Comment by mmahalwy** [comment]
@ahmedre probably is!

**Comment by mmahalwy** [comment]
@ahmedre is this still broken?

**Comment by mmahalwy** [comment]
@ahmedre fixed?

**Comment by ysofi** [comment]
Yes @mmahalwy 

Looks like it's still broken.

**Comment by naveed-ahmad** [comment]
this was fixed long ago!
