### ISSUE TITLE
search button styling weird on ie 11

### ISSUE THREAD

**Issue by ahmedre** [quran/quran.com-frontend#397]
<img width="275" alt="screen shot 2016-07-10 at 7 54 36 pm" src="https://cloud.githubusercontent.com/assets/47771/16718823/41a64a44-46d8-11e6-8896-3aa1dfe7bba1.png">

**Comment by mmahalwy** [comment]
Yeah... ie is the....

**Comment by mahboob-awan** [comment]
IE try his/her best to align with W3C specs but some browsers are tried to be smart...

> On inherited properties, the initial value may be surprising and you should consider using the inherit, unset, or revert keywords instead.
https://developer.mozilla.org/en-US/docs/Web/CSS/initial#Browser_compatibility 

i fixed it and send a pull request. Thanks @ahmedre

**Comment by mahboob-awan** [comment]
#404

**Comment by mahboob-awan** [comment]
@ahmedre  close this issue.

**Comment by ahmedre** [comment]
jazakAllah khair bro
