### ISSUE TITLE
"Previous/Next Surah" when reading first/last surah.

### ISSUE THREAD

**Issue by srifqi** [quran/quran.com-frontend#398]
If you tried to click on Previous Surah while reading Surah Al-Fatihah or to click on Next Surah while reading Surah An-Nas, you will get message:

> Surah is out of range. Please go to thehome page and select a Surah/Ayah

Can we hide/disable that button?

The location of the button:
![previous surah button in Al-Fatihah](https://cloud.githubusercontent.com/assets/4017302/16773238/5c203182-4881-11e6-84a2-d85a5df39130.PNG)

**Comment by sabeurthabti** [comment]
@srifqi can you provide screenshots? I am not seeing previous or next on either of those surahs.

**Comment by srifqi** [comment]
@sabeurthabti I've uploaded the screenshot in [the first comment](https://github.com/quran/quran.com-frontend/issues/398#issue-164860012).

**Comment by mmahalwy** [comment]
@sabeurthabti @srifqi i can replicate this behavior. Not sure why this is happening but we can put a fix for it inshallah.

**Comment by srifqi** [comment]
@mmahalwy Thank you for your fast response. Don't forget to hide/disable "Next Surah" in An-Nas. :smile:

**Comment by sabeurthabti** [comment]
@mmahalwy @srifqi I was looking at the bottom of the surah :(

**Comment by mmahalwy** [comment]
Yeah, I think what we can do is just not call the function in the `onClick` callback. That's the quickest fix, cause from a UI it looks disabled but not from a functional point :) 

@srifqi my pleasure :)
