### ISSUE TITLE
Every time I play a surah, the sheikh will  after a certain number of verses. 

### ISSUE THREAD

**Issue by abdelouali** [quran/quran.com-frontend#40]
Is it just me or others also?

**Comment by muhsinali** [comment]
@abdelouali the sheikh will what akhi?

**Comment by abdelouali** [comment]
Salaam brother, sorry but the sheikh will stop reciting after a certain number of verses. 

Wassalam

**Comment by mmahalwy** [comment]
hmm can you tell me more of what happens? Do you see the console in the browser and see if it errors and with what error?

**Comment by abdelouali** [comment]
The first error I get is: Failed to concat the ayahs 11 21
and the second one: Uncaught TypeError: Cannot read property 'pause' of undefined

**Comment by abdelouali** [comment]
![image](https://cloud.githubusercontent.com/assets/13354388/8880771/65a53368-323b-11e5-8e8c-603924ae7f56.png)

**Comment by mmahalwy** [comment]
hmmm... i will write tests to try to fix for this... i thought i fixed this and it should be fixed... ugh
