### ISSUE TITLE
Changeing 'From' in ranged repeat puts repeat back to single

### ISSUE THREAD

**Issue by AskYous** [quran/quran.com-frontend#409]
Basically, it's impossible right now to change the 'from' section of a ranged-repeat because it toggles the repeat back to 'single'.

**Comment by mahboob-awan** [comment]
@mmahalwy are You working on? should i start looking this issue?

![anim](https://cloud.githubusercontent.com/assets/2077078/17083104/2e625c44-51ae-11e6-8d9f-21afec882d98.gif)

**Comment by mmahalwy** [comment]
@mahboob-awan please do! That is weird :S
