### ISSUE TITLE
[Feature Request] Bookmark/Save Ayahs

### ISSUE THREAD

**Issue by sabeurthabti** [quran/quran.com-frontend#413]
Via Zendesk:

> Hey Guys,
> Quran.com by far has given me the best online Quran experience so far, I am regular visitor and I suggest it to everybody all the time. Being a regular visitor and a personal researcher i felt a new feature can impact largely here. And the feature is Ayah Tagging.
> 
> Ability to do an Ayah Tagging for each verse Privately and Publicly will be a huge advantage. Example: User will log in to save  all ayah related his Daily Reading Verses, or user will save and read all Commandment Related Versus, All Manner Related Verses, All Scientific Miracle Related Versus, All Dawah Relaed Verses. Like i said, these Ayah can be Private and Also Public [Governed by Admin for greater benifit].
> 
> I hope you would agree to it and look forward to hear from you.
> 
> Zazakallaha and Warm Regards,
> Sami

**Comment by ATouhou** [comment]
Agreed would be a great feature, and in this combination could add a "hifdh" log.
Hifdh log could be extended with reminders if not X ayat have been memorised each X days.

**Comment by sabeurthabti** [comment]
@ATouhou this would require a lot of back-end work which apparently "we" will inshallah get round to doing.

**Comment by mmahalwy** [comment]
@maryamklabib and I should be getting together next week to bootstrap the backend project.
