### ISSUE TITLE
[BUG] bismillah broken 

### ISSUE THREAD

**Issue by sabeurthabti** [quran/quran.com-frontend#416]
<img width="974" alt="screen shot 2016-07-28 at 22 22 34" src="https://cloud.githubusercontent.com/assets/2606228/17229994/fbf4bcb8-5511-11e6-8a93-e386965d8006.png">
https://quran.com/40
Regression introduced.

**Comment by ahmedre** [comment]
yep, this is because i am not done with https yet.

some of the things left:
- static needs to be https
- verses needs to be https
- setting for cdn needs to be set to https

**Comment by ahmedre** [comment]
(it's not a code bug, it's just that because i haven't updated the cdn to be https yet, chrome fails to load the font since you're going from something https to http, which is considered insecure).
