### ISSUE TITLE
Make the Arabic lettering of the Surah even smaller to save header space. (On my laptop it takes up a fifth of the screen's height while in fullscreen mode. The laptop screen size diagonally is around 12 inches.)

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#43]

**Comment by muhsinali** [comment]
I'm also on a relatively small laptop and when adjusting the font size I'm only seeing about 1/2 another ayah and that's when the font is tiny. This would be related more to the padding of the ayah itself, no? Not just the font size

**Comment by azizur** [comment]
We should move the font-sizing relative em (`rem`) based that way browser will adjust accordinly.

**Comment by mmahalwy** [comment]
+1

**Comment by sharabash** [comment]
+1
