### ISSUE TITLE
Bump react to 15.x

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#439]

**Comment by sabeurthabti** [comment]
This is proving much harder than expected, there is some issues with react-bootstrap (https://github.com/react-bootstrap/react-bootstrap/issues/1994)

I would suggest we go to React `15.2.1` until a proper fix has been made within the bootstrap library.

**Comment by mmahalwy** [comment]
I think there is a slight fix deployed. Still some things are throwing warnings.

**Comment by mmahalwy** [comment]
oh dear. We should do this ASAP.
