### ISSUE TITLE
copy and paste the content

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#44]
There must be a way to listen for highlight or clipboard and provide the actual arabic text for the copied. I have to look into it but i have an idea of how. We just need to get off our clipboard!

**Comment by muhsinali** [comment]
![clippy](https://cloud.githubusercontent.com/assets/11522852/8792598/101822be-2f72-11e5-8379-61bc5b71f333.jpg)

**Comment by mmahalwy** [comment]
Closing for now
