### ISSUE TITLE
Load third party JS using async

### ISSUE THREAD

**Issue by sabeurthabti** [quran/quran.com-frontend#444]
I ran webpagetest[1] against the website and we have some things to improve around `time to first byte`. 

<img width="964" alt="screen shot 2016-08-11 at 08 18 36" src="https://cloud.githubusercontent.com/assets/2606228/17581241/4997d75e-5f9c-11e6-871e-e93fa3d41b01.png">

`<script src="https://cdn.ravenjs.com/3.0.4/raven.min.js" async ></script>`

1.https://www.webpagetest.org/result/160811_AY_9BP/

**Comment by ahmedre** [comment]
for raven specifically, this looks like it may be tricky, since setting it to async means we don't get errors during loading.

see this for more details: https://github.com/getsentry/raven-js/issues/169

**Comment by sabeurthabti** [comment]
Yeah kinda felt that would be an issue, especially google analytics and mixpanel. 

Maybe we can bundle raven/mixpanel as part of our javascript, if anything to save on http calls.

**Comment by sabeurthabti** [comment]
However we can serve them via CDN and add the appropriate cache headers.

**Comment by mmahalwy** [comment]
I am not sure if webpack has the ability to download/bundle unless we download them. I think we could load raven in sync but don't need mixpanel to be.

**Comment by mmahalwy** [comment]
Okay seems that mixpanel and zendesk load their script via `async`. All that script we have is doing is adding their code.

**Comment by sabeurthabti** [comment]
@mmahalwy They're being downloaded before DOM is ready? 

We can download the files locally and bundle them as part of our script.

**Comment by mmahalwy** [comment]
no no i mean it's a script from them that embeds their script async
