### ISSUE TITLE
Display a verse using simple combination of HTML, CSS and TTF files (without image generation)

### ISSUE THREAD

**Issue by abdallah-amoudi** [quran/quran.com-frontend#447]
Salam Alikum,

I want to write a verse in HTML and display it the webpage using simple combination of HTML, CSS and TTF files (without image generation) . Something similar to the following:

The HTML code:
`<h1>قُلْ أَعُوذُ بِرَبِّ النَّاسِ</h2>`

What is displayed in the page will be similar to the image attached
![q_html](https://cloud.githubusercontent.com/assets/14120439/17641655/a377bd2a-6131-11e6-8cb9-121febfad973.png)

Please advise
@mmahalwy

**Comment by mmahalwy** [comment]
@abdallah-amoudi thanks for writing this. We don't have a way to embed ayahs just yet. `<h1>قُلْ أَعُوذُ بِرَبِّ النَّاسِ</h1>` will work but will not display like the image above because that requires CSS, fonts and the correct font code.

**Comment by sabeurthabti** [comment]
would be cool, we can make embeddable ayahs, not sure how much value that would have.
