### ISSUE TITLE
Surah No. 110 , Verse No. 01, 

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#45]
Surah No. 110 , Verse No. 01, 
There is missing the word "Help" in sahih international. 
"When the Help of Allah has come and the Victory" 
will be better instead of "When the victory of Allah has come and the conquest"

**Comment by ATouhou** [comment]
But this is the officiel released text of sahih international. Isen't it wrong to change it and still title the translation as "sahih international"? I think the group behind the translation in Jeddah, should be contacted to explain why they chose to translate it this way and if they will revise it. Else it should stay that way in my opinion.

**Comment by ahmedre** [comment]
Agreed, in this particular case, we should not change this. We file many of the complaints people give about the translations and then consider them on a one by one basis. 

For Sahih International, for example, the version on our site is the second edition. I checked the latest (third edition) and it matches what's there, "110:1 When the victory of Allah has come and the conquest."

Generally, the direction we are discussing is as follows - if an error is an obvious typo, or if we can find that it's different in a printed edition, we will change it. 

In other cases (example other languages), if we decide to make a change, we'll make it in a different color or font or something and denote that it's not part of the translation, but part of user feedback or suggestions. Until now, however, we haven't done this.

Open to any suggestions you have though.
Walsalam 3alaikum.

**Comment by ahmedre** [comment]
Closing as won't fix.
