### ISSUE TITLE
Decrease the number of fonts or put them somewhere else! 

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#46]

**Comment by mmahalwy** [comment]
Really should be CDNing them...

**Comment by mmahalwy** [comment]
Thanks @ahmedre !

**Comment by ahmedre** [comment]
these are already cdn-ed.
let's move them github's large file storage maybe to clean them out of this repo? this has the added benefit of making builds much faster...

**Comment by mmahalwy** [comment]
@ahmedre okay awesome. That's all you!

**Comment by mmahalwy** [comment]
closing this
