### ISSUE TITLE
Suggestion: Hovering over the Arabic Aayah number shows the number in English

### ISSUE THREAD

**Issue by AskYous** [quran/quran.com-frontend#461]
It would be great to have the English number appear over the Arabic number on mouse hover, just like how hovering over an Arabic word shows the English meaning:

![image](https://cloud.githubusercontent.com/assets/791996/17877414/f817e4aa-6897-11e6-8db2-bf101081e67f.png)

**Comment by mmahalwy** [comment]
Agreed! Especially if it says 'Verse 267' since all my non Muslim friends always ask what that marker is

**Comment by mmahalwy** [comment]
I'd be excited and really looking forward for some help on this one! Who wants it :)
