### ISSUE TITLE
lgtm integration

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#463]
@sabeurthabti @ahmedre @sharabash 

Wanted to get your thoughts on this:
https://lgtm.co

**Comment by sabeurthabti** [comment]
@mmahalwy +1 from me. Only issue it might become a blocker. Lets try it!

**Comment by mmahalwy** [comment]
Okay, we can definitely give it a try :)

**Comment by abdelrahman-elkady** [comment]
Check the new [**Reviews**](https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features) feature in GitHub now, it can be a great alternative

**Comment by mmahalwy** [comment]
@abdelrahman-elkady yes! heard about it today!

**Comment by ahmedre** [comment]
i prefer github's over a third party tool, so i'd say we use those as well.
