### ISSUE TITLE
Non-existant ayat should return 404 but returns 500

### ISSUE THREAD

**Issue by matmar10** [quran/quran.com-frontend#468]
Steps to reproduce:
- Construct a non-existant ayat URL, e.g. https://quran.com/23/150

Actual behavior: 
- 500 status code
- Generic "Internal server error" page

Expected behavior:
- 404 status code
- Friendly "Ayat not found" error page

**Comment by mmahalwy** [comment]
+1 on this

**Comment by matmar10** [comment]
I will take a stab at this.

**Comment by ahmedre** [comment]
link to corresponding api task here - https://github.com/quran/quran.com-api/issues/74 - not sure if the api is doing the right thing or not, we should check that first.

**Comment by mmahalwy** [comment]
@ahmedre might not

**Comment by naveed-ahmad** [comment]
@ahmedre  @mmahalwy API is fine, following api call will return empty array as it should. Frontend should handle this case.

https://quran.com/api/v2/surahs/1/ayahs?from=10&to=12

**Comment by mmahalwy** [comment]
@matmar10 any luck on this?

**Comment by aslamhadi** [comment]
how is this going? or do we have mockup on how should the website look like when this happens? maybe I can help 🙇

**Comment by mmahalwy** [comment]
We do need help! @aslamhadi want to take it over?

**Comment by abdulapopoola** [comment]
I should inshaaha Allaah be able to pick this one; @aslamhadi do you want to take this one? If not, I can take a stab.

**Comment by aslamhadi** [comment]
I'm working on it :) @mmahalwy @abdulapopoola
