### ISSUE TITLE
better handling of sura/ayah urls

### ISSUE THREAD

**Issue by ahmedre** [quran/quran.com-frontend#471]
- some people try urls like quran.com/3:42 - while these aren't the standard, we should handle them (redirect to /3/42).
- when people use ranges, sometimes they flip the range (i.e. /23/5-4 instead of /4-5 - let's fix these if we can ).
- non-existant ayahs #468

**Comment by atalebagha** [comment]
PR for this issue:  https://github.com/quran/quran.com-frontend/pull/475

**Comment by mmahalwy** [comment]
Thank you!
