### ISSUE TITLE
Remove/Populate tooltip on search results

### ISSUE THREAD

**Issue by sabeurthabti** [quran/quran.com-frontend#472]
Reproduce:
Visit: https://quran.com/search?q=%D8%AA%D9%8E%D8%A8%D9%8E
Hover over a word and the outcome will be as shown below:
## <img width="935" alt="screen shot 2016-08-30 at 10 44 19" src="https://cloud.githubusercontent.com/assets/2606228/18084573/a8f28eda-6e9f-11e6-835c-a1fea915f813.png">

We can either hide the tooltip or populate it with the correct translation.

**Comment by srifqi** [comment]
Can we get translation from server like we usually read in normal situations?

**Comment by sabeurthabti** [comment]
@srifqi yes, based on what I remember.

**Comment by mmahalwy** [comment]
Yep. Just have to do it on the API side. I can get on that inshallah :)

**Comment by hassansin** [comment]
How about this quickfix: https://github.com/quran/quran.com-frontend/pull/474 ?
