### ISSUE TITLE
Feature for memorization

### ISSUE THREAD

**Issue by kickthemooon** [quran/quran.com-frontend#476]
My feature suggestions would be:

That users can select Ayat that they would like to be repeated over and over again so it can help them with memorization or to practice the parts of Qur'an they already know.

JazzakAllah khair.

**Comment by atalebagha** [comment]
Kind of like an A-B Repeat but for ayat?

**Comment by kickthemooon** [comment]
sorry, didnt see the repeat options which has the range, so repeating a chosen ayat can be done, awesome

**Comment by mmahalwy** [comment]
Maybe a button to click on an ayah that will trigger the range repeat but only for that ayah?

**Comment by atalebagha** [comment]
What if you want multiple ayas?

**Comment by mmahalwy** [comment]
Hmm, currently you can do that. but for the purpose of repeating that single ayah, we can always add something on the ayah level to click and play-repeat
