### ISSUE TITLE
Repeat Single Ayah

### ISSUE THREAD

**Issue by sabeurthabti** [quran/quran.com-frontend#478]
Add a repeat toggle near each individual ayah. To reduce noise we can have an icon appear whenever a user hovers over an ayah, 

Reference: #476

**Comment by mmahalwy** [comment]
+1

**Comment by arshdkhn1** [comment]
Clicking button while hovering can be difficult. What about repeat toggle button below play button?

**Comment by naveed-ahmad** [comment]
Looks like there is already repeat single aya setting on staging. So maybe close this :)
