### ISSUE TITLE
Public facing API with tafseer

### ISSUE THREAD

**Issue by mmrs151** [quran/quran.com-frontend#482]
Assalamualaikum,

First let me start by asking Allah swt to grant you Jannatul Ferdous for your work.

Secondly, may I ask your API to be publicly available for developers. You have the API and you made great use of it. But you can multiply your rewards to infinity when you will allow others to use it and make use of it as well.

Thirdly, can you add the tafseer option as well just as the quran please.

**Comment by mmahalwy** [comment]
Salam! 

Thanks for reaching out! We do have an API and it's pretty much public, since we don't limit or have API keys, for now at least. You can find the repo here: https://github.com/quran/quran.com-api

We do need to add tafseer. We held off until we can provide English too

**Comment by mmrs151** [comment]
Jazakallah for your time for replying the query. 

I have seen the API, but I was looking for something hosted so I can use my poor PHP knowledge to integrate with my wordpress plugin.

Unfortunately I don't know RUBY, I wish I knew so I could be a part of the project as well.

Is there any chance you can host the API somewhere?

Regards,
Mustafiz.

**Comment by mmahalwy** [comment]
@mmrs151 never too late to try to learn! I learnt many things while doing the quran.com project and we highly encourage it! I'd be happy to guide you if you wish to learn it seriously.

It is hosted on api.qruan.com
