### ISSUE TITLE
Surah 22 links to 2:21

### ISSUE THREAD

**Issue by ysofi** [quran/quran.com-frontend#483]
When opening a link to surah Al-Hajj (22) it displays Al-Baqarah starting from ayah 21

Can reproduce in Edge 39, FF 49, Chrome 54. 

Explicitly going to the first ayah by typing quran.com/22/1 displays the correct surah.

![quran_22](https://cloud.githubusercontent.com/assets/17520348/19812945/22061fbe-9d6a-11e6-836e-4266f44db1e9.png)

**Comment by sabeurthabti** [comment]
Salam @ysofi, 

Thank you for filing this issue. I am not able to reproduce this issue on chrome 54 or FF 39. Please delete your cookies and browser cache. Let us know if you still experience the issue. 

<img width="740" alt="screen shot 2016-10-29 at 18 00 51" src="https://cloud.githubusercontent.com/assets/2606228/19831431/a6c16a50-9e01-11e6-8a6a-6efc5e29a7da.png">

**Comment by ysofi** [comment]
Wa'alaikum salaam @sabeurthabti 

Yeah I saw it working the following morning. It was a bit strange as I did clear cookies and cache as well as testing on a few different devices and it definitely was showing from 2:21

I would rather it being an error on my end and in any case, it is displaying correctly now Alhamdulillah.
