### ISSUE TITLE
Hosted public facing API and tafseer #482

### ISSUE THREAD

**Issue by mmrs151** [quran/quran.com-frontend#484]
Jazakallah for your time for replying the previous query.

I have seen the API, but I was looking for something hosted so I can use my poor PHP knowledge to integrate with my wordpress plugin.

Unfortunately I don't know RUBY, I wish I knew so I could be a part of the project as well.

Is there any chance you can host the API somewhere?

I have couple of things using your service already, 
1. https://wordpress.org/plugins/quran-verse-a-day/ 
   This is the plugin used by so many mosques and Islamic professionals 
2. https://www.facebook.com/quran.verse.a.day
   For this page I would be happy to integrate Bengali translation as I get many user requests for it. I will also be glad to use your Tafseer over others.

Regards,
Mustafiz.

**Comment by sabeurthabti** [comment]
@mmrs151 

As @mmahalwy said the API is publicly available. However our API is not documented:

Here are the REST endpoints

### Get Surah Info:
`https://quran.com/api/v2/surahs/{SURAH_NUMBER}`
example:  `https://quran.com/api/v2/surahs/1`

### Get Ayahs
`https://quran.com/api/v2/surahs/1/ayahs`

### Get Ayahs pagination:
`https://quran.com/api/v2/surahs/1/ayahs?from=1&to=30`


Hope that helps!

Salam

**Comment by mmrs151** [comment]
Thanks, I understand now.

**Comment by mmahalwy** [comment]
@sabeurthabti @mmrs151 I created this a while ago :)

https://quran.com/api/docs
