### ISSUE TITLE
Loading always shows when reaching the end of the surah

### ISSUE THREAD

**Issue by Gujarats** [quran/quran.com-frontend#485]
Hi, I was confused when I've reach the end of the surah, it says keeps loading I thought there were another ayat but it turn out its the last ayat. 

I found it  on quran.com/4/170 this surah An-nisa has 176 ayats, and this is the screenshots

![bugs quran com](https://cloud.githubusercontent.com/assets/10476678/19836760/cdd09504-9edc-11e6-9019-a8f2094744b2.png)

**Comment by mmahalwy** [comment]
@Gujarats thanks for reporting this. Would you like to give this a try?

**Comment by Gujarats** [comment]
@mmahalwy yeah sure, I will give a try. Let me see if I can do something

**Comment by Gujarats** [comment]
@mmahalwy I'm not an expert on this field and I'm still learning javascript. So maybe next time :D

**Comment by mmahalwy** [comment]
No worries. One of us will pick it up in the meantime. Looking forward to having you help out!
