### ISSUE TITLE
Links of footer are dead below 990px width

### ISSUE THREAD

**Issue by arshdkhn1** [quran/quran.com-frontend#487]
For width greater than 990px:
![bg1](https://cloud.githubusercontent.com/assets/16819670/20149669/57a19b7c-a6d8-11e6-8f5f-4c624dfe0b44.png)

For width less than 990px:
![bg2](https://cloud.githubusercontent.com/assets/16819670/20149646/3825f9be-a6d8-11e6-8c47-d7059fc17e1e.png)

 I will try to fix this bug.

**Comment by mmahalwy** [comment]
thank you @arshdkhn1 ! looking forward to your PRs

**Comment by arshdkhn1** [comment]
Links are not dead but stacked below the third col because third div has not been given `sm` or `xs` class.
