### ISSUE TITLE
Basic styling issues

### ISSUE THREAD

**Issue by arshdkhn1** [quran/quran.com-frontend#489]
![s1](https://cloud.githubusercontent.com/assets/16819670/20151569/958a3cc0-a6e0-11e6-9495-0b0f33ba3140.png)

In the above picture, you can see there is no padding for first `li` element with text `surahs`. It doesnt look good.  

Second thing to note down here is the width of container having ayats. Their width is greater than 100%. I guess removing negative margin and some styles, will remove this bug.
  
![s2](https://cloud.githubusercontent.com/assets/16819670/20151574/99bef9e8-a6e0-11e6-8464-8a0de797004f.png)

I think navbar is holding too much things, sidebars can be used here which will offer same control in better way. I did not like the styling here. The toggle button (hamburger sign) and font-size of surahs (see second picture) doesnt look good. I will try to post some good options in future for these issues.

**Comment by mmahalwy** [comment]
@arshdkhn1 thanks for the feedback! I agree, the navbar needs some change. It's very confusing. Ideas?

**Comment by arshdkhn1** [comment]
@mmahalwy I think sidebar will be the best option. By sidebar I meant something like this-
![afsd](https://cloud.githubusercontent.com/assets/16819670/20154583/0ec56012-a6ee-11e6-8207-6e3b9cf9919b.png)

**Comment by mmahalwy** [comment]
I agree! @arshdkhn1 want to take it on?

**Comment by arshdkhn1** [comment]
@mmahalwy surely.

**Comment by mmahalwy** [comment]
thank you!
