### ISSUE TITLE
CSS Tooltip causing horizontal scroll on mobile

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#496]
![image](https://cloud.githubusercontent.com/assets/3749095/20383152/7cf8aa7e-ac63-11e6-864d-76969dfa9ed0.png)

**Comment by arshdkhn1** [comment]
@mmahalwy somehow I am not able to reproduce this issue but when I hover over ayah tooltip width's is so small that each word breaks into characters.
![screenshot at 2016-11-17 17-14-10](https://cloud.githubusercontent.com/assets/16819670/20388116/710d7de4-ace9-11e6-9dfb-82358f44844d.png)

**Comment by arshdkhn1** [comment]
@mmahalwy this issue can be tackled easily by adding `word-wrap: normal` css to `::after` pseudo element.
![screenshot at 2016-11-17 17-18-14](https://cloud.githubusercontent.com/assets/16819670/20388212/d8c60eec-ace9-11e6-90d7-45439db6c434.png)
