### ISSUE TITLE
As a user I would like to be able to change script to IndoPak so that I can read the way I was taught

### ISSUE THREAD

**Issue by ohaq13** [quran/quran.com-frontend#505]
quranexplorer has a similar option where you can chose script uthmani or indopak, It would be great to have this option in the app. 

It would be also nice if the app had an option in the setting to donate. The only way to donate seems to be from the website. Some times the eeman is high and you realize how much we have benefited from the app, but then don't know how to donate. I love the fact that there arent constant reminders to donate and leaves it up to the user to figure out how to donate. The only way I could find was via the website and the website had no paypal option.

**Comment by naveed-ahmad** [comment]
+1 for changing Arabic font, Ill actually want to extend this feature request to include following fonts + plus default current font of course :)  

## Pakistan Data Management Services(PDMS) Saleem Font:
![_pdms_saleem_quranfont](https://cloud.githubusercontent.com/assets/701567/20615946/0eee7c04-b300-11e6-884a-a1c395a5811c.gif)

## Al Qalam Font:
![al qalam quran majeed](https://cloud.githubusercontent.com/assets/701567/20616009/c72b7f7e-b300-11e6-8bec-5f2fd9c3316d.jpg)

## Me Quran Font:
![me_quran_font](https://cloud.githubusercontent.com/assets/701567/20616025/f63c677e-b300-11e6-83ee-b35dc79db46d.gif)

## Noor-e-Hidayat Font:
![noor-e-hidayat](https://cloud.githubusercontent.com/assets/701567/20616041/10039be6-b301-11e6-9b6b-a32c5bbd3f02.gif)


All fonts are available here: http://quran.mursil.com/Web-Print-Publishing-Quran-Text-Graphics-Fonts-and-Downloads/fonts-optimized-for-quran

**Comment by mmahalwy** [comment]
Salam folks,

For a while, when we first introduced this new version of quran.com, we had many options to display quranic text (images, tashkeel, etc). We decided to move forward with just the fonts since it gives us the ability to do things like hovers/tooltips/etc. since UTC text will not. At least, we haven't put in the effort because the fonts seemed to work well. 

Let's keep this issue open for discussion about moving forward with this - whether we give users the option to change display text.

**Comment by naveed-ahmad** [comment]
v3 api will return text in indopak, madani and simple script. We can add this feature one v3 integration is finished.

**Comment by mmahalwy** [comment]
+1 @naveed-ahmad

**Comment by mmahalwy** [comment]
Going to close this?

**Comment by saeedjassani** [comment]
SA @naveed-ahmad ,

I am searching for verse by verse Quran text to display in Al Qalam (screenshot in your earlier comment). Can you please guide me where I can get that?

**Comment by naveed-ahmad** [comment]
waAlakim o salam @saeedjassani 

Stay tuned, many good things are coming with beta inshAllah. Checkout the first step, user can change the font :) 
http://beta.quran.com/1/1?font=v2 
http://beta.quran.com/1/1?font=v1

Next is adding the option in UI for font, and text. If you need the data, checkout our api.
