### ISSUE TITLE
styling issues on surah page

### ISSUE THREAD

**Issue by arshdkhn1** [quran/quran.com-frontend#506]
The color of social media icons is a bit different. Cursor type isnt pointer on hovering as well.

![screenshot at 2016-11-23 18-39-13](https://cloud.githubusercontent.com/assets/16819670/20562977/6cd800b0-b1ac-11e6-9736-4a7095ac1632.png)

Options in the head of surah page should be a bit more formatted and aligned for mobile layout.
![screenshot at 2016-11-23 18-37-44](https://cloud.githubusercontent.com/assets/16819670/20563075/e72ee7de-b1ac-11e6-827d-f0f409a49d1e.png)

**Comment by allyraza** [comment]
Currently pngs are being used for social icons and fonts for others, perhaps a more unified approach toward icons across the site would suite better. Symbolset standard package does not contain social icons maybe we can switch it to FontAwsome.

**Comment by allyraza** [comment]
after some digging as it turns out, fontawesome is being included I have attached a link to a patch with minor other changes.
