### ISSUE TITLE
Move Bayyinah lecture alongside other per Ayat actions  

### ISSUE THREAD

**Issue by naveed-ahmad** [quran/quran.com-frontend#512]
## Suggestions 

* Add video icons with tooltip "Watch lecture by Bayyinah" 
* Click on icons will open the video popup
* This will make UI more consistence, all action in one place plus will save lot of spaces

<img width="1309" alt="ayat ui" src="https://cloud.githubusercontent.com/assets/701567/20643886/6ae76e7a-b446-11e6-8fee-7e7a6c9521ea.png">

**Comment by mmahalwy** [comment]
Agree this is probably what we want to do in the future. Right now we want it to be in the user's face because Bayyinah worked really hard in making this videos and we want to maximize the usage.
