### ISSUE TITLE
Add option to close nav draw

### ISSUE THREAD

**Issue by sabeurthabti** [quran/quran.com-frontend#513]
It is not as clear how to close the nav. 

<img width="526" alt="screen shot 2016-11-27 at 11 03 48" src="https://cloud.githubusercontent.com/assets/2606228/20647931/40f8c000-b491-11e6-862e-106f91e1e708.png">

**Comment by mmahalwy** [comment]
We can do
- shadow on the rest of the page 
- have an icon or something besides 'Options'

**Comment by arshdkhn1** [comment]
I guess @sabeurthabti is iphone user.

**Comment by mmahalwy** [comment]
@sabeurthabti thoughts on what to do?

**Comment by sabeurthabti** [comment]
@mmahalwy slap a 'X' in the top right of the draw, and add an dark shade on the main body. My issue was I didn't know how to close the draw

**Comment by arshdkhn1** [comment]
http://codepen.io/arshdkhn1/full/ZBajrE/

**Comment by sabeurthabti** [comment]
@arshdkhn1 thats beautiful
