### ISSUE TITLE
User react-share for social

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#518]
https://github.com/nygardk/react-share

**Comment by aslamhadi** [comment]
hi @mmahalwy 

I'm currently working on this, should I display the share count? Because the `TwitterShareCount` is removed from the API. more https://github.com/nygardk/react-share/blob/master/src/share-counts.jsx#L85-L89

Btw this project is awesome, Barakallahu fiik :)

**Comment by aslamhadi** [comment]
oh and apparently facebook sharer is not working when I try it :( https://github.com/nygardk/react-share/issues/43

**Comment by mmahalwy** [comment]
Hrmm, no worries! Don't neeed counts but shares would be great.

Thanks for your help!
