### ISSUE TITLE
UI for current Ayah

### ISSUE THREAD

**Issue by sabeurthabti** [quran/quran.com-frontend#522]
Hi, 

I think we should only highlight the current ayah when the audio player is triggered. Also the yellow is big strong, it is not naturally fitting. 

<img width="1206" alt="screen shot 2016-12-08 at 11 28 08" src="https://cloud.githubusercontent.com/assets/2606228/21008438/9e2d10c2-bd39-11e6-9ca7-43a84b2ac1fb.png">

Maybe something like:

<img width="1232" alt="screen shot 2016-12-08 at 11 33 10" src="https://cloud.githubusercontent.com/assets/2606228/21008559/242db8c0-bd3a-11e6-8d26-47a9c4382cea.png">

thoughts?

**Comment by mmahalwy** [comment]
+1

Love the green :)

**Comment by arshdkhn1** [comment]
same

**Comment by mmahalwy** [comment]
Looks like it's on staging. Closing.
