### ISSUE TITLE
Changing Surah while playing is throwing error/plus continue playing current surah

### ISSUE THREAD

**Issue by naveed-ahmad** [quran/quran.com-frontend#525]
* Click on play  
* When player start playing ayah, click on next surah

## Expected 
* Player should stop
* Next surah should load and display

## Current behaviour 
* Player continue to play the current surah
* When finished playing loaded ayah through js error: 
```javascript
main-4eb8720….js:99 Uncaught TypeError: Cannot read property 'src' of undefined
```

**Comment by Ilyes-Hammadi** [comment]
Getting the same problem in the web player !!

**Comment by abdulapopoola** [comment]
I can start with this inshaaha Allaah. @mmahalwy, any tips on where to start?

**Comment by sabeurthabti** [comment]
@abdulapopoola i'd start by running the application locally and trying to reproduce the the bug. If you have the chrome developer tools, you should see an error - try to follow the error.

**Comment by mmahalwy** [comment]
Ah, yes, I kind of know what the problem is here. 

The audio player is getting a new chapter id but the verses call hasnt resolved yet, crawling the audio player to an error. Rather, that audioplayer should wait until a pending verses call is resolved. 

@abdulapopoola ^^

**Comment by Maputo** [comment]
@abdulapopoola @mmahalwy Any progress on this issue? I'd like to take a look at it if that's ok?

**Comment by mmahalwy** [comment]
@Maputo no progress as far as I know. Please go for it!

**Comment by mohhasbias** [comment]
Any update?
I would like to contribute.
I think this issue is a good first issue for me.

thank you.

**Comment by naveed-ahmad** [comment]
@mohhasbias feel free to take this :)

**Comment by atiqueansari1987** [comment]
Is this issue taken?
