### ISSUE TITLE
English Tafsir by Sayyid Abul Ala Maududi

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#528]
Has anyone used this tafsir or have knowledge of it?

http://www.tafheem.net/tafheem.html

**Comment by ATouhou** [comment]
Following

**Comment by mmahalwy** [comment]
@ATouhou sorry?

**Comment by ATouhou** [comment]
I've heard the name pop-up a couple of times.
Meant to say I am following this "issue/thread" :-)

**Comment by mmahalwy** [comment]
Ah nice :)

**Comment by naveed-ahmad** [comment]
I've tasfir of Sayyid Abul Ala Maududi in English, urdu and Malayalam language. Going to add verse by verse tafsir in v3

**Comment by naveed-ahmad** [comment]
Added in v3
