### ISSUE TITLE
Copy Quran text and/or translation text

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#530]

**Comment by naveed-ahmad** [comment]
What's problem in copying translation text ? Select the text and ctrl + c 

+1 for pdf export though

**Comment by mmahalwy** [comment]
Not sure. But it's a feedback where people want to copy and paste the arabic + translation.

**Comment by sabeurthabti** [comment]
On hover copy? maybe use https://clipboardjs.com to handle the copy to clipboard?

**Comment by mmahalwy** [comment]
@sabeurthabti interesting! Probably should have use that over this `copy-to-clipboard` which we are currently using.

Do we think it's valuable to add a copy text for the translations? I once added it but thought it's counter intuitive since you can just copy that text.
