### ISSUE TITLE
Readme is missleading

### ISSUE THREAD

**Issue by hellowin** [quran/quran.com-frontend#531]
This part

```
Unless you have the backend API running locally, you will need to update the API_URL, in development.env file, from localhost to api.quran.com. Leave the port number same.

To start the app, run npm run dev which will run both the server and the client (webpack) to compile upon edits. Go to http://localhost:8001 in your browser, not 8000 (that is just the express server).
```

Is no longer relevant. Some updates are:

1. `development.env` is now `.env`
2. `from localhost to api.quran.com` is already `API_URL=http://staging.quran.com:3000`
3. `http://localhost:8001` become `http://localhost:8000` now

Before I create PR, is my points are true?

**Comment by mmahalwy** [comment]
You are certainly correct except the 8001. Not on my computer but pretty sure it's that and not 8000 which will not have hot reloading

**Comment by hellowin** [comment]
Hmmm wait, I got these:

![screen shot 2016-12-17 at 6 35 58 am](https://cloud.githubusercontent.com/assets/1904744/21281953/43f6eb96-c423-11e6-8cc6-b8651e5143e2.png)

![screen shot 2016-12-17 at 6 36 07 am](https://cloud.githubusercontent.com/assets/1904744/21281960/49c04b62-c423-11e6-9801-0b2ab46dc606.png)

I haven't change anything yet. And look at these config:

1. https://github.com/quran/quran.com-frontend/blob/master/.env#L2
2. https://github.com/quran/quran.com-frontend/blob/master/webpack/webpack-dev-server.js#L11
3. https://github.com/quran/quran.com-frontend/blob/master/package.json#L17

Number 1. is not used? number 2 will get port 8000 because it's hardcoded on `package.json` (number 3), is it as expected?

**Comment by mmahalwy** [comment]
+1 
thanks!

**Comment by ysahbi** [comment]
Can you please specify also that these steps does not work on Windows.

**Comment by mmahalwy** [comment]
sorry, what does not work?

**Comment by ysahbi** [comment]
I forked the project in both Ubuntu and Windows environnement and for both I ran `npm run dev` for Ubuntu it works, for windows i got this 
![image](https://cloud.githubusercontent.com/assets/6714981/21817463/64e64302-d764-11e6-8a31-99aa1fe746be.png)

**Comment by mmahalwy** [comment]
hmm i think the problem is with `env` and probably should be `export` I think for windows. Maybe we should use something else for env variables in command line. What to try moving those variables to `.env` and see if it works?

**Comment by sabeurthabti** [comment]
Maybe [cross-env]( https://www.npmjs.com/package/cross-env) can help?

**Comment by mmahalwy** [comment]
@sabeurthabti +!
