### ISSUE TITLE
Javascript broken on staging

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#532]

**Comment by mmahalwy** [comment]
Might be the culprit:
https://github.com/quran/quran.com-frontend/commit/75401e0f5a9f965e01592bb7fda6382231df42bd#diff-f10b3fc5acaea787dd0cefdca1919612R16

**Comment by naveed-ahmad** [comment]
Already fixed in https://github.com/quran/quran.com-frontend/pull/523/commits/8d776389d367439263fbf11b25adeabf3093dfee

**Comment by mmahalwy** [comment]
@naveed-ahmad its a huge PR that is now blocking staging. When do we expect to deploy it?

**Comment by naveed-ahmad** [comment]
Next few hours, working on specs.
