### ISSUE TITLE
Planning 2017

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#533]
Salams all,

Wanted to start a post on what we should try to accomplish this year. I am really excited on what we will accomplish together - we have already got so far with so many great people offering their time and talent to the project. To help steer these efforts, thought I'd make a list here that we can discuss and create issues/tasks accordingly. Here are a few things we'd like to do (they include features but overall vision).

1. **How do we get more contributors to the projects.** We are where we are today due to the amazing help by so many people. These individuals became core members of the team. We look forward to adding more.

2. **Improving mobile.** This is two-part. Firstly, we are now getting ~55% of our users on mobile. How do we improve the mobile web experience? Secondly, the web has many content features that we'd love to add to our mobile apps that offer offline content but don't have online yet.

3. **Search.** We haven't given it much attention recently and it's barely working. What can we do to improve search + add features to it?

4. **Offline.** One of our number one requests these days is downloading the content offline to read the Quran. We cannot offer audio downloads since they are ayah-by-ayah but we can offer to download the content.

5. **Research.** We get many requests for data for the purpose of academic research. We don't have a good way to help those individuals. Corpus.quran.com came from an academic project, and thus if we enable more people, we can potentially get other projects like it.

6. **Tafsir/Content.** We get requested tafsir often. How can we implement a good way to present tafsir? Where can we get more trustworthy content?

7. **Community.** With One.Quran.com in place, we will have user authentication. This means we can store data relevant and helpful to the user (bookmarks, notes, metrics on reading time, etc), but also start to incorporate some sort of a community where people can contribute thoughts, can ask questions, etc.

8. **Connected Quran.** This is an overstretch but what if you can ask your Echo or Google Home to play Quran for you? What if Quran content is more tightly bonded to Google results?

Okay, those are a lot of thoughts. What would be great is if we can discuss them then turn them into action items (issues) for us and other contributors to pick up and help out with. I don't know if we can do all of these in 2017 but let's put the right intentions and try to raise the bar as high as we can.

**Comment by sabeurthabti** [comment]
**1.How do we get more contributors to the projects**
I remember I somehow landed on your twitter, and then your Medium posts which lead me to Github. 
We can do more "community outreach" via twitter and Medium. We can discuss things around releases/features, @ahmedre can tell us about his Docker/Jenkins pipeline, Analytics, tech tips and more. Can we get Slack on the readme it can be a way to ease people in. 

**4.Offline.**
We have HTTPS, can we look into adding Service Workers? This should give us some excellent results (minus Safari support). 

**8. Connected Quran.** 
Excellent ideas, and within a similar field we can do FB Messenger Bots. Messenger bots can be used to send out daily Ayah, some quran reminders and so on.  Another thing around social, we can do is sharable Ayah pages (full page experience, and ayah play), with translation and *maybe* comments/likes.

**Comment by mmahalwy** [comment]
@sabeurthabti thanks for the awesome feedback! Regarding number 1, yes I agree. People do randomly stumble upon and ping me on Twitter. How can we get more people to find us and know that 1. we exist, 2. we welcome and would love their help. Thoughts?

**Comment by wahono77** [comment]
I think we need Arabic keyboard for user that using latin keyboard. It's needed to search Arabic content of Quran. We can use library http://www.greywyvern.com/code/javascript/keyboard

Thanks

**Comment by sabeurthabti** [comment]
@mmahalwy lets have an action to start a quran.com Medium Blog/Journal, we can use that announce releases.

**Comment by naveed-ahmad** [comment]
Or create release category in our [discourse instance](http://discuss.quran.com) and announce releases there. [Discourse meta](https://meta.discourse.org/c/releases) is great example for that.

**Comment by reshadn** [comment]
as-Salamu 'Alaykum,
Not having made much of a contribution I appreciate the chance to add some thoughts here. 

- How do we get more contributors to the projects. 
  - I see this as a 2 part challenge, how do we widen the funnel but also how do we engage interested individuals. I think it might help to create teams to focus on various aspects of the site (eg. design, backend, search, translation, tafseer, marketing, etc). With team leads actively guiding interested individuals through their specific project.
- Improving mobile.
  - Can we leverage react-native for mobile apps, desktop apps?
- Search
  - The potential here is amazing. Voice search, context search, multi-language search, general concept search, etc.
- Offline
  - Just curious why we can't offer audio downloads? I know the Quran android app offers downloads by ayah, page, surah or entire juz. Is there a technical or logistical reason we can't? In a general sense are we considering iOS, Android apps for "offline" use vs mobile web app?
- Research. 
  - I'd love to see research.quran.com for academics with a whole suite of tools.
- Tafsir/Content
  - I'd really like to see the an integration with "The Study Quran, A new translation and commentary" by Seyyed Hossein Nasr and group. Seems like a solid academic resource that is also friendly to a modern audience.
- Community. One.Quran.com
  - Personalizing the quran is going to be such a great experience. Excited to hear more ideas about how people would like to use quran.com in their daily lives. I think we can aim to pass the "tooth-brush" test here. 
- Connected Quran
  - The number of possible devices and mediums for connection are growing by the day. We should absolutely integrate quran.com in to all of these spaces. home devices, tv, watch, VR headset, airpods.

- AI/ Quran Assistant
  - I'd like to add the possibility of leveraging AI/ML in creative ways. I don't have much experience here so I don't really know what's possible yet. I am however interested in learning more. The idea of a personalized Quran study guide, trainer, reminder would be nice.

Additionally, I'm curious to know what other data is available from current usage to drive priorities here. Also I'd like to suggest a survey on the site itself to get feedback from our users on what they want to see and priorities. 

I pray that God blesses this effort and counts it on our scale of good deeds.

**Comment by ATouhou** [comment]
@reshadn wa aleykoum salam. 
Hossein Nasr is a sufi inspiried shii3i, so don't expect his content coming up on the site :-)

Besides that I really like your inputs.

Some search ressources: 
Alfanous (https://github.com/assem-ch/alfanous) have a really powerfull search engine (http://www.alfanous.org/) .
For the voice searching, I saw some apps that converts audio -> arabic text (Google API) -> search quran. 

Personalized assistant would be genius with settings and preferences set to a user (also linked to community) and tracks progress etc.  across all platforms. 



Making teams according to interests also sounds great

**Comment by reshadn** [comment]
WSalam. I don't know about his personal beliefs or views but the book is an
academic resource highly regarded by a number of mainstream scholars. It's
actually references from the traditional tafseer sources. I wouldn't
discount it so quickly but am open to discuss it further iA.

**Comment by yasserhussain1110** [comment]
How about a gitter or slack channel where we can discuss stuff and maybe invite other potential contributors??

**Comment by mmahalwy** [comment]
@yasserhussain1110 we do have a slack account and usually add people are contributing. But I think we can open it up for anyone?

**Comment by yasserhussain1110** [comment]
> But I think we can open it up for anyone.

That would be great, I think.

**Comment by mmahalwy** [comment]
+1. How can we make it easy for anyone to join?

**Comment by yasserhussain1110** [comment]
How about posting the link on the README page?

**Comment by mmahalwy** [comment]
Yes, but how do people request invite to slack

**Comment by yasserhussain1110** [comment]
I have joined the slack channel. :+1:
