### ISSUE TITLE
Communicating releases and features to users

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#534]
Thoughts about a good scalable way to communicate features and changes? 

My best idea so far is have a button in the nav. Click to open a modal that would iframe an article in Zendesk / and/or link to Zendesk article.

**Comment by sabeurthabti** [comment]
Hmm, maybe one of those growth hack modal boxes? We can trigger them on each release and maybe we can start doing chimp mail (might be too much and not the type of website). 

Also can we make use of github release tagging? (https://github.com/quran/audio.quran.com/releases)

**Comment by mmahalwy** [comment]
Yes. Anyone know of some package to help communicate releases from GH? 

For example, it saves a cookie to a user and opens a modal based on the github release. Doesn't show the modal again until another release then it opens a modal with details + saves a new cookie. 

Might be a good open-source project :)
