### ISSUE TITLE
View enhancement: Mobile view is not friendly enough 

### ISSUE THREAD

**Issue by murad073** [quran/quran.com-frontend#539]
While trying to get the surah info link, I was unable to see the link in mobile view. Top menu links does not work as well. Bottom help button also overlapped on player controls. 
Please have a look at the screenshot to understand better - 
http://prntscr.com/dlvhp3

**Comment by mmahalwy** [comment]
Yeah we have to find a way for mobile and the help button. I am thinking inside the drawer. Thoughts?
