### ISSUE TITLE
Unable to play only one ayah

### ISSUE THREAD

**Issue by Alishankhan** [quran/quran.com-frontend#540]
It seem their is bug while playing only one ayah as it keep continuing to play succeeding ayah when toggle repeat is enable  for one ayah in the surah

**Comment by mmahalwy** [comment]
on staging or production?

**Comment by Alishankhan** [comment]
Production.
Problem  Step
1) play any ayah (in my case first)
2) enable toggle to repeat
3) select single 
4) now play ayah (in my case first)
works fine
5) Now play second ayah it start playing second, third, till end of surah

**Comment by mmahalwy** [comment]
Yeah, we are getting a weird 412 on audio files... investigating.

**Comment by mmahalwy** [comment]
CC @ahmedre
