### ISSUE TITLE
local specific meta tags

### ISSUE THREAD

**Issue by naveed-ahmad** [quran/quran.com-frontend#544]
https://github.com/quran/quran.com-frontend/pull/523 will add localization now its time to update meta tags. 

* dynamically set `og:locale` value according to current local
* Add tags alternate tags for available locals
```html 
<link rel='alternate' href="https://quran.com/...?local=?local" hreflang="LOCAL"> 
``` 
* make sure canonical meta is without local param

**Comment by mmahalwy** [comment]
My vote for ` quran.com?language=LANGUAGE`
