### ISSUE TITLE
Adding Tajik language translation

### ISSUE THREAD

**Issue by MegaApp** [quran/quran.com-frontend#545]
Assalamu aleykum. My name Izzat I am from Tajikistan and I want to add tajik language in this app. how can I help for you ?

**Comment by naveed-ahmad** [comment]
@MegaApp can you attach translation file here?

**Comment by MegaApp** [comment]
I found here  http://islam-book.info/tadzhikskom/koran/koran-na-tadzhikskom-yazike

[koran_na_tadzhikskom_yazyke.zip](https://github.com/quran/quran.com-frontend/files/672917/koran_na_tadzhikskom_yazyke.zip)

**Comment by mmahalwy** [comment]
@naveed-ahmad you'll add it to db?

**Comment by mmahalwy** [comment]
@MegaApp can you create this issue here? github.com/quran/quran.com-api

**Comment by naveed-ahmad** [comment]
@mmahalwy found same translation on [tanzil.net](http://tanzil.net/#trans/tg.ayati/1:1) will add this and other missing translation after completing v3, two more weeks.

**Comment by mmahalwy** [comment]
okay perfecto. Thanks!
