### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by Alishankhan** [quran/quran.com-frontend#546]
typo in is surah fatiha
should be "Al" not "ul" 
https://quran.com/1:2
same for 1:3 and rest of surah too ...
![capture](https://cloud.githubusercontent.com/assets/1307689/21505353/8c96ef92-cc8c-11e6-931e-9f78acf98c08.PNG)

**Comment by ahmedre** [comment]
this isn't a damma - it does say "al," not "ul," so it is correct.

let me explain:

historically, there are 2 very popular scripts (you can think of these as "fonts") that the Quran is written in - the Madani script, and the Naskh script. the Madani script comes out of Madinah, and is mostly prevalent in the Arab speaking world. the Naskh script is mostly used in southeast Asia (India, Pakistan, etc). both are correct (and say the exact same thing), but just have slightly different ways of writing the tashkeel ("zabar, zer, and pesh") compared to the madani script.

both of these are correct, and if you were to walk into Masjid al Haram (the Ka'bah in Makkah) or Masjid al Nabawi (in Madinah), you'd find many copies of both scripts on the shelves there.

here's [sura fatiha in Naskh](http://android.quran.com/data/naskh/width_1280/page002.png), and here is [sura fatiha in Madani script](http://android.quran.com/data/width_1280/page001.png).

we use the older Madani script on quran.com - i think i recall someone opening a feature request for supporting Naskh in the future, which we will consider insha'Allah.

**Comment by Alishankhan** [comment]
ok XD
