### ISSUE TITLE
Resuming Previous Ayah

### ISSUE THREAD

**Issue by umairidris** [quran/quran.com-frontend#547]
Salam,

Thank you for the wonderful site. I am trying to set this up for my mother to use. I am unable to find a setting that resumes where the previous session was left off. I see that there is a hyperlink beside each verse which changes to URL to point to this specific verse, but it is not saved. 

Am I missing a setting that I need to enable? Ideally my mother should be able to go to quran.com and there should be a resume button (if she was on the site previously). 

If this feature is not supported I could try adding it by storing this information in a cookie and if the value is found then there could be a resume button when going on the main page.

**Comment by mmahalwy** [comment]
Salam @umairidris thanks for pinging us about this! 

We used to have a previously visited ayah link on the home page that we removed when we did a rewrite. It used to save reference to the first ayah of the last API call made, so if I go to Surah 2, and i kept scrolling till the API for ayahs 100-120 are called, it'd save 2:100 to the cookies. Maybe that could help? Looking forward to your PR!

**Comment by umairidris** [comment]
Thank you, I will try to work on this when I get a chance inshAllah.

I am going to move the surah settings issue to a new issue as it is not directly related storing previous state.

**Comment by mmahalwy** [comment]
Perfect, that you!
