### ISSUE TITLE
Side menu doesn't work on staging

### ISSUE THREAD

**Issue by ahmedre** [quran/quran.com-frontend#551]
none of these items are clickable on Chrome on OS X.

<img width="250" alt="screen shot 2017-01-02 at 8 30 39 pm" src="https://cloud.githubusercontent.com/assets/47771/21599988/6019594e-d12a-11e6-8796-8aa8c9b7c4b4.png">

**Comment by mmahalwy** [comment]
Yeah something is up on staging 

Going to fix it

**Comment by mmahalwy** [comment]
fixed!
