### ISSUE TITLE
Flags to customize url

### ISSUE THREAD

**Issue by ahmedre** [quran/quran.com-frontend#552]
low priority feature request - i have an option to share Quran links - right now, i share these to quranapp.com, which is great, but it may make more sense in the future to share them to quran.com instead. so if i want a flag so i can do something like quran.com/2/25-27&only=true (or something) so that i get a page showing just ayahs 25-27 (and then maybe a button to remove the `only=true` flag and go back to the normal behavior of infinite scrolling in either direction).

secondarily to this, would be nice to have an explicit `&translations=` option of sorts to be able to set a sharing url with a specific translation showing.

again, super low priority on both of these but would be nice to have them in the future.

**Comment by mmahalwy** [comment]
really good features! I agree. I think translation and reciter params should be added.

**Comment by mmahalwy** [comment]
Hmm, why do I feel like I already did this...

**Comment by mmahalwy** [comment]
I did, but didnt do anything yet.

**Comment by naveed-ahmad** [comment]
- https://quran.com/1?translations=21
- https://quran.com/1/1?translations=21
