### ISSUE TITLE
class styles.title adds random vertical lines around numbers

### ISSUE THREAD

**Issue by umairidris** [quran/quran.com-frontend#555]
Example:
![vertical line](https://cloud.githubusercontent.com/assets/5559279/21748481/05298a9e-d53b-11e6-9e90-fce7788c3305.png)

Code used to generate this:
```
  return (
    <div className="">
      <h4 className={`text-muted ${styles.title}`}>
      Foo {1} 2 {3} Bar
      </h4>
    </div>
  )
```

The culprit:
```
&:after {
  content: '|';
}
```
in containers/Home/styles.css

Is there a reason for this? Removing it seems to be fine. If there is no reason to have it I can send a PR to remove it.

**Comment by naveed-ahmad** [comment]
@umairidris `|` is separating pages of search result. If you've a better idea to separate page please open the PR :)
