### ISSUE TITLE
Scrollbars move and expand/contract randomly when moving mouse on staging

### ISSUE THREAD

**Issue by umairidris** [quran/quran.com-frontend#557]
To reproduce:
- go to staging.quran.com/2
- move mouse around randomly
- observe scrollbars moving erratically

I reproduced this problem on Chrome (Windows 10, KDE Neon 5.8.5)

Only seems to happen on surahs that don't fit on one page (i.e. on Al Fatihah I don't see this problem).

**Comment by sabeurthabti** [comment]
@umairidris Thank you for raising this issue.

**Comment by mmahalwy** [comment]
yes, I noticed this too and I think this is the culprit for this bug: https://github.com/quran/quran.com-frontend/pull/553

**Comment by mmahalwy** [comment]
@umairidris it's to do with lazy loading, thus Surah 1 and any of the smaller surahs smaller than 20 verses won't have this problem.
