### ISSUE TITLE
Part of ayah #2 gets skipped

### ISSUE THREAD

**Issue by umairidris** [quran/quran.com-frontend#566]
To reproduce:
- Go to any surah (I checked with surah 1 and 2)
- Press play beside the first ayah
- Wait for the first ayah to finish
- Observe that part of the second ayah gets skipped

I reproduced this on both current release and staging (Chrome on Windows 10 and Ubuntu 16.04)

This does not happen if the main player play button is used, only if ayah 1 play button is used.

**Comment by murad073** [comment]
I also get the same problem with surah 98, https://quran.com/98 

After finishing the first ayat, it jumped to the third ayat, skipping the second ayat. 

![image](https://cloud.githubusercontent.com/assets/1317890/23093183/15e35948-f5aa-11e6-8f0a-a3c600b2702a.png)
