### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by umairidris** [quran/quran.com-frontend#568]
Observations on staging:
-  Settings are inconsistent and dispersed across multiple parts of the app which may make it difficult for users to find them
   - Language settings are in footer
   - In Surah page there is a sidebar with some settings (reciter, search, etc)
   - Some settings are in the player at the bottom (loop, etc)
   - Some settings are near the top (reading mode, etc)
- There are navigation links on top of homepage and also in the footer and they do not match
- There is a "quick links" section on homepage which is somewhat duplicated in footer "other links" section and do not match
- Sitemap link which I am not sure if it's working as intended
- There is no way to get back to home from a surah easily (#560)
- Mobile UI issues (#539)
  - Help button floating on bottom right
- On surah page the playback controls are a small popup over the page on the bottom left corner of the screen

Recommendations:
- Follow Material design
- Mimic Play Music (a site implementing Material Design with similar functionality for ours)

Reasons:
- Material Design supports both desktop and mobile UIs
- Material Design is used by Google and majority of Android apps so majority of users will have exposure and understanding of it
- Many examples to use
- Will allow for greater synchronization/sharing between UIs of web app and Android app
- Well specced out and tested with good documentation (https://material.io)

Links:
- https://material.io/guidelines/
- http://www.material-ui.com/

Samples:
App bar:
![image](https://cloud.githubusercontent.com/assets/5559279/21802447/a5a831b4-d6da-11e6-8474-02de4b777ffd.png)

Nav drawer:
![image](https://cloud.githubusercontent.com/assets/5559279/21802467/b7cbaaba-d6da-11e6-9fbb-e2846a336c0c.png)

Bottom bar with album/playlist view (Surah list can go here):
![image](https://cloud.githubusercontent.com/assets/5559279/21819444/8f2e79b6-d720-11e6-8119-6a5fc6ba3011.png)

**Comment by mmahalwy** [comment]
@umairidris these are awesome! I pinged one of the designers helping us out about this. I'd love to break these down into issues to tackle them one by one. 

Also, what's your email address so I can add you to slack?

**Comment by umairidris** [comment]
Can use my personal email umairidris93@gmail.com

**Comment by umairidris** [comment]
Possibly useful: http://www.material-ui.com, https://github.com/callemall/material-ui

**Comment by mmahalwy** [comment]
@umairidris can we create this to be a check list so we can work down the list?

**Comment by umairidris** [comment]
Done! I am not sure if you can modify my post but if you want me to change/add/remove anything feel free to post it here and I will.

**Comment by mmahalwy** [comment]
Yep, I certainly can!

**Comment by umairidris** [comment]
Might be useful to have one issue per major change (i.e. one for adding an app bar, one for settings, etc...)

**Comment by mmahalwy** [comment]
Yes. We'd need to break it down

**Comment by umairidris** [comment]
Done

**Comment by mmahalwy** [comment]
Closing. Only missing is #581
