### ISSUE TITLE
Organize languages in dropdown by alphabet order

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#57]

**Comment by haritsE** [comment]
Hey guys, is this issue still available? Can I try it? By languages, did you mean this one? ![alt text](http://imgur.com/VnLaVRr.png "organize languages")

**Comment by mmahalwy** [comment]
@haritsE yes, still a bug! Please do take it on. I'd suggest opening a PR early so it's marked on this issue as in progress.

**Comment by sabeurthabti** [comment]
Example of sorting alphabetically on objects within an array:

`export function alphabetically(property) {

  return (a, b) => {
    const textA = a[property].toUpperCase();
    const textB = b[property].toUpperCase();

    if (textA < textB) {
      return -1;
    }

    if (textA > textB) {
      return 1;
    }

    return 0;
  };
}`

usage:

`[{name: "English"}, {name: "Arabic"}].sort(alphabetically('name')`

**Comment by haritsE** [comment]
Awesome, I'll try to have a PR ready by this weekend 👍

**Comment by kriwil** [comment]
I guess this issue is fixed?

**Comment by sabeurthabti** [comment]
@kriwil yep
