### ISSUE TITLE
Add global nav drawer

### ISSUE THREAD

**Issue by umairidris** [quran/quran.com-frontend#579]
- [x] Add global nav drawer
- [x] Move navigation links from top of homepage and bottom footer into nav drawer
- [ ] Move help button into separate page and link it from nav drawer

Quick mockup in trusty MS paint (stolen off Play Music nav drawer):
![image](https://cloud.githubusercontent.com/assets/5559279/21880532/5ce51c82-d854-11e6-8845-ab05fa4853a6.png)

**Comment by mmahalwy** [comment]
Okay, some links cannot be removed due to SEO and Google. For example, we have links to surahs due to search behavior.
