### ISSUE TITLE
[Suggestion] Better UX with "sura info"

### ISSUE THREAD

**Issue by ATouhou** [quran/quran.com-frontend#58]
When clicking the "info" button. Open the info box, in an overlay that  can be easily closed again.  Problem in the user interface occours when having scrolled down in a surah, clicking the button, then suddenly the entire page just goes 2≈ aya (according to what resolution you got),  and I have to scroll "all the way" up to read it.   
Would be better if it just appeared, and could easily be hidden when needed

**Comment by mmahalwy** [comment]
do you have a screenshot?

**Comment by ATouhou** [comment]
1. having scrooled down in a surah. 
https://www.dropbox.com/s/2jgrv2rsdyc54w1/Sk%C3%A6rmbillede%202015-07-31%2022.19.27.png?dl=0
2. Clicking the info button
https://www.dropbox.com/s/ec1h8d77megmh2o/Sk%C3%A6rmbillede%202015-07-31%2022.19.31.png?dl=0
3. Scrooling back up
https://www.dropbox.com/s/i10klpxhz67mqsp/Sk%C3%A6rmbillede%202015-07-31%2022.19.40.png?dl=0

**Comment by ATouhou** [comment]
So basically what i mean is that it comes in an overlay something like this : 
https://www.dropbox.com/s/9tjh36glujfu2tk/Sk%C3%A6rmbillede%202015-07-31%2022.24.01.png?dl=0  
Ofcourse added some "X" in the right top corner to help the user that forgot how to "enable/disable it"   , also maybe darken the background alittle

**Comment by mmahalwy** [comment]
Salam @ATouhou I appreciate the suggestion. An overlay may be confusing as you can simply continue scrolling and not see it anymore.

**Comment by ATouhou** [comment]
Not if it's centered at all times in the screen or position fixed
Den 03/08/2015 5.38 AM skrev "Mohamed El Mahallawy" <
notifications@github.com>:
