### ISSUE TITLE
Cleanup settings

### ISSUE THREAD

**Issue by umairidris** [quran/quran.com-frontend#580]
- [x] Add settings page and link to nav drawer (or put it under the "three dot" dropdown in app bar)
- [x] Move language settings from footer to settings
- [x] Move reciters, translations, tooltip setting
- [x] Remove search from nav drawer

Sample: http://i.imgur.com/JroM2lH.png

**Comment by mmahalwy** [comment]
+1

**Comment by umairidris** [comment]
My next couple of weeks are bit busy but I am going to start contributing to the UI efforts by working on the settings page.

**Comment by mmahalwy** [comment]
@umairidris might beat you to it since all this is blocking deploying. Since we are unhappy with the drawar.

**Comment by umairidris** [comment]
You can see some of the groundwork I was doing here: https://github.com/umairidris/quran.com-frontend/tree/settingspage

May help! I will let you continue from here

**Comment by mmahalwy** [comment]
Keeping font size out of settings modal. Might make sense to have it more accessible?
