### ISSUE TITLE
Cleanup surah page

### ISSUE THREAD

**Issue by umairidris** [quran/quran.com-frontend#581]
- [ ] Expand the playback controls on surah page to take up the whole bottom of the screen (new bottom bar)
- [ ] Add volume control to bottom bar 
- [x] Dynamically add surah info, reading mode & ayah select icons to app bar
- [x] Switch main title to surah name in app bar
- [x] On surah page, the surah title in app bar should have a drop down which will let users quickly select another surah

**Comment by mmahalwy** [comment]
Some of the changes are here: https://github.com/quran/quran.com-frontend/pull/583
