### ISSUE TITLE
Add an easier way to get back home

### ISSUE THREAD

**Issue by ahmedre** [quran/quran.com-frontend#591]
<img width="761" alt="screen shot 2017-01-18 at 2 10 58 pm" src="https://cloud.githubusercontent.com/assets/47771/22085231/f5e708cc-dd87-11e6-9ee4-3c13340b773a.png">

when the menu is open, there's no easy way to go home (without closing the panel and clicking the house). an easy fix is to make the "Quran" row clickable.

**Comment by omerblink** [comment]
@mmahalwy @ahmedre I have made this change and its linking back to home... 

<img width="727" alt="screen shot 2017-02-01 at 8 10 12 pm" src="https://cloud.githubusercontent.com/assets/773535/22512335/7dd61312-e8ba-11e6-8a52-dd72c46f7e05.png">

Am I doing it right? 

`<Link to="/"><i className="ss-icon ss-home back-to-home" /><LocaleFormattedMessage id="nav.title" defaultMessage="Quran" /></Link>`

**Comment by mmahalwy** [comment]
Yep! That'd do it!

**Comment by omerblink** [comment]
Once question though... I'm adding css in this file but its not affecting... 

`/Quran.com/quran.com-frontend/src/components/GlobalSidebar/style.scss`

Do I have to run the sass compiler? Shouldn't it compile itself?
