### ISSUE TITLE
Improve time to first paint

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#594]
New
![image](https://cloud.githubusercontent.com/assets/3749095/22098682/8d52ceb8-dddc-11e6-84cf-8cd691d56674.png)

Old
![image](https://cloud.githubusercontent.com/assets/3749095/22098694/94d2b9dc-dddc-11e6-900f-ea1d7d635d09.png)

**Comment by mmahalwy** [comment]
![image](https://cloud.githubusercontent.com/assets/3749095/22098714/b3041ffe-dddc-11e6-8ad0-7a672e794aee.png)

**Comment by ahmedre** [comment]
@naveed-ahmad's change for v3 api will help with this because it'll remove all the sura info into an api call.

**Comment by mmahalwy** [comment]
@ahmedre its already in API

**Comment by naveed-ahmad** [comment]
fontawesome and intl polyfill should load asynchronously, thired:  https://github.com/quran/quran.com-frontend/pull/599  and we've some performance improvment.  We might get more improvement on staging ( not sure why http/2 isn't working with temp pr builds )

**Comment by ahmedre** [comment]
http/2 depends on https working, which is currently not there for the PR containers, but there for staging and prod.
