### ISSUE TITLE
iOS audio playback gets stuck on even-numbered ayat

### ISSUE THREAD

**Issue by cpfair** [quran/quran.com-frontend#596]
If you open any surah on iOS and press the main play button, only the first ayah plays, after which the player gets stuck (play/pause button toggles, scrubbing bar responds, but no playback). If you skip to the next ayah (3) then back to the previous (2), everything works as expected: the 2nd then 3rd verses play... then the player again gets stuck on the 4th. This process must be repeated for subsequent even-numbered ayat. If you use the player's skip buttons to skip to the 2nd ayah before first starting playback, then the opposite occurs - even-numbered ayat play as expected while odd-numbered fail. The discrete ayah play buttons are intermittently functional throughout this ordeal.

iOS 10.2 in MobileSafari. No errors in console, requests to preload audio seem to complete without issue (various 200s, 206s, 304s).

**Comment by mmahalwy** [comment]
Will take a look at this!

**Comment by mmahalwy** [comment]
Adding @sabeurthabti too since he has lots of experience with the audioplayer

**Comment by navedcoded** [comment]
Confirming that this is still a problem from iOS Safari

**Comment by sabeurthabti** [comment]
I will also take a look at this tonight iA

**Comment by sabeurthabti** [comment]
I tried to investigate, I was able to replicate it but couldn't find a fix. Let's make this a priority. I will add it the project board.

**Comment by navedcoded** [comment]
Let me know if I can help with any testing; I can't code but I can at least do that inshaAllah!

**Comment by sabeurthabti** [comment]
That would be awesome, I actually was thinking we need some testers for our projects. Please feel free to do some exploratory testing. We are on slack, come join us.

**Comment by navedcoded** [comment]
I would love to! Like I said I can't code, but I am technically savvy and I
have a variety of devices lying around home to test with.

I've got iPads, an iPhone, two Android phones, a Linux computer and also a
Chromebook; send anything that needs testing my way!

And I think I need to be invited to the slack team right?

**Comment by sabeurthabti** [comment]
@navedcoded https://quranslack.herokuapp.com
