### ISSUE TITLE
Update URL when player switch the ayah

### ISSUE THREAD

**Issue by naveed-ahmad** [quran/quran.com-frontend#605]
If user is listening say [2:25](https://quran.com/2/25) when player switch to 2:26 the URL should also be updated to  .../2/26

#### This feature will be helpful when 
* You started from a verse and after few verse something went wrong. User simply try to refresh the page and boom you'll start from where you first started listening. I faced this issue couple of time 
* You are listing current verse and want to share, copy the URL!

**Comment by mmahalwy** [comment]
I don't understand :(

**Comment by naveed-ahmad** [comment]
Sorry this was a placeholder task for me to so later. Updated readme

**Comment by mmahalwy** [comment]
ah, this is tricky btw. you got to be careful cause we rely so heavily on url changes that you dont want 1. to refetch data, 2. rerender components when you update the url

**Comment by naveed-ahmad** [comment]
Well I was hopping we can update URL using pushstate API without
changing/updating/reloading page. Not sure if it's possible with react.

**Comment by mmahalwy** [comment]
I think all url updates are pushstate which the react-router subscribes to.
