### ISSUE TITLE
web progressive app, service workers , why not?

### ISSUE THREAD

**Issue by ATouhou** [quran/quran.com-frontend#608]
Assalamu aleykoum.
Have you considered making a web progressive app with service workers? 
Since it's revolving around an API, it seems like a no-brainer to initiate that, as soon as there is ressources for it and sync it with the web frontend? 
And service workers and  storing page images after first loading them unless hash is differentiating seems like the way to go? 
What do you guys think?

**Comment by naveed-ahmad** [comment]
@ATouhou +1 for PR :)

**Comment by mmahalwy** [comment]
+1

**Comment by mmahalwy** [comment]
I think it'd be great to store surahs since that's the homepage. Let's wait till v3 api

**Comment by ATouhou** [comment]
The app itself would not have to be updated so often, if the statics already comes shipped, but checks on server if, the server has a newer version or not. 
Also we would have an app, that have all the ressources collected at one place

**Comment by mahmoudfelfel** [comment]
Any updates here, is there anyone working on this?
I can start working on it, it is straight forward with this webpack plugin https://github.com/goldhand/sw-precache-webpack-plugin
By default, it uses a [`cache-first` strategy](https://jakearchibald.com/2014/offline-cookbook/#cache-falling-back-to-network) where it will cache all the assets so the second load will be almost instant, and whenever we have a new update it will download the new assets in the background and use them for the next visit of the website.
We can start with caching the assets for a better load time, then later start caching even the actual data with a `network-first` caching, so it will try to hit the network first but if the user is offline, it will fallback to the cached data.

**Comment by ATouhou** [comment]
It should just use the cacheFirst, then meanwhile get the real feed from the API. If the data is not the same (maybe version number or checksum) then there could be a little prompt saying "Site has updated, do you want to reload? " then reload the page (with js) dynamically

**Comment by mahmoudfelfel** [comment]
@ATouhou the `sw-precache` webpack plugin handles the versioning of the sw file. 
And let's make it on steps as you're saying, first cache the assets to make the second visit quicker, then store the data itself from the API to have a full offline version.
Will start working on it, and open a PR soon Insha'a Allah.

**Comment by mmahalwy** [comment]
@mahmoudfelfel please take it! Would love your help and I don't have much knowledge in this.

**Comment by agungsb** [comment]
I see that the service worker has been registered to the application, but it's not working properly. Is this issue still opened? If yes, I would love to help by opening a PR soon. In syaa' Allah.. 😄
