### ISSUE TITLE
When copying an Ayah, include Ayah number (and maybe the surah number)

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#609]

**Comment by omerblink** [comment]
@mmahalwy I want to work on this feature... But when I run `npm run dev` I don't see any surahs...

**Comment by mmahalwy** [comment]
@omerblink yes. Staging has new API, and frontend isn't up to date with it. Let me fix that now

**Comment by omerblink** [comment]
Let me know once it fixed :)
