### ISSUE TITLE
Share icons are not intuitive on the surah page

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#611]
'What are these? What do they do?'

Also, people tend not to share a surah but share a verse. 

I think we should change to only display one ayah instead of starting from that ayah when you go to that ayah via url. Have a button to view more.

**Comment by mmahalwy** [comment]
Medium.com kind of sharing?

**Comment by sabeurthabti** [comment]
I had this idea where we build ayah specific page, with all the great features of quran.com. Maybe discussion, however I can see that getting out of hand, maybe moderated/registered users.

**Comment by mmahalwy** [comment]
@sabeurthabti sounds interesting, do tell more!
