### ISSUE TITLE
2 minor bugs

### ISSUE THREAD

**Issue by ahmedre** [quran/quran.com-frontend#619]
<img width="1143" alt="screen shot 2017-01-24 at 12 29 24 am" src="https://cloud.githubusercontent.com/assets/47771/22240538/81be6222-e1d0-11e6-8479-5b4da25b182f.png">

no ideas on how to fix these -
1. shafee3in illa are too close together - probably because shafee3in in the mus7af is at the end of a line and illa is at the start of the next line, and here they're right next to each other with 0 padding (and the font itself has no intrinsic padding for said characters).
2. the pause mark is on a separate line, which makes no sense. i know this depends on the width, but we should prohibit certain characters from leaving their words (the various stopping indicators).

**Comment by omerblink** [comment]
Shafee3in has a separate ID... If these IDs are unique it can be fixed though CSS with the following simple code: 

```
b#word-10-3-18 {
    margin: 0 0 0 9px;
}
```

http://prntscr.com/e2tp46

If you think its a right way then I can make another pull request :)

**Comment by mmahalwy** [comment]
@omerblink it's certainly a good hack! A better is to add that margin based off of the position of the world. Since all words have a position, if it's at the end of the line in the mushaf (as @ahmedre mentioned), then add margin.

**Comment by omerblink** [comment]
@mmahalwy Any suggestions or way already in the system to determine the position of the word?

**Comment by mmahalwy** [comment]
Let's wait till we implement api v3. That will have it
