### ISSUE TITLE
Bangla translation 5:92

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#62]
I have seen in the bangla translation in Sura maidah (5) verse 92 is 'তোমরা আল্লাহর অনুগত হও, রসূলের অনুগত হও এবং আত্মরক্ষা কর। কিন্তু যদি তোমরা বিমুখ হও, তবে জেনে রাখ, আমার রসূলের দায়িত্ব প্রকাশ্য প্রচার বৈধ নয়।' which is totally opposite meaning, it should be "বৈ নয়" instead of "বৈধ নয়" please correct it. Such type of mistake is totally misguide the people.

**Comment by ATouhou** [comment]
Have you reported all this to tanzil.com?
Den 03/08/2015 5.36 AM skrev "Mohamed El Mahallawy" <
notifications@github.com>:
