### ISSUE TITLE
typo in Malay translation

### ISSUE THREAD

**Issue by EvilTwin01** [quran/quran.com-frontend#624]
https://quran.com/56

ayat 4 : (Ia berlaku) semasa bumi bergoncang dengan sebebar-benar goncangan.

it should be: (Ia berlaku) semasa bumi bergoncang dengan sebenar-benar goncangan.

**Comment by sabeurthabti** [comment]
Closing as we don't have a Malay translation. 
@EvilTwin01 If you would like to contribute Malay:

1. https://github.com/quran/quran.com-frontend/blob/master/CONTRIBUTING.md
2. add the Malay locale file: https://github.com/quran/quran.com-frontend/tree/master/src/locale
