### ISSUE TITLE
Homepage wording should be separated from 'the'

### ISSUE THREAD

**Issue by kjellouli** [quran/quran.com-frontend#625]
![image](https://cloud.githubusercontent.com/assets/6676571/22409306/d12a5634-e655-11e6-9c66-4b6dff562b9e.png)

**Comment by omerblink** [comment]
@kjellouli Can you tell me how you got into this issue? Just wanted to replicate it so I can see it and fix it.

**Comment by naveed-ahmad** [comment]
@omerblink this is 404 page, try any invalid Surah number

https://quran.com/115
https://quran.com/error/invalid-surah

**Comment by omerblink** [comment]
@naveed-ahmad ... Fixed the bug and create the pull request...

**Comment by mmahalwy** [comment]
Fixed by https://github.com/quran/quran.com-frontend/pull/628#pullrequestreview-19492093
