### ISSUE TITLE
Verse Bookmark

### ISSUE THREAD

**Issue by adipurnama141** [quran/quran.com-frontend#626]
It would be better if there is verse bookmark feature, so we can continue our last reading.
I hope, this feature will be accessible without the need of login...

I'm sorry if this feature is already implemented, if that is true, can you please show me how to do it.. 

Many thanks..

**Comment by m-adilshaikh** [comment]
Although not explicitly called a bookmark, similar feature is now available as it remembers which link you were on the last time. Links are currently not updated as the ayah audio progresses, but that update is currently #610 is in process.
