### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by adipurnama141** [quran/quran.com-frontend#627]
I'm trying to build this project.
I installed node v.6.9.4.

When i tried to npm install , there was a warning like this..

![capture](https://cloud.githubusercontent.com/assets/13418482/22474940/0cefe9f2-e810-11e6-99a4-c187a19254a6.PNG)

And , when i try to npm run dev , there was an error like this

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\USER\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.10.8
3 info using node@v6.9.4
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle quran@1.0.0~predev: quran@1.0.0
6 silly lifecycle quran@1.0.0~predev: no script for predev, continuing
7 info lifecycle quran@1.0.0~dev: quran@1.0.0
8 verbose lifecycle quran@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle quran@1.0.0~dev: PATH: C:\Users\USER\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Node\quran\quran.com-frontend\node_modules\.bin;C:\Program Files\Java\jdk1.7.0_80\bin;C:\Program Files\ImageMagick-6.9.2-Q16;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Haskell\bin;C:\Program Files\Haskell Platform\2014.2.0.0\lib\extralibs\bin;C:\Program Files\Haskell Platform\2014.2.0.0\bin;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\FPC\2.6.4\bin\i386-Win32;C:\Program Files\Windows Live\Shared;C:\Program Files\MATLAB\R2011a\runtime\win32;C:\Program Files\MATLAB\R2011a\bin;C:\Program Files\Haskell Platform\2014.2.0.0\mingw\bin;C:\Program Files\IVI Foundation\VISA\WinNT\Bin;C:\Program Files\Bitvise SSH Client;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\LLVM\bin;C:\Program Files\doxygen\bin;C:\Program Files\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\nodejs\;C:\Program Files\OpenVPN\bin;C:\Program Files\Mercurial;C:\Program Files\PostgreSQL\9.;C:\Program Files\Git\cmd;C:\Program Files\PostgreSQL\9.6\bin;C:\Python27\Scripts;C:\Python27;C:\Ruby193\bin; C:\Program Files\GnuWin32\bin; C:\unxutlis\bin\; C:\unxutlis\usr\local\wbin\ ; C:\Program Files\Java\jdk1.7.0_80\bin ; C:\tcc;  C:\Users\USER\AppData\Roaming\cabal\bin;C:\FPC\2.6.4\bin\i386-win32;C:\Users\USER\AppData\Roaming\npm;
10 verbose lifecycle quran@1.0.0~dev: CWD: C:\Node\quran\quran.com-frontend
11 silly lifecycle quran@1.0.0~dev: Args: [ '/d /s /c',
11 silly lifecycle   'env NODE_PATH=\'./src\' PORT=8000 UV_THREADPOOL_SIZE=100 node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --config ./webpack/dev.config.js & env NODE_PATH=\'./src\' PORT=8000 node ./bin/server.js' ]
12 silly lifecycle quran@1.0.0~dev: Returned: code: 1  signal: null
13 info lifecycle quran@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: quran@1.0.0 dev: `env NODE_PATH='./src' PORT=8000 UV_THREADPOOL_SIZE=100 node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --config ./webpack/dev.config.js & env NODE_PATH='./src' PORT=8000 node ./bin/server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid quran@1.0.0
16 verbose cwd C:\Node\quran\quran.com-frontend
17 error Windows_NT 6.1.7600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\USER\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v6.9.4
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error quran@1.0.0 dev: `env NODE_PATH='./src' PORT=8000 UV_THREADPOOL_SIZE=100 node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --config ./webpack/dev.config.js & env NODE_PATH='./src' PORT=8000 node ./bin/server.js`
22 error Exit status 1
23 error Failed at the quran@1.0.0 dev script 'env NODE_PATH='./src' PORT=8000 UV_THREADPOOL_SIZE=100 node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --config ./webpack/dev.config.js & env NODE_PATH='./src' PORT=8000 node ./bin/server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the quran package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     env NODE_PATH='./src' PORT=8000 UV_THREADPOOL_SIZE=100 node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --config ./webpack/dev.config.js & env NODE_PATH='./src' PORT=8000 node ./bin/server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs quran
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls quran
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

Can you help me please?
Many thanks...

**Comment by sabeurthabti** [comment]
hmm, remove node_module folder and try again. If that doesn't work can you confirm the version of NPM you're on?

**Comment by umairidris** [comment]
#531 mentioned issues getting the app running on Windows. Might be related.
