### ISSUE TITLE
When increase Translation font size, watch lecture link font size increases as well

### ISSUE THREAD

**Issue by omerblink** [quran/quran.com-frontend#631]
Just came on to this while I was reading the translation and needed to increase the translation font size. When I increases the font size of the translation the watch lecture link font size increases with it. Should we call it a bug of is it supposed to work like that?

<img width="1440" alt="screen shot 2017-02-01 at 10 28 56 pm" src="https://cloud.githubusercontent.com/assets/773535/22518642/2517222e-e8cf-11e6-948c-b0d8b4ee0591.png">

**Comment by qasimalyas** [comment]
Others might be able to comment further on this but i suspect this is by design and it should become larger as its a lecture by Nouman Ali Khan. So I wouldn't consider this as a bug.

**Comment by ahmedre** [comment]
but since the Arabic size isn't becoming larger, imho, "Watch lecture" shouldn't grow.

**Comment by mmahalwy** [comment]
This is by design. Since this is urdu translation it's hard to tell but it's other english, they should all grow.

**Comment by omerblink** [comment]
@mmahalwy Actually its doing in all translation

**Comment by mmahalwy** [comment]
That's correct behaviour
