### ISSUE TITLE
A tafseer icon would be great beside ayat

### ISSUE THREAD

**Issue by murad073** [quran/quran.com-frontend#639]
It would be great if a tafseer icon can be placed beside the other icons of an ayat. If someone click on that icon it will open a new tab with the tafseer of various scholars on that ayat. If possible, the history of that ayat, time and situation, chronology of appearance, etc.  

![image](https://cloud.githubusercontent.com/assets/1317890/22552167/cbe01150-e925-11e6-99ff-1d5c830aa049.png)

**Comment by mmahalwy** [comment]
Currently don't show tafsir but working on adding it

**Comment by naveed-ahmad** [comment]
There are multiple tafsir for each verse, actually in multiple languages. Yumee we need to think about good UX here.

**Comment by mmahalwy** [comment]
Tafsir is challenging because it can span multiple ayahs. check out how recitequran.com has done it. They have a different UI completely for it

**Comment by ysofi** [comment]
The above reasons (UX and interpretation spanning multiple ayahs) amongst others make me think perhaps it's better to have tafsir as a separate app. 

Perhaps tafsir.quran.com

Similar to corpus.

Tafsir discussion is scattered, what's the best channel to talk about it on the Slack group?

**Comment by mmahalwy** [comment]
+1 on @ysofi 

We can either do separate app or open a modal with that information.
