### ISSUE TITLE
"Loading..." shows up after last ayah of Surah Al-Jumu'a

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#64]
Can anyone confirm this?

**Comment by ahmedre** [comment]
the bug should be renamed - "loading indicator consistently appears after sura Jum3a's last ayah."

**Comment by ahmedre** [comment]
<img width="1090" alt="screen shot 2015-08-25 at 7 02 39 pm" src="https://cloud.githubusercontent.com/assets/47771/9484035/e64ffe56-4b5b-11e5-8ccf-5e6241be85f0.png">

**Comment by mmahalwy** [comment]
@ahmedre thanks for updating it!

**Comment by mmahalwy** [comment]
closing
