### ISSUE TITLE
Content : Sourat "Maryam" / Ayat 26 : missing the letter "Alif" at the beginning of the word "Ahadan"

### ISSUE THREAD

**Issue by jalal10** [quran/quran.com-frontend#645]
Assalamo alaykom,

There is an error on the Ayat **26** sourat **Maryam** - on the Firefox browser, missing the letter *Alif* at the beginning of the word *Ahadan* it is displayed, *Hadan*

Best regards
Jalal.
![sourat_maryam_ayat_26](https://cloud.githubusercontent.com/assets/5561041/22764715/4084206c-ee64-11e6-81fe-8278274e98b4.png)

**Comment by ahmedre** [comment]
wa3laikum alsalam,
looks like a Firefox specific issue - works fine on Chrome, but i can also repro on Firefox.
<img width="1006" alt="screen shot 2017-02-08 at 6 15 41 pm" src="https://cloud.githubusercontent.com/assets/47771/22766520/c829adaa-ee2a-11e6-8ed5-e93f6c60dfbf.png">

on Firefox, other things seem cut out too in that ayah for example - see the other arrow in my screenshot from Firefox that repros what brother Jalal mentioned.

<img width="917" alt="screen shot 2017-02-08 at 6 17 53 pm" src="https://cloud.githubusercontent.com/assets/47771/22766552/0e45eeac-ee2b-11e6-9b8e-1136bcedd7fb.png">

we should find a way to fix this for Firefox, if we can't, then we should use images by default there.
