### ISSUE TITLE
quick search for specific ayah

### ISSUE THREAD

**Issue by AmmarCSE** [quran/quran.com-frontend#648]
Assalamu Alaykum

Sorry if there is already a way to do this, but I havent found it.

If I am looking at a large surah and want to look at a specific ayah, I have to keep scrolling and wait for paging. There should be a way to do a 'scroll to' or search for a specific ayah.

**Comment by ahmedre** [comment]
wa3laikum alsalam,
why not just change the url - i.e. https://quran.com/3/190
walsalam 3alaikum

**Comment by AmmarCSE** [comment]
Ah ok,
Thanks for tip!

Perhaps there should be a feature request made for a way to do it via the UI for non-technical users.

**Comment by imomer** [comment]
Perhaps something like this:

<img width="1440" alt="screen shot 2017-02-14 at 1 10 35 pm copy" src="https://cloud.githubusercontent.com/assets/773535/22920704/414d73ba-f2b8-11e6-8e0a-87327a7d028c.png">

**Comment by AmmarCSE** [comment]
Exactly :-)

Unless you have already done or you are already doing it(you good deed hoarder, you ;-) ), I might be able to take a look at it this weekend.

However, if you already started, go for it.

Thanks

**Comment by imomer** [comment]
@mmahalwy @ahmedre Thoughts?

**Comment by mmahalwy** [comment]
There used to be a way before redesign. If you'd like to take it, more than welcome to. I'd suggest it goes in the top navbar beside the surah name.

**Comment by naveed-ahmad** [comment]
Yeah top bar make more sense.

**Comment by murad073** [comment]
I have one suggestion on this. Instead of creating a new place for quick ayat, I think an existing placeholder can be modified to serve this purpose - 

![image](https://cloud.githubusercontent.com/assets/1317890/23127883/b07006a4-f74a-11e6-946e-210b688c9cad.png)
