### ISSUE TITLE
Skip to verse number

### ISSUE THREAD

**Issue by AskYous** [quran/quran.com-frontend#654]
Currently, the only way (that I know of) is to enter it in the URL. But it's not obvious to users. I just had a friend complain and he had no idea how to skip 200 verses except 1 at a time.

**Comment by AskYous** [comment]
This should also be added to the homepage, such as a "Jump to" button like on the android app.

**Comment by sabeurthabti** [comment]
@AskYous I'd be happy to review a pull request on this, any ideas where it might fit within the UI?

**Comment by AskYous** [comment]
Thank you @sabeurthabti!

Here's two mockups where it should fit in the UI. Of course, use some styling too to make it go with the theme:

# Home Page
![image](https://cloud.githubusercontent.com/assets/791996/24323863/5a86477c-1139-11e7-96c6-ede1dda2d8f4.png)


# Soorah Page
----

![image](https://cloud.githubusercontent.com/assets/791996/24323825/fbd79316-1138-11e7-9dc9-4e475556a1e8.png)

**Comment by mmahalwy** [comment]
+1 @AskYous

**Comment by sabeurthabti** [comment]
@AskYous  + 1 love it. We have https://github.com/quran/common-components, where we put common components, this would be an awesome candidate.  Demo of current components: https://quran.github.io/common-components/
