### ISSUE TITLE
v3: Tafsirs

### ISSUE THREAD

**Issue by naveed-ahmad** [quran/quran.com-frontend#658]
Available tafsirs: http://staging.quran.com:3000/api/v3/options/tafsirs
You can get tafsir of individual verse via this endpoint: http://staging.quran.com:3000/api/v3/chapters/CHAPTER_ID/verses/VERSE_ID/tafsirs?tafsirs[]=TAFSIR_ID&tafsirs[]=ANOTHER_TAFSIR_ID ( you can ids from first endpoint ) 

sample URL: http://staging.quran.com:3000/api/v3/chapters/1/verses/1/tafsirs?tafsirs[]=90&tafsirs[]=91

**Comment by ATouhou** [comment]
There is a typo in the Key, it says: "tafisrs"

**Comment by naveed-ahmad** [comment]
@ATouhou thanks for catching the typo, fixed.

**Comment by naveed-ahmad** [comment]
done via https://github.com/quran/quran.com-api/pull/146
