### ISSUE TITLE
Stop button in audio player

### ISSUE THREAD

**Issue by murad073** [quran/quran.com-frontend#673]
In standard audio player, there supposed to be a stop button. While I want to re-listen a surah from the beginning, there is no way. Therefore I had to refresh the entire page. A stop button would be great to start over. 

![image](https://cloud.githubusercontent.com/assets/1317890/23659272/987c58d4-0313-11e7-8f53-dfca1882bad9.png)

**Comment by AhmedShab** [comment]
This should be a feature labeled not a bug

**Comment by sabeurthabti** [comment]
@murad073 @AhmedShab once playing the icon should change to pause/stop

**Comment by AhmedShab** [comment]
I will work on this :smile:

**Comment by andela-aolaniran** [comment]
Sallam @AhmedShab. Are you still working on this ?

**Comment by AhmedShab** [comment]
Walikum salam @andela-aolaniran, not yet. I was busy over the last few months. Sorry about that. I can get to it later. When do you guys need me to work on this?

**Comment by azeezolaniran2016** [comment]
@AhmedShab I asked because I was looking through issues and was interested in this. Since you're still working on it, I guess you can go ahead with it when its convenient for you.

**Comment by AhmedShab** [comment]
@azeezolaniran2016 I actually didn't start yet. You can go ahead and work on it. We can even collaborate on this if you like

**Comment by andela-aolaniran** [comment]
@AhmedShab Yea, I like :)

**Comment by azeezolaniran2016** [comment]
@AhmedShab Yea, I don't mind collaborating on this with you.
