### ISSUE TITLE
Beginning of the Surah button does not reset the player

### ISSUE THREAD

**Issue by murad073** [quran/quran.com-frontend#674]
Beginning of the Surah button does not reset the player. After clicking the button, if I click the play button, it starts reciting the last ayat I listened to. I think the right behavior is to reset the player to start from the beginning of the ayah. 

![image](https://cloud.githubusercontent.com/assets/1317890/23659566/8216b66a-0314-11e7-9c84-19ead7fbb507.png)

**Comment by mmahalwy** [comment]
+1 on this too :)

**Comment by naveed-ahmad** [comment]
This is simple, at of each surah there is "go to beginning of surah"
button. Clicking on it should reset player to first verse of surah.

**Comment by azeezolaniran2016** [comment]
Thanks @naveed-ahmad. Insha Allah I will look at it tonight.

**Comment by bahaa96** [comment]
@naveed-ahmad Close this.
