### ISSUE TITLE
Change of surah from top menu does nothing to audio player

### ISSUE THREAD

**Issue by murad073** [quran/quran.com-frontend#675]
I listened surah 36, after that I have changed to surah 112. But the audio player still shows ayah 83! it a bug

Before Navigate - 
![image](https://cloud.githubusercontent.com/assets/1317890/23659765/339c3900-0315-11e7-85e3-626aef9fc982.png)
 
After Navigate - 
![image](https://cloud.githubusercontent.com/assets/1317890/23659798/52463e96-0315-11e7-9e77-a43547dd4cef.png)

**Comment by mmahalwy** [comment]
+1 on this.

**Comment by imadmk** [comment]
@murad073 is this still happen on http://staging.quran.com:32934/112 ?

**Comment by murad073** [comment]
@imadmk I think it is resolved. Page is refreshing.

**Comment by mmahalwy** [comment]
I think this is going to change once my graphql PR gets merged
