### ISSUE TITLE
Night mode is not persistent  

### ISSUE THREAD

**Issue by murad073** [quran/quran.com-frontend#676]
I was listening surah 114 in night mode. While I changed the url to listen surah 36, the night mode is gone. 
I think night mode setting should be stored in local-storage. Currently any type of refresh could reset the night-mode.  

![image](https://cloud.githubusercontent.com/assets/1317890/23659994/00b59738-0316-11e7-871d-caf1d82a69d3.png)

**Comment by umairidris** [comment]
Settings like reciters, etc are already stored in an options cookie, is night mode not being stored there? Did you try refreshing the page? This may be the same as #550 where the options didn't get applied due to a timing bug.

**Comment by murad073** [comment]
refreshing also reset the night mode.

**Comment by mmahalwy** [comment]
It's not being stored! Need to store it

**Comment by naveed-ahmad** [comment]
this was intentional, you enable night mode only on nights :) 

But yes we can have cookie which last only 4-8 hours.

**Comment by sabeurthabti** [comment]
@naveed-ahmad we can try to work out the time of the day and enable it accordingly?

**Comment by naveed-ahmad** [comment]
`timezone` could make this simple toggle switch very complex imo @sabeurthabti also sorry I'm not that good in reactjs :( for now I'm just saving to in options cookies. We can work on intelligent night mode later on :) thoughts ?

**Comment by naveed-ahmad** [comment]
Maybe I'm missing something.

**Comment by mmahalwy** [comment]
i can help on this too.

**Comment by naveed-ahmad** [comment]
@sabeurthabti  @mmahalwy feel free to take over from https://github.com/quran/quran.com-frontend/pull/692 and make night mode timezone/day aware :)

**Comment by mmahalwy** [comment]
too difficult. plus, I like to see Quran.com in white bg all times. would be bothered if it changed by itself, personally.
