### ISSUE TITLE
Translation information in url

### ISSUE THREAD

**Issue by murad073** [quran/quran.com-frontend#677]
While I was sending a url as a reference to one of my friend (bangla), he did not get the correct translation at the first time. So I have to explain how to get the right translation from the setting menu. Is it possible to place the translation info in the URL, so that more meaningful url reference can be made? 

Example: https://quran.com/114/2?translation=3

**Comment by naveed-ahmad** [comment]
duplicate issue https://github.com/quran/quran.com-frontend/issues/552 closing.
