### ISSUE TITLE
Switch "previous" and "next" surah button positions -- confusing right now

### ISSUE THREAD

**Issue by navedcoded** [quran/quran.com-frontend#678]
This might be a matter of taste, but I find the current placement of previous surah button on the left and next surah on the right is very confusing -- as in the real mushaf the next surah would be towards the left.

Even the apps are like this and maybe the website should make this switch too?

**Comment by ysofi** [comment]
Switching it would make it confusing. The buttons are are in English, which is a left to right language.

In the apps swiping to the left (next) or right (previous) is akin to flipping the page. You're not pressing a button and definitely not one in a foreign (LTR) language. 

Wallahu 'alam.

**Comment by navedcoded** [comment]
Yeah I see what you mean. As salamu 'alaykum :)
