### ISSUE TITLE
[Major BUG] Settings Cause Error

### ISSUE THREAD

**Issue by sabeurthabti** [quran/quran.com-frontend#681]
Hi, 

The settings link the nav is causing the application to crash.  React is updating none stop, 
url:
https://staging.quran.com/

screenshot:
<img width="1301" alt="screen shot 2017-03-12 at 9 56 56 pm" src="https://cloud.githubusercontent.com/assets/2606228/23836380/0ed30f6e-076f-11e7-92a8-50a28450bba5.png">

This is a major block for any future production release.

**Comment by mmahalwy** [comment]
Ah yes, this will fix it https://github.com/quran/quran.com-frontend/pull/671

**Comment by naveed-ahmad** [comment]
Setting popup is still crashing app

<img width="772" alt="2017-03-18_0429" src="https://cloud.githubusercontent.com/assets/701567/24066348/8f03aef0-0b93-11e7-960a-905af8e9ae36.png">

**Comment by mmahalwy** [comment]
hmmm... sooo weird :S
