### ISSUE TITLE
Two page reading view

### ISSUE THREAD

**Issue by AskYous** [quran/quran.com-frontend#685]
I have a suggestion, which is to support two page reading view. There's plenty of space for it:

![image](https://cloud.githubusercontent.com/assets/791996/23932096/3c6599bc-08f3-11e7-96e5-7638ded33be0.png)

**Comment by mmahalwy** [comment]
Great idea! I will add it to project

**Comment by naveed-ahmad** [comment]
Two page view don't support infinite scrolling, user have to click `previous page` and `next page` OR a select tag for jump to specific page. IF we're going to have two page view anyway, how about this design: http://v4.globalquran.com/#/quran-uthmani+ar.jalalayn+en.ahmedali/1

https://github.com/GlobalQuran/site seems to be dead :(

**Comment by mmahalwy** [comment]
Agree.

**Comment by AskYous** [comment]
Salaam. I'm confused. I see the update on quran.com that it now takes up the entire page as in the screenshot below. Is this new UI the implementation of this issue? For this issue, I meant seeing two pages (like page 200 and 201 from the Mushaf with a separation in between). Not that the text should span the entire page.

![image](https://cloud.githubusercontent.com/assets/791996/25189880/6525be56-24df-11e7-96b0-b7d6241d1527.png)

**Comment by naveed-ahmad** [comment]
@AskYous two page view isn't possible. Issue is with scrolling and auto loading more ayah. ^ this was bug which is fixed.
