### ISSUE TITLE
When repeat is toggled on, clicking next should also repeat the next Aayah

### ISSUE THREAD

**Issue by AskYous** [quran/quran.com-frontend#687]
Salaam,

When I use the repeat option to memorize an Aayah, then click next on the player to memorize the next Aayah, the repeat feature still attempts to repeat the previous Aayah, and thus causes the next Aayah to be played. It gets confusing.

**Comment by maaizelahi** [comment]
Would love to help on this and any other issues....I am a front end developer with 6 years of experience

**Comment by mmahalwy** [comment]
@maaizelahi please take it! We need help!

**Comment by Nourin-Eka** [comment]
@maaizelahi Salam. Have you started working on this?

**Comment by maaizelahi** [comment]
@Nourin-Eka : Walaikum Assalam... Will be working on it over the weekend

**Comment by Nourin-Eka** [comment]
@maizelahi : In case you think I can help, please comment on this thread.

**Comment by imadmk** [comment]
@maaizelahi @Nourin-Eka Assalamualaikum. Is this still on development?

**Comment by sabeurthabti** [comment]
@imadmk please go ahead and work on this. Jzkallah

**Comment by imadmk** [comment]
Ok waiyyakum.

**Comment by mmahalwy** [comment]
This might be fixed by https://github.com/quran/quran.com-frontend/pull/843

Heads up
