### ISSUE TITLE
Please use WOFF2 fonts

### ISSUE THREAD

**Issue by praisedpk** [quran/quran.com-frontend#705]
AOA,

WOFF2 fonts are now supported by more than 75% of browsers, and the level of support is increasing day by day.

Why I have opened this issue is because:
1. WOFF2 fonts' file size is roughly quarter the size of TTF fonts;
2. Site loads really slow, and arabic text takes even longer to load on even not-so-slow connections.

Hope you take this as priority.
Jazakallah.

**Comment by mmahalwy** [comment]
salam. Can you take a look at staging.quran.com and let us know?

**Comment by praisedpk** [comment]
Wa Alaikum As Salam,

This one is a lot better. Font files are now relatively smaller. Also, your nginx is sending gzipped ttf files but keycdn will not do it when it will be live, that will have some performance impact.

Anyways, thanks a lot for continuously improving the site for us.
Jazakallah.

**Comment by mmahalwy** [comment]
@ahmedre can we confirm? CDN not sending gzipped?

**Comment by praisedpk** [comment]
FYI, Here is the screenshot of my Firefox 52.0.1: http://prntscr.com/emzd23
Content-Encoding for JS and CSS is fine for me.

**Comment by ahmedre** [comment]
jazakAllah khairan for pointing this out. this was actually my fault. this specific cdn host is based on pull (so it mirrors based on whatever the nginx config parameters are) - i unfortunately didn't have ttf as part of the gzipped types. i've fixed this now:

```
❯ curl -i "https://static.quran.com/fonts/ttf/bismillah.ttf" --silent --write-out "%{size_download}\n" --output /dev/null
303644

~
❯ curl -i "https://static.quran.com/fonts/ttf/bismillah.ttf" --silent -H "Accept-Encoding: gzip,deflate" --write-out "%{size_download}\n" --output /dev/null
189163
```

i've set the cdn to purge its cache, but not sure how long it takes to propagate, but let's keep an eye on it insha'Allah. jazakAllah khairan for reporting this.

**Comment by naveed-ahmad** [comment]
tried woff2, unfortunately didn't worked. We've very special/odd fonts ligga didn't worked with woff2. Closing this.

**Comment by praisedpk** [comment]
Sorry to interrupt again.

How did you verify that woff2 isn't working? Did you use Mac? Or Windows platform? Operating systems render woff2 fonts differently. Google font, when using woff2, sends different font files for Windows and Mac.

http://michaelboeke.com/blog/2013/09/10/Self-hosting-Google-web-fonts/
