### ISSUE TITLE
Clarification of using Source Code In Other Projects

### ISSUE THREAD

**Issue by mohamede1945** [quran/quran.com-frontend#714]
We would like to understand with no confusion, what are the guidelines for using the source code of any of the repositories under Quran organization?

Usually, we get requests for permission to use the source code to build another Quran app (Web/Android/iOS). We would like a clear statement on this matter.

**Comment by mmahalwy** [comment]
@mohamede1945 should we copy the license file you have in quran ios?

**Comment by mohamede1945** [comment]
Yeah, sure why not. It is the same one used in Android.
