### ISSUE TITLE
Limit selection of translations: User should not be able select more than xx translations

### ISSUE THREAD

**Issue by naveed-ahmad** [quran/quran.com-frontend#718]
Maybe max 10 translations.

**Comment by azeezolaniran2016** [comment]
Hi @naveed-ahmad, I would love to handle this issue. Any hints on where I could start would be appreciated.

**Comment by naveed-ahmad** [comment]
Salam @azeezolaniran2016 thanks, feel free to take this :) 

We currently have 60 translations, we might have more in future. For now user can select all translations, which don't make any sense plus api call with 60 translations will put huge load on server. One simple solution is to simply disable the translation checkboxes when user select 10 translations, if user de-select one then we enable all checkboxes again. Basically user shouldn't be able to select more than 10 translation. 


<img width="410" alt="2017-05-22_0113" src="https://cloud.githubusercontent.com/assets/701567/26287049/4675077a-3e8c-11e7-8cdf-e4b0dce4ce11.png">

Let me know if you've any question.

**Comment by azeezolaniran2016** [comment]
Thank you @naveed-ahmad.

**Comment by azeezolaniran2016** [comment]
Salam @naveed-ahmad. I have gone through this and I've decided to keep a count of how many items are checked and decide which checkboxes to enable or disable based of the checked count. 

I have also discovered that the custom CheckBox component does not expose the 'disable' property. Is there a work around for this/ what do you suggest ?

**Comment by azeezolaniran2016** [comment]
Oh, interesting. This has lead me to discover https://github.com/quran/common-components.
I'm thinking of raising a issue there to add the functionality of disabling Checkbox components if not already created.

**Comment by naveed-ahmad** [comment]
@azeezolaniran2016 Update quran-component to `0.0.71` added the disabled functionality few hours ago. Sorry forget to inform you earlier :)

**Comment by azeezolaniran2016** [comment]
Thanks @naveed-ahmad :)
