### ISSUE TITLE
Selecting ayaat within a range no longer works

### ISSUE THREAD

**Issue by houda95** [quran/quran.com-frontend#752]
Latest release no longer allows one to select ayaat to listen to within a range.  It is not possible to select which ayaat to include in the range.

**Comment by houda95** [comment]
I had a few minutes so was able to give the repo a quick glance and it seems as though commit https://github.com/quran/quran.com-frontend/commit/230eaf522747431097bbb24a8c376281cb2b94ef may have been the cause of the issue

It was committed at a similar time as to when I noticed the problem and seems to touch code which impacts the repeat functionality. I do not have access to my personal dev machine atm so I can't open a PR - hope this helps though.

**Comment by mmahalwy** [comment]
@houda95 sorry can you give more details about this? Screenshots, etc. I am a little confused by what you mean by range.

**Comment by houda95** [comment]
@mmahalwy my apologies - wasn't sure what to call it. The problem now appears to be fixed but for reference I was talking about this <img width="330" alt="range-image" src="https://cloud.githubusercontent.com/assets/5567940/25250836/96668366-265a-11e7-9982-284bfff9847a.png">

The 'From:' and 'To:' drop-downs were not being populated with the ayaa numbers.

**Comment by mmahalwy** [comment]
Okay, thank you!
