### ISSUE TITLE
Include reciter "Saad Al-Ghamdi" in the list of reciters.

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#76]

**Comment by ahmedre** [comment]
Two things:
1. We should switch to gapless first.
2. We should switch to word by word.
3. to avoid a million issues, we should combine all recitation requests in
one ticket.

**Comment by reshadn** [comment]
@ahmedre Assuming you meant this ticket.. =)
Add reciter "Tawfeeq ibn saeed as-Sawa'egh" http://quranicaudio.com/quran/23

**Comment by sharabash** [comment]
@ahmedre do we have word by word audio

**Comment by mmahalwy** [comment]
going to close this
