### ISSUE TITLE
Player and Go to verse issues

### ISSUE THREAD

**Issue by naveed-ahmad** [quran/quran.com-frontend#760]
Player and go to verse dropdown has multiple conflicts:

# Steps to reproduce issues: 
* Go to any Surah
* Play the first verse 
* Select any verse from go to verse dropdown 
* 1: Player will now play multiple verses simultaneously. Pause btn in player bar won't stop first recitation. 
* 2:  Go to 2/1, then select verse from dropdown which isn't loaded yet(> 10, say user select 30). Now user can't see first 10 verses yet player will keep playing them. BAD UX 

### IMO: `Go to verse` should stop currently playing verse and start playing selected one.

**Comment by AhmedShab** [comment]
@naveed-ahmad I will look into this if you like :)

**Comment by AhmedShab** [comment]
It looks like Mohamed is working on it. In that case, I can look for something else

**Comment by mmahalwy** [comment]
I think this is fixed no?
