### ISSUE TITLE
Bug: listening first verse does not continue to the next. 

### ISSUE THREAD

**Issue by murad073** [quran/quran.com-frontend#762]
Listen the first verses of a surah. It does not continue to the next verse. However, if you listen second verse, it will continue to the third verses, and so forth. 

I tired with chapter 2 and 3. Same for both. 

![image](https://cloud.githubusercontent.com/assets/1317890/25386764/756f4a64-2996-11e7-93e0-2c4c24e2657e.png)

**Comment by AhmedShab** [comment]
I'm keen to look into this bug 😄

**Comment by mmahalwy** [comment]
@AhmedShab please do!

**Comment by AhmedShab** [comment]
@murad073 I was testing this bug. Downloaded the project to my local machine and it seems it works fine. It starts the first verse of the surah then continue on.

There is a completely different bug though. After the initial start, you can't go back and listen from the first to the following order of the rest of the verses.

**Comment by AhmedShab** [comment]
Actually, I tested it again, it looks like if you already listened to the surah, come back to it again then listen one more time. It doesn't continue to the second verse. 

It's most likely related to cache. I tried to clear my cache and it worked. Will investigate  more to find the source in the code

**Comment by AhmedShab** [comment]
@mmahalwy  Here is what I discovered. The first time when you go to a Surah, it shows the progress bar from the start (initial progress bar is at the beginning). Then when you refresh the page, the first verse's progress bar, for some reason, is at the end. Therefore, the state does not change and that concludes why `handleAddFileListeners` method is not being called. It's the one which is responsible for moving the audio from verse to verse.

Is there anyone I can talk to who worked on this project? There is so much to digest but I'm getting my head around it now. The async in Redux is probably is the only part I'm confused about (asyncConnect -- redux-connect) and how `file` is audio html audio element 

![move_to_next_verse_bug](https://cloud.githubusercontent.com/assets/12079101/25559421/cd097880-2d8d-11e7-9f57-e38b286cb9f0.png)
![move_to_next_verse](https://cloud.githubusercontent.com/assets/12079101/25559424/ded0e562-2d8d-11e7-83c0-53f1ac4e1ec9.png)

**Comment by murad073** [comment]
@AhmedShab , thanks for looking into the bug. Actually I tried again, and the bug seems exists, without moving to another surah and come back. 

Here goes the environment details: 
Machine: Windows 7 x64 
Browser: Chrome 
Url: https://quran.com/2 
Action: instead of clicking the player buttons, I clicked small play button with the first ayat, Refer to the actual bug image. 
Comment: Cache Clear has no impact on the bug. Still persists.

**Comment by mmahalwy** [comment]
Sorry guys, had my plate full but slowly getting back to it for bugs + others before Ramadan!

**Comment by AhmedShab** [comment]
I noticed that it doesn't move the progress bar instead of not having it loaded. I'm convinced it's something to do with the cache. If you try Ctrl + F5, it works just fine (http://refreshyourcache.com/en/cache/)

When I run it on my local machine, it seems like every time it reloads it clear the caches

I might have to investigate the backend as well for this task. @mmahalwy, can you direct me to where I can find that? Thanks

**Comment by sabeurthabti** [comment]
Fixed by @AhmedShab
