### ISSUE TITLE
Audioplayer is empty when in reading mode

### ISSUE THREAD

**Issue by AskYous** [quran/quran.com-frontend#763]
![image](https://cloud.githubusercontent.com/assets/791996/25463971/b5303820-2aae-11e7-83ef-aef75bfa057b.png)

**Comment by KashifHK123** [comment]
Please Change Browser and 

> Make sure your browser proper running javascript

 because "**Quran.com**" based on **Javascript**.

**Comment by mmahalwy** [comment]
@AskYous is correct. I think there is a bug with reading mode.

**Comment by AskYous** [comment]
It's actually appearing for me now. I didn't change anything.

**Comment by AskYous** [comment]
It's happening again:

![image](https://cloud.githubusercontent.com/assets/791996/25644316/099ae9c8-2f5a-11e7-9a62-457e3e7dab79.png)

**Comment by mmahalwy** [comment]
This is a known bug. I think i logged it somewhere.

**Comment by mannanali413** [comment]
@mmahalwy i can pick this up.

**Comment by mohhasbias** [comment]
@mannanali413, are you still working on this?

**Comment by mannanali413** [comment]
Yes

**Comment by mmahalwy** [comment]
@mannanali413 sorry, due to ramadan being tomorrow, had to rush on this. Should be fixed in: https://github.com/quran/quran.com-frontend/pull/772
