### ISSUE TITLE
Add hreflang

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#766]
See airbnb:
![image](https://cloud.githubusercontent.com/assets/3749095/25494367/4676f164-2b2e-11e7-8169-7c8896c03f25.png)

With google telling us:
![image](https://cloud.githubusercontent.com/assets/3749095/25494373/4d2217d2-2b2e-11e7-9f24-05c1b7dc97d3.png)

**Comment by naveed-ahmad** [comment]
Duplicated  https://github.com/quran/quran.com-frontend/issues/544

Need to decide the url format, en.quran.com OR quran.com?language=en
