### ISSUE TITLE
UI for pagination

### ISSUE THREAD

**Issue by naveed-ahmad** [quran/quran.com-frontend#769]
Infinite scrolling is great but it has few drawback as well. For slow connection you want to load fewer items per page, and sometime you accidentally scroll down and app triggered the call to load more items. Loader cover the whole screen, impossible to do anything until the more items are not loaded and rendered. How about this is ? let user decide the app behaviour! just mockup, we can have better messaging. @sabeurthabti @mmahalwy @ahmedre 

<img width="580" alt="2017-04-27_2325" src="https://cloud.githubusercontent.com/assets/701567/25498285/db227352-2ba0-11e7-8c01-95ffff4cdb7b.png">

**Comment by ahmedre** [comment]
i like Apple's approach of "pick the right ui behavior for the user and provide as few options as possible" - i think auto load on scroll is good, but we can be much more restrictive about it. on mobile, we have something that gives us an estimate of how good or bad the connection is - is there something similar for web that we can use and then we can limit or gate accordingly?

**Comment by AskYous** [comment]
I would like auto scroll still there, but just remove that big loading circle that covers the entire page. It's very very annoying.

**Comment by ysofi** [comment]
@AskYous 

Agreed!

It breaks the reading flow unnecessarily. The loader should be set back to the bottom as per PR #750

+1 Ahmed

**Comment by mmahalwy** [comment]
Agreed. I don't like the loading on the whole page.

**Comment by mmahalwy** [comment]
Going to close this. Seems like no progress. Feel free to reopen
