### ISSUE TITLE
Follow Arabic audio by auto-scrolling the page.

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#78]

**Comment by ahmedre** [comment]
and, more importantly, highlighting the playing ayah.

**Comment by mmahalwy** [comment]
Following.

**Comment by mahboob-awan** [comment]
@mmahalwy  is it fixed? it is really great for better UX.

**Comment by sabeurthabti** [comment]
@mahboob-awan This is much more challenging, we do have it for some Reciters, but the data isn't available for the others. Change Reciter to Mohamed al-Tablawi and you should see it working.

**Comment by mahboob-awan** [comment]
Aha, so it data specific implementation.

@sabeurthabti,thanks but here i have a question:
 why not handling Ayah via "hash"? (e.g.https://quran.com/18#4)

and if we update hash for every Ayah, it can easily fix via native solution [:target](https://developer.mozilla.org/en-US/docs/Web/CSS/:target)

**Comment by sabeurthabti** [comment]
@mahboob-awan good question, I think the idea behind `18:4` or `18/4` rather than hash is because people reference chapters and verses in such a matter. We can add support for hash but no remove previous implementation as people use this website to reference verses. I am happy to review PR.

**Comment by mmahalwy** [comment]
+1 on the hash for quick reference but not removing old implementation. I don't remember what happens with react-router when adding a hash, so long as we don't get a rerender :)
