### ISSUE TITLE
Sura toggle does not change to current surah

### ISSUE THREAD

**Issue by zfaizal** [quran/quran.com-frontend#793]
Asalamualaikum, I am not sure if this issue has been flagged after looking through current issues but I have found that when toggling between Surahs either using the dropdown, or the arrow toggle the name of the Surah in the top left does not change to the current Surah. 

![screenshot](https://cloud.githubusercontent.com/assets/2507977/26134212/9a1c9820-3a72-11e7-95cf-42565881dc52.png)
For example, here we see that the Surah name displayed is Al-Qadr but the current Surah is Fatihah. Will look into it, but just a heads up. 

Jazakallah!

**Comment by mohhasbias** [comment]
i've tried to reproduce this problem. but i got the inverse of it, such as these
![image](https://cloud.githubusercontent.com/assets/2347137/26222504/705ce2b4-3c44-11e7-94de-e1d9b2fc211d.png)
The surah is Al-Qadr, but the toggle is Al-Fatihah.

To reproduce:
1. Visit Quran.com
2. Click Al-Fatihah
3. From surah toggle (select), choose Al-Qadr.

**Comment by zfaizal** [comment]
The toggling is not limited to those Surahs only. They apply to the toggling to any Surah. If you were to follow your directions again exactly, but this time:

2. Click Al-Qadr
3. From surah toggle select Al-Fatihah 

Now, you will see what I have shown. The main issue is that the toggle does not match surah which the displayed ayahs are from.

**Comment by Hartha-aloufi** [comment]
I notice the same issue again, did you fix it ?
