### ISSUE TITLE
Add tafsir(s) (preferably in English) to alpha.quran.com.

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#80]

**Comment by ATouhou** [comment]
To get the tafseer from www.alim.org / recitequran.com Or qtafsir.com !  would be amazing

Also Recitequran.com have sound recitations for each word, both with / without tajweed

**Comment by reshadn** [comment]
+1 Any copyright restrictions?

**Comment by mmahalwy** [comment]
We have arabic tafsir: http://api.quran.com:3000/content/tafsir/6166

I want to release it with english too

**Comment by rahiel** [comment]
Assalaam, I've recently extracted the tafsir al-Jalalayn from the pdf by [altafsir](http://www.altafsir.com/Al-Jalalayn.asp). I've attached it here in json format. It is a list of 114 surahs, each a list of their verses. I haven't asked for permission to use/distribute it, but you may find this helpful.

(It was generated by first converting the pdf to text with `pdftotext -nopgbrk Al_Jalalain_Eng.pdf` and then running it through [this function](https://github.com/rahiel/BismillahBot/blob/1d792532326b5b6fcd72b2051a5a2b2ea44af111/quran.py#L33) and finally dumping it as json.)

[tafsir.txt](https://github.com/quran/quran.com-frontend/files/34122/tafsir.txt)

**Comment by mmahalwy** [comment]
@rahiel this is awesome! Think we can do the same for Ibn Kathir? I can work on the permissions during the weekend to send out the appropriate emails. We can try to make make it open-source-ish, with api key requirement for example? 

@ahmedre thoughts ^^

**Comment by rahiel** [comment]
@mmahalwy If there is a pdf/source for Ibn Kathir with some structure, then yes, you can parse it. Doing tafsir [Ibn Abbas](http://www.altafsir.com/Ibn-Abbas.asp) would require less effort, because the pdf has similar structure to the one for Al-Jalalayn. I can do it if quran.com will use it.

**Comment by ahmedre** [comment]
just to be clear, we have Jalalayn in both Arabic and English - we intentionally removed the English after speaking with a sheikh. with respect to this particular version of Ibn Abbas's tafseer, we should consult with a sheikh - from that page, it says, "Despite its uncertain authorship and its reliance on the controversial Isrâ’îliyyat or Israelite stories, Tanwîr al-Miqbâs nevertheless offers readers valuable insight into the circulation and exchange of popular ideas between Islam, Judaism and Christianity during the formative phase of Islamic exegesis."

not sure if something like that is a good idea to add to the site.

**Comment by sharabash** [comment]
i think we should lay the groundwork for tafsir and just silently disable it until we have proper sources like we did for surah info; @mmahalwy what happened to the surah info code?

what i visualize is a separate panel with content (tafsir) corresponding to the selected ayah

**Comment by mmahalwy** [comment]
@sharabash @ahmedre do we have english tafsir? @rahiel any way we can get ibn kathir pdf?

**Comment by ATouhou** [comment]
Tafseer ibn kathir is widely available on the Internet. But it is not indexed ayah for ayah but maybe 3 ayah is all within 4 different page topics etc. So would be best to index from existing site if you ask me.
In regards to sura info, alim.org has 2 great resources

**Comment by mmahalwy** [comment]
@ATouhou do you have a copy of the ibn kathir english? We can index it then.

**Comment by ATouhou** [comment]
@mmahalwy   Yes.  http://www.kalamullah.com/Books/Tafsir%20Ibn%20Kathir%20all%2010%20volumes.pdf  
 

If you want something already indexed,  recitequran.com and qtafsir.com got it indexed
