### ISSUE TITLE
Are refactor PRs allowed?

### ISSUE THREAD

**Issue by UmanShahzad** [quran/quran.com-frontend#801]
Assalamu Alaikum brothers --

I wish to inshAllah get involved in contributing to Quran.com whatever way I can, and the first step for me would be to get more familiar with the codebase, its structure, etc..

In the process of reading through it I reckon I'll find random things that could be refactored, and usually a new reader or a developer coming back to read his own code has the best eye for these things, so I think it may be a useful contribution in preparing for more significant ones later.

Would you brothers be okay with accepting a primarily refactor-based PR? I know some orgs don't like that that's why I'm asking before I do it and realize I have to throw it away :)

If all's good, I'm perfectly happy with a strict review that ensures I don't change something that was in fact intended.

**Comment by mmahalwy** [comment]
Please do! Refractors are more than welcome, but the only thing I'd caution is making it easier for us to review it and making it easier for us to transition it in. The last thing we would want is a huge PR that sits there and is a complete rewrite. Lastly, if you foresee it will be slightly larger, maybe create PRs against an open PR of your own (branch called refactor, branch called refactor1 that is to merge into branch refactor).

Other than that, please do! We need lots of help and I been meaning to do some refactoring too

**Comment by UmanShahzad** [comment]
@mmahalwy Great to hear! Definitely willing to help. Will take your advice into mind -- no one wants to a deal with a diff-mess-fest, understandably. I'll try to just incrementally push a PR when it looks like it's getting significant, to keep each one relatively light, inshAllah.

Looking forward to helping :)

**Comment by mmahalwy** [comment]
Going to close this!
