### ISSUE TITLE
There are problems with the auto-loading of ayahs around 121-131 in as-Saffat

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#802]
From @ysofi:

```
There are problems with the auto-loading of ayahs around 121-131 in as-Saffat

Manually going to them is OK. e.g. quran.com/37/125

Seems to be consistent across major browsers

There is also a couple of related support tickets
```
Error:
```
MIDDLEWARE ERROR: TypeError: Cannot read property 'text' of null
```

**Comment by naveed-ahmad** [comment]
its data related issue: 

 {
          "id": 77955,
          "position": 4,
          "text_madani": null,
          "text_indopak": null,
          "text_simple": null,
          "verse_key": "37:130",
          "class_name": "p451",
          "line_number": 2,
          "page_number": 451,
          "code": "&#xfb62;",
          "code_v3": "&#xfb62;",
          "char_type": "word",
          "audio": {
            "url": "//verses.quran.com/wbw/037_130_004.mp3"
          },
          "translation": null,
          "transliteration": null
        }

**Comment by naveed-ahmad** [comment]
إِلْ يَاسِينَ
 Need to break down them into two words, well we already found this while importing word audio. Sorry forget to fix :(

**Comment by naveed-ahmad** [comment]
note to myself:

**Comment by mmahalwy** [comment]
@naveed-ahmad thanks for finding it - what should I do for this?

**Comment by naveed-ahmad** [comment]
Need to fix the data, best tool to fix the data is community admin panel. We need to have production build for community. OR update via console( on all servers ) I believe @ahmedre was working on community build yesterday.

**Comment by naveed-ahmad** [comment]
Fixed.
