### ISSUE TITLE
Overlay loading is quite distracting when loading next ayah

### ISSUE THREAD

**Issue by jama707** [quran/quran.com-frontend#810]
Assalam alaykum,

The Loading overlay between ayah loads is a bit distracting. Is it possible to add smaller loading line like Github/Youtube: http://www.usabilitypost.com/2013/08/19/new-ui-pattern-website-loading-bars/

**Comment by naveed-ahmad** [comment]
@mmahalwy already fixed this https://github.com/quran/quran.com-frontend/pull/750 not sure why this wasn't merged with last build.
