### ISSUE TITLE
Loading pop up always showing on the bottom left corner

### ISSUE THREAD

**Issue by Gujarats** [quran/quran.com-frontend#811]
This happens when I change surah where I click next surah atfer reaching the bottom of the surah.
here is the screen shoot  : 

![quran loading screen](https://cloud.githubusercontent.com/assets/10476678/26623907/6aa93bc2-4619-11e7-802b-f0f5c8d2a53c.png)

any idea why this problem exist?

**Comment by naveed-ahmad** [comment]
Sorry can you explain what's wrong with navigating to next surah ? @Gujarats

**Comment by Gujarats** [comment]
@naveed-ahmad, the next surah navigation is working. the problem was that loading on the left bottom corner. can you see it on the picture ? it is always shows up.

**Comment by naveed-ahmad** [comment]
ah ok, yeah this is known bug and actually already fixed :) 

Closing, feel free to reopen if you can reproduce this bug on https://staging.quran.com.

**Comment by Gujarats** [comment]
@naveed-ahmad Okay I see. thanks for letting me know about this.

**Comment by Gujarats** [comment]
Hi @naveed-ahmad . I found this bugs again on staging. 
https://staging.quran.com/10/21 
when I go to that url. any idea?

**Comment by naveed-ahmad** [comment]
@Gujarats sorry can't reproduce this. Works fine for me. Care to share some screencast/video?

**Comment by mrtugicom** [comment]
@naveed-ahmad I opened #1060 which has similiar issue with additions, I cant even see any surah or ayah on staging at this time. But its actually happens on quran.com after navigating from home page.

**Comment by naveed-ahmad** [comment]
@mrtugicom yes api is down. Working on it.
