### ISSUE TITLE
Can't play verse past 10

### ISSUE THREAD

**Issue by ibz096** [quran/quran.com-frontend#816]
I am unable to play any verse of a surah past the 10th verse.

I have noticed this for Al-Baqarah and Al-'Imran.

I usually see the following message in the console 

> Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().

**Comment by ajalger** [comment]
Same issue .. except verse 8 was stopped. Same error

**Comment by azizur** [comment]
I am seeing the same issue here.

After the playback starts I am getting:
`Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().`

**Comment by mmahalwy** [comment]
Salam all, is this problem still existent? @ibz096 @ajalger @azizur ?

**Comment by ajalger** [comment]
Similar issue is still there. Here are the screen shots I have for Chrome 62.0.3202.89 and Firefox Dev 58.0b1. In Firefox (regular version) it works perfectly.

Chrome 62.0.3202.89
<img width="485" alt="screen shot 2017-11-12 at 3 18 32 pm" src="https://user-images.githubusercontent.com/6264696/32704627-2c887238-c7bd-11e7-905e-d8afaf92faed.png">

Firefox Dev 58.0b1
<img width="736" alt="screen shot 2017-11-12 at 3 17 35 pm" src="https://user-images.githubusercontent.com/6264696/32704631-3d9b75b6-c7bd-11e7-8258-0f29cc00f183.png">

**Comment by mmahalwy** [comment]
Very weird... okay, going to try to fix this
