### ISSUE TITLE
Shape of the circle around the number of the verse

### ISSUE THREAD

**Issue by KhadimAlQuran** [quran/quran.com-frontend#817]
Assalam alaykom wa rahmatou Allah ta3ala wa barakatouh,

May Allah reward you for the great and hard work and may Allah help you in the Ihssan of this great project.

Talking about Ihssan , I really dislike the shape of the circle around the number of the verses, I feel that is like ears of a devil and for that reason I don't share pictures of ayat when this shape is around a number of a verse.

You may think that is no sense, but I hope that you'll considere seriously my point and choose other shape for the circle, or even make it as simple as possible without any artificial drawing , the beauty of the verses have no need of it ...

I can help on programming and fixing issues ...
Ramadan Moubarak Karim

**Comment by UmanShahzad** [comment]
@KhadimAlQuran One must remember that drawings of the devil are themselves artificial, and our understanding of the devil's ears may be wholly incorrect or simply unfounded in truth. However I think the best contribution if you're not convinced would probably be an alternative image file (?), but the main contributors probably know better.

**Comment by KhadimAlQuran** [comment]
This one for exemple :
https://pixabay.com/fr/séparateur-verset-coran-nombre-36415/

I ll try to find a better one

**Comment by KhadimAlQuran** [comment]
@UmanShahzad I agree with you about the shape of devil's ears but even in Islam tradition we always prevent ourselves to draw such things.. and we use only geometrical shapes such octogonals (8 sides) as reference to the 8 doors of heaven...
I'm not a native english speaker so forgive my mistakes
I hope you like this picture : https://pixabay.com/fr/séparateur-verset-coran-nombre-36415/
And you'll use it. It's free for commercial use

**Comment by UmanShahzad** [comment]
@KhadimAlQuran I actually like that picture, but not sure how this is implemented for Quran.com, @mmahalwy would know better.

**Comment by naveed-ahmad** [comment]
Salam 3alaikum @KhadimAlQuran @UmanShahzad going to close this, lets continue discussion on slack if you've any question. WHY?

- Shape of Ayah numbers are not images, they're font. We can't change glyph, its not single glyph we've to modify 286 glyph to change the shape, even if we could change 286 glyph I'm not sure what we're gaining here
- Lets focus on more important issues, tafsir, audio bugs etc
- Rest assured its not devil image :)

**Comment by UmanShahzad** [comment]
@naveed-ahmad Ah, didn't know that was the case of how it's implemented. Yeah that would be pretty troublesome.
