### ISSUE TITLE
Filters for Parah [Feature Request]

### ISSUE THREAD

**Issue by ismailfarooq** [quran/quran.com-frontend#819]
Currently we have filters for Surah and Verses but not for Parah can we have this too ?

**Comment by UmanShahzad** [comment]
@ismailfarooq This is actually a good feature request -- I know many people, including my own Mother, who think of the Qur'an primarily in Parahs and not Surahs necessarily.

**Comment by naveed-ahmad** [comment]
I don't like the UI but now user can filter by Parah/Juz on home page.
