### ISSUE TITLE
wrong highlight in reading mode

### ISSUE THREAD

**Issue by ducaale** [quran/quran.com-frontend#825]
it usually happens when ayah spans multiple lines.
![capture](https://user-images.githubusercontent.com/16341131/27100383-955ca6ca-5086-11e7-987c-410dfc09a1e6.PNG)

the highlighted words all share an id of "word-6-6-2".

on a closer inspection it seems word id is composed of the ayah number and the index of the word in line

**Comment by ducaale** [comment]
on a closer inspection it seems the way id is composed of the ayah number and and the index of the word in line

**Comment by techmaniack** [comment]
I can confirm this.

OS: OSX Darwin
Browser: Safari, Google Chrome
