### ISSUE TITLE
Misalignment of Arabic surah names on homepage

### ISSUE THREAD

**Issue by refrigerator** [quran/quran.com-frontend#828]
Hi,

Apologies in advance if this comes across as nit-picking, but in the surah list on the homepage, the Arabic names of the surahs are misaligned. This means that it looks a bit off, and some of them actually overspill from their box when hovered:

![image](https://user-images.githubusercontent.com/983210/27412051-e6b8474a-56e9-11e7-87cd-f904665e727f.png)

Quick fix that seems to work - add `float: right` to the `[class*=" icon-surah"], [class^=icon-surah]` selector:

![image](https://user-images.githubusercontent.com/983210/27412086-1f572ac6-56ea-11e7-8e9a-46fb9bb54def.png)

Thoughts?

**Comment by mmahalwy** [comment]
Thanks for taking a look into it! Mind putting together a PR to fix it?

**Comment by UmanShahzad** [comment]
@refrigerator Nice catch!

**Comment by ajalger** [comment]
Is this being worked on? If not, I can make the quick fix so the page will look better.

**Comment by refrigerator** [comment]
@ajalger please go ahead :)
