### ISSUE TITLE
Turn off word-by-word translation when no English translation is selected, and another language is selected because the word-by-word is only in English.

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#83]

**Comment by ATouhou** [comment]
This guy (http://quranapp.omaralzabir.com/)  have word-by-word in arabic(translitteration), the ROOT of the word(like your corpus.quran request) and also have word-by-word in BANGLADESH.
He is also on Github with the app/site :-)

**Comment by mmahalwy** [comment]
Hmmm interesting. We may find good use for that! 

What's his github?

**Comment by ATouhou** [comment]
https://github.com/oazabir/QuranApp

He is working on it, as we speak :-)

**Comment by ATouhou** [comment]
He have indonesian word-by-word. 
Assuming there are more indonesian speaking muslims, than english speaking. This should be a must-have as well.  So word-by-word should not be coded as an english only solution... Also for supporting future languages easily in API structure?

**Comment by mmahalwy** [comment]
@ATouhou unfortunately we just don't have the word-by-word data. That's the blocker

**Comment by ATouhou** [comment]
It is in the brother Omar's application: https://github.com/oazabir/QuranApp . 
You can request it from him?

**Comment by dashohoxha** [comment]
@ATouhou: Would you be willing to add these data and the feature to the application?
@mmahalwy: I suggest that you assign this task to ATouhou, what do you think?

**Comment by ATouhou** [comment]
@dashohoxha  I am a LAMP stack developer. I can't really contribute to this project :/

**Comment by mmahalwy** [comment]
The data might not be difficult to import and might be useful actually. Just need to add the features to front-end to pull that data (as well as API).

I'd suggest we revisit this after Ramadan?

**Comment by dashohoxha** [comment]
> I am a LAMP (linux, apache, mysql & PHP) stack developer. I can't really contribute to this project :/

@ATouhou I am in a similar position.
However I do wish I knew RoR, and maybe one day I will start learning it.
Until then I am restricting myself only to reporting bugs. Asking for new features, in my opinion, is not right, unless you are willing to contribute those new features, or at least help in developing them. From my experience, this is how it works on the open source world.

**Comment by mmahalwy** [comment]
@dashohoxha on the contrary - we love how responsive you have been and how helpful you are in reporting bugs and bringing features to the discussion. Don't mind us, though, if for the next 2 weeks we are heads down on getting ready for Ramadan. 

One thing, if you'd like to, that you can help us setup is a Slack self signup app. I know they exist cause I had to sign up with them before but people can self sign up them selves to the quran Slack.

**Comment by mmahalwy** [comment]
@dashohoxha found it https://github.com/rauchg/slackin

**Comment by ATouhou** [comment]
Well we are in the open muslim world :P I suggest whatever I find beneficial for the ummah brother, regardless if I can contribute or not. 
Whatever is the standard in the "open source world" I don't really care brother, unless they are based on islamic values. 

As the API is going to be treated on multiple platforms and in multiple countries, it should be done as correctly as possible, for future support - and we are already at v2 :P 


I am contributing however I can and given I do have an bachelors degree in project management, communication etc. I think it is fine, that we do have some participants who solely are contributing through advice and thoughts - we shouldn't disregard the input of non developers. 


I am sure the brothers knows how to prioritize and can see what amount of people are accessing from indonesia.  

- From Wikipedia:
Indonesia is the fourth most populous nation in the world (after China, India and the United States). Of its large population, the majority speak Indonesian, making it one of the most widely spoken languages in the world.

**Comment by dashohoxha** [comment]
> @dashohoxha on the contrary - we love how responsive you have been and how helpful you are in reporting bugs and bringing features to the discussion.

That's great, and its up to you.

In my experience, whenever I asked other people for new features it never happened, because they were busy with other things. Whenever other people asked me for new features it rarely happened, because I was already busy with other things. So, whenever I needed some new features, the shortest path was to try and implement them myself, and then ask other people to include them into their project. This is not about "open source standards", this is about my experience.

By the way, I don't think of "islamic values" as being different from basic human values, but this is an entirely different topic that we should avoid discussing here.

**Comment by dashohoxha** [comment]
> One thing, if you'd like to, that you can help us setup is a Slack self signup app.

I have no idea what Slack is, why do you think that I can help you with it? Its website does not even describe what are its features.
Is it kind of a modern IRC (chat) app, something similar to https://telegram.org/ ?

**Comment by mmahalwy** [comment]
It is. We use Slack internally with Quran.com team
