### ISSUE TITLE
Player loading endlessly after selecting a verse

### ISSUE THREAD

**Issue by Papisco** [quran/quran.com-frontend#830]
When selecting a verse after 20 for instance in Surah An Nur the player is loading and never ends.

**Comment by benweet** [comment]
Same problem here.

**Comment by imadmk** [comment]
This is maybe a known bug on [here](https://github.com/quran/quran.com-frontend/issues/811). It is partly done, maybe you can check on staging.quran.com and check if it still exist.

What i found done on staging is, a bug that makes audio player to stuck on `loading` state after we change to any verse.
But i found another bug if we play the audio or press next until ayah > 1, and then move to other chapter / surah via navbar. In production, the audio player still stuck on loading state, but on staging, the page is stuck on loading, nothing loads other than navbar and footer.

If no one haven't fix this yet, Insha Allah i will try to fix this.

**Comment by mmahalwy** [comment]
Might be fixed by https://github.com/quran/quran.com-frontend/pull/843

**Comment by naveed-ahmad** [comment]
@imadmk ayah and surah navigation is fixed https://github.com/quran/quran.com-frontend/pull/863

**Comment by naveed-ahmad** [comment]
@mmahalwy graphql is great, but we should have fallback option. Looks like your PR may take few more week/month :)
