### ISSUE TITLE
Put transliteration in its own section, not under English.

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#84]

**Comment by ATouhou** [comment]
There is also a turkish translitteration (more easy to read for Turks) that could be added, so that it does not stand alone under "Translitteration"

**Comment by ATouhou** [comment]
Can be downloaded from here: 
http://globalquran.com/download/data/

The author of the page is also on Github :-)

**Comment by mmahalwy** [comment]
i dont think this is a valid issue. going to close
