### ISSUE TITLE
Tilt.com contribution link is broken

### ISSUE THREAD

**Issue by yazinsai** [quran/quran.com-frontend#853]
The link to contribute (see below) is broken:

![image](https://user-images.githubusercontent.com/1846034/29006257-12cd0b20-7af5-11e7-8d9d-e516c7404765.png)

It currently redirects to https://quran.tilt.com/support-quran-com-preorder/checkout/payment which, according to Chrome, `uses an unsupported protocol`

![image](https://user-images.githubusercontent.com/1846034/29006265-3281ac64-7af5-11e7-96f8-87ab62ad608a.png)

This is probably because Tilt.com is retired:

![image](https://user-images.githubusercontent.com/1846034/29006269-49fd12de-7af5-11e7-8043-a2b5ae09c0dd.png)

Suggestions for possible alternatives? You could just use Stripe, if you've got a legal setup.

**Comment by sabeurthabti** [comment]
Thank you @yazinsai, 

@mmahalwy has this on his evergrowing todo list.

**Comment by yazinsai** [comment]
I'm surprised there's no Patreon (or alternative) for this project. It is *so* worth it, and I know I would contribute. 

The only way to ensure this project gets the attention it so rightly deserves is to dedicate resources to it. That's not going to happen without some form of compensation. 

It's amazing how far this has come without full-time resources, and I'd hate for this project to suffer the same fate that so many other excellent (but unfunded) open-source projects have.

**Comment by mmahalwy** [comment]
@sabeurthabti oh gosh :( I built a reputation for that! :) 

@yazinsai Agreed. Either we need more dedicated volunteers or we need some funding for people to work on it and future projects full time.

**Comment by naveed-ahmad** [comment]
https://github.com/lockitron/selfstarter We can roll our own mini crowdfunding app as well.

**Comment by mmahalwy** [comment]
Update on this, for the time being, I have a friend that has a company for this stuff specifically. It's a quick drop in solution until we figure out a longer term one

**Comment by zbhoy** [comment]
1 year later and the contribute option still goes to a dead Tilt link. Can't it just be switched to something people can donate to?

**Comment by abbatykori** [comment]
Just wondering if there's any progress on this. Patreon, PayPal etc?

**Comment by zbhoy** [comment]
Yeah not sure why this was closed. Contribute page still goes to a dead link

**Comment by zbhoy** [comment]
@mmahalwy @naveed-ahmad

**Comment by ahmedre** [comment]
we'll make sure to remove this from the next version in sha' Allah.

**Comment by zbhoy** [comment]
Just noticed new repo. Should i make issue there or y'all got it?

**Comment by ahmedre** [comment]
i pinged Naveed about it - but please feel free so we have something to track it in case we forget. jazakAllah khairan.
