### ISSUE TITLE
Hanging on npm run dev

### ISSUE THREAD

**Issue by junwatu** [quran/quran.com-frontend#857]
Salam,

I think i can't run `npm run dev` sucessfully on Windows 10 64 bit. The browser never show the homepage by the way. Any ideas what could be wrong? 

![2017-08-18_16-33-01](https://user-images.githubusercontent.com/948279/29461338-93dc1f9e-8455-11e7-9944-4ee64c10359f.jpg)

**Comment by mmahalwy** [comment]
Hmm, we haven't done a good job to support windows. That being said, I can see that where it's 'stuck' is usually something that takes a while (about 30s for me). We would like to remove bootstrap plugin for webpack because it's slow!

**Comment by imadmk** [comment]
I think i now what cause this. I am often using windows but use `Git Bash` or Bash Ubuntu for Windows mostly for running or compiling.
The stuck that i found caused by sass that taking to long to compile, or maybe not the sass, but this lines of code
```
@mixin word_font($page) {
  @font-face {
    font-family: p#{$page};
    src: url('//quran-1f14.kxcdn.com/fonts/ttf/p#{$page}.ttf') format('truetype');
  } // @font-face {
  //   font-family: text#{$page};
  //   src: url('../../static/fonts/embed_ttf/tp#{$page}.ttf') format('truetype');
  // }
  .p#{$page} {
    font-family: p#{$page};
  }
  .text-p#{$page} {
    font-family: text#{$page};
  }
}

@for $i from 1 through 604 {
  @include word_font($i);
}
``
found on `src/styles/fonts/_font.scss`

I don't know how to correctly fix this so i overcome this by change the CDN request to the fonts provided in the repo
from
```
@font-face {
    font-family: p#{$page};
    src: url('//quran-1f14.kxcdn.com/fonts/ttf/p#{$page}.ttf') format('truetype');
  }
```
to

```
  @font-face {
    font-family: p#{$page};
    src: url('../../static/fonts/ttf/p#{$page}.ttf') format('truetype');
  }
```

Hope it helps

**Comment by junwatu** [comment]
@imadmk thanks for the trick, webpack build succesfully but i still have problem with browser request though, it's shows empty response.

**Comment by sabeurthabti** [comment]
@junwatu can you share screenshot? what url you're hitting?

**Comment by mmahalwy** [comment]
What is the url? `localhost:8080` or `localhost:8000`?

**Comment by junwatu** [comment]
@mmahalwy  the url is `localhost:8080` and i try to hit `localhost:8000` but there is no connection at that url.

**Comment by imadmk** [comment]
Try to run
```
env NODE_PATH='./src' PORT=8000 UV_THREADPOOL_SIZE=100 node --expose-gc ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --config ./webpack/dev.config.js --progress
```
and
```
env NODE_PATH='./src' PORT=8000 node --expose-gc ./bin/server.js
```
in 2 different consoles, webpack first then node and use `git-bash`.

hope it works

**Comment by mmahalwy** [comment]
@junwatu is this still a problem? Perhaps we should escalate this to a higher priority

**Comment by junwatu** [comment]
@mmahalwy i already update to the latest code but the problem is still persist. 
@imadmk  thanks but it doesn't work on my machine.

**Comment by mmahalwy** [comment]
@junwatu sorry, this has been a while. What does it hang out?
