### ISSUE TITLE
Divehi Translation not showing

### ISSUE THREAD

**Issue by kjellouli** [quran/quran.com-frontend#858]
Salam Alikum wr wb,

I am Kamal, the developer of http://Quranindex.info and I noticed the Divehi translation doesn't show properly in the browser (see screenshot below).

![image](https://user-images.githubusercontent.com/6676571/29642950-bd7fd95c-8839-11e7-9e9c-a1d72bb46536.png)

The issue can be resolved by downloading/applying the proper fonts for the Divehi translation from the following links:
- http://quranindex.info/fonts/divehi/divehi.woff
- http://quranindex.info/fonts/divehi/divehi.woff2
- http://quranindex.info/fonts/divehi/divehi.eot
- http://quranindex.info/fonts/divehi/divehi.ttf
- http://quranindex.info/fonts/divehi/divehi.svg

It should fix your issue as I did (see screenshot below).

<img src="https://user-images.githubusercontent.com/6676571/29643071-84c7e360-883a-11e7-9ee7-f42ebbf2335c.png" width="300">

Jazakum Allah khair everyone for your huge efforts and keep up the great work!

Kamal J.

**Comment by imadmk** [comment]
Waalaikumsalam @kjellouli 
What browser and version you used?

**Comment by kjellouli** [comment]
Alikum salam wr wb brother @imadmk,

I am using the same Chrome version as you (with no extensions). I think you might have the Divehi font installed on your OS and that is why maybe it is showing for you and not for me. What is weird is that the font is properly working on Safari on Mac and iPhone.

Please let me know if you need further information.
Kamal J.

**Comment by naveed-ahmad** [comment]
@kjellouli thanks for providing the fonts.

**Comment by kjellouli** [comment]
@naveed-ahmad Glad to help!
