### ISSUE TITLE
Have different subdomains, where each one would open up the website in that language or the translation would be of that language.

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#86]
It could also flip the website and make the text go from right to left to make it seem more natural for languages that are written that way, for example Urdu. Or cookies could be kept to tell the preferred language of the user.

**Comment by reshadn** [comment]
Maybe use the w3 country codes: http://www.w3.org/International/O-charset-lang.html

**Comment by mmahalwy** [comment]
I think this is long long term to be honest with you. We don't do any i18n at all
