### ISSUE TITLE
Scrolling doesn't not work correctly + Icon highlight not clear

### ISSUE THREAD

**Issue by talothman** [quran/quran.com-frontend#887]
Once playing, the scrolling feature does not jump to the correct Ayah but scrolls a couple of Ayahs down. Additionally, the icon to set scrolling on and off does not seems to indicate which mode it's in.

**Comment by mmahalwy** [comment]
Salam,

Mind sharing screenshots or anything to help us debug/reproduce this?

Thanks!

**Comment by bahaa96** [comment]
@talothman Would you attach some screenshots to help us solve this issue ?
