### ISSUE TITLE
Preferrably rename these Surahs:

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#89]
rename Surahs referring to prophets (explicitly) to The Prophet _______

rename Surah 5 to Al-Maidah

rename Surah 14 to Abraham, "im" to "am"; more common

rename Surah 20 to The Letters "Ta" and "Ha"

rename Surah 22 to Al-Hajj, extra j more common

rename Surah 25 to The Criterion, "a" changes to an "o"

rename Surah 36 to The Letters "Ya" and "Sin"

rename Surah 52 to The Mountain, as mounts can refer to horses

rename Surah 58 to Al-Mujadilah, add h to mean converted t in Arabic

rename Surah 60 to The Woman to Be Examined

rename Surah 66 to The Prohibition, had extra i

rename Surah 86 to The Nightcomer, extra m

rename Surah 88 to The Overwhelming Event

rename Surah 101 to The Striking Calamity

rename Surah 102 to The Rivalry in Worldly Increase

rename Surah 104 to The Slanderer

rename Surah 106 to The Tribe of Quraysh

maybe rename Surah 21 to Al-Ambya, if you wish to write as pronounced

maybe rename Surah 28 to The Narrations, stories can mean fairy tales

maybe rename Surah 85 to The Big Stars

**Comment by ahmedre** [comment]
I disagree with some of these - let's stick to current quran.com naming for
now (that'll fix some of the suggestions from this ticket, ex Abraham
should be Ibrahim).

**Comment by ahmedre** [comment]
To be clear, I am talking about the Arabic name. For English, let's find a
translation and use their naming.

**Comment by mmahalwy** [comment]
yeah i am with you i dont want to change them
