### ISSUE TITLE
Ayah title not changed when user click next surah.

### ISSUE THREAD

**Issue by bhirmbani** [quran/quran.com-frontend#890]
The ayah section with dropdown at the upper left corner (next to the home button) didn't changed when user click next surah, after the current surah is finished.

**Comment by popo63301** [comment]
Personally, I can't see the problem. Could you provide us more details, or a screenshot?

**Comment by bhirmbani** [comment]
Hello, i hope this helps:

1.
<img width="1429" alt="screen shot 2017-11-20 at 08 21 41" src="https://user-images.githubusercontent.com/12825389/32998300-8ddf3462-cdcc-11e7-975e-15c0a54c6fca.png">

2.
<img width="1436" alt="screen shot 2017-11-20 at 08 22 31" src="https://user-images.githubusercontent.com/12825389/32998301-90784204-cdcc-11e7-886f-4e9e71218fe2.png">

**Comment by sabeurthabti** [comment]
@bhirmbani Thank you for raising this, I've applied some labels for this and iA we will try to fix it.

**Comment by popo63301** [comment]
I'd like to solve it inshAllah.

**Comment by mmahalwy** [comment]
@popo63301 please take it away!

**Comment by popo63301** [comment]
Already fixed on staging thanks to @naveed-ahmad . Now, we can close this issue.

**Comment by naveed-ahmad** [comment]
JazakAllah for testing bro, yeah this was fix few week back. We need to have build very soon.
