### ISSUE TITLE
 5:105, where it is typed ' To Allah is you return', I believe it should be 'your'.

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#91]

**Comment by abdelouali** [comment]
Allah knows best

**Comment by ahmedre** [comment]
sahih international, this is indeed corrected in the third revision, so we should fix this.

**Comment by ATouhou** [comment]
Is it not best to make a REPO just for translations, and then for all languages keep those "bugs" there. So can contact publishers and confirm with them / or fix critical/typos , while the change is logged in Github?

**Comment by ATouhou** [comment]
If Tanzil could move their translations to GITHUB and accept pull-requests that would be optimal
