### ISSUE TITLE
switch to transliteration from translation on surah 69

### ISSUE THREAD

**Issue by mtweak** [quran/quran.com-frontend#912]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other

**Current behavior:**

Go to quran.com, al-haqqah.  You'll see that even though you've set translation, for some ayahs it switches to transliteration at ayah 11.

**Expected / new behavior:**

Expected behavior is to honor the setting (translation)
**For issue, please provide steps to reproduce it:**
Go to quran.com
Ensure settings are set for translation for tooltip
Navigate to al-haqqah (69)
Hover over some of the ayahs, you'll see that some are showing transliteration

**Anything else:**
Reproduced on Firefox, Chrome.

**Comment by mtweak** [comment]
<img width="948" alt="screen shot 2017-12-17 at 7 25 17 pm" src="https://user-images.githubusercontent.com/13370087/34086240-0ab13582-e360-11e7-8f86-e72fef70ef7a.png">

**Comment by fawazahmed0** [comment]
Same problem here,with every surah

**Comment by mmahalwy** [comment]
We are fixing it inshallah. Apologies.

**Comment by mmahalwy** [comment]
@naveed-ahmad can we close this once deployed?

**Comment by osaid-ahmad** [comment]
irrespective of the selection, tooltip is displaying translation

**Comment by fawazahmed0** [comment]
@osaid-ahmad The problem has already been solved

**Comment by osaid-ahmad** [comment]
@fawazahmed0 now its showing translation even if we chose transliteration

![qrn](https://user-images.githubusercontent.com/32534673/34513757-d6636bd2-f08f-11e7-8178-114a548628b7.png)

**Comment by fawazahmed0** [comment]
@mmahalwy @naveed-ahmad Its showing translation even if we chose transliteration

**Comment by fawazahmed0** [comment]
@osaid-ahmad Please open a new issue

**Comment by naveed-ahmad** [comment]
Salam, yeah we're updating transliteration. New transliteration will be available in few days inshAllah.

**Comment by fawazahmed0** [comment]
@naveed-ahmad But now transliteration tooltip option is not working, I hope it gets solved soon Inshallah
