### ISSUE TITLE
'npm run dev' runs fine but app is not loading

### ISSUE THREAD

**Issue by osaid-ahmad** [quran/quran.com-frontend#915]
**I'm submitting a ...**

- [x] other

**Current behavior:**
on running 'npm run dev', i dont see any error on CLI but app is not loading on localhost:8000

[CLI text.txt](https://github.com/quran/quran.com-frontend/files/1579379/CLI.text.txt)

![cli](https://user-images.githubusercontent.com/32534673/34258418-e0cd9e78-e683-11e7-97db-184e95594f8b.PNG)

![localhost8000](https://user-images.githubusercontent.com/32534673/34258420-e1099a86-e683-11e7-8e72-db34e6548b69.PNG)

I dont know if this is the right place to ask this but any help in this setup would be a great help.

**Expected / new behavior:**

**For issue, please provide steps to reproduce it:**
- Steps 
- to
- reproduce 

**Anything else:**
OS: windows 7 x64bit
node -v: 8.9.3
npm -v: 5.5.1

**Comment by mmahalwy** [comment]
@osaid-ahmad salam, any errors in the logs?

**Comment by osaid-ahmad** [comment]
@mmahalwy w/salam brother, till yesterday there was no error in command line or browser console.
files were emitted but i could not see anything on localhost.
i got some warnings on running 'npm install', not sure if that helps.
[npm install warnings.txt](https://github.com/quran/quran.com-frontend/files/1581756/npm.install.warnings.txt)


However, today I am getting some error (attached below) which is probably originated by ..\src\redux\create.js where it is referencing to ./modules/reducer
[npm run dev.txt](https://github.com/quran/quran.com-frontend/files/1581742/npm.run.dev.txt)

I can explain more about my prob on skype: 'osaid.ahmad91' if it is convienent for you.

**Comment by osaid-ahmad** [comment]
For now i commented line 29-33 in \src\redux\create.js in my local. 
Now, though i dont see any error on CLI or browser console, the app is not loading on localhost:8000

**Comment by mmahalwy** [comment]
@osaid-ahmad mind having the output here? I fear downloading files on my work computer.

**Comment by osaid-ahmad** [comment]
npm install warnings: 


D:\ReactProj\QuranFrontend\quran.com-frontend>npm install
npm WARN babel-preset-react-app@3.1.0 requires a peer of babel-runtime@^6.23.0 but none is installed. You must install p
eer dependencies yourself.
npm WARN eslint-loader@1.3.0 requires a peer of eslint@>=1.6.0 <3.0.0 but none is installed. You must install peer depen
dencies yourself.
npm WARN react-json-tree@0.5.5 requires a peer of react@^0.14.0 but none is installed. You must install peer dependencie
s yourself.
npm WARN react-router-scroll@0.2.1 requires a peer of react-router@^2.3.0 but none is installed. You must install peer d
ependencies yourself.
npm WARN react-test-renderer@16.2.0 requires a peer of react@^16.0.0 but none is installed. You must install peer depend
encies yourself.
npm WARN react-treebeard@2.1.0 requires a peer of react@^15.5.4 || ^16.0.0 but none is installed. You must install peer
dependencies yourself.
npm WARN react-treebeard@2.1.0 requires a peer of react-dom@^15.5.4 || ^16.0.0 but none is installed. You must install p
eer dependencies yourself.
npm WARN redux-connect@5.0.0 requires a peer of react-router@~2.x.x || ~3.x.x but none is installed. You must install pe
er dependencies yourself.
npm WARN redux-devtools-dock-monitor@1.1.0 requires a peer of react@^0.14.0 but none is installed. You must install peer
 dependencies yourself.
npm WARN redux-devtools-log-monitor@1.0.5 requires a peer of react@^0.14.0 but none is installed. You must install peer
dependencies yourself.
npm WARN scroll-behavior@0.7.0 requires a peer of history@^1.12.1 || ^2.0.0 but none is installed. You must install peer
 dependencies yourself.
npm WARN stylelint-webpack-plugin@0.2.0 requires a peer of stylelint@^6.0.1 but none is installed. You must install peer
 dependencies yourself.
npm WARN quran@1.0.0 No license field.
npm WARN The package webpack-dev-server is included as both a dev and production dependency.

updated 184 packages in 76.259s

D:\ReactProj\QuranFrontend\quran.com-frontend>

**Comment by osaid-ahmad** [comment]
npm run dev errors with lines uncommented in create.js: 

D:\ReactProj\QuranFrontend\quran.com-frontend>npm run dev

> quran@1.0.0 dev D:\ReactProj\QuranFrontend\quran.com-frontend
> cross-env NODE_PATH='./src' PORT=8000 UV_THREADPOOL_SIZE=100 node --expose-gc ./node_modules/webpack-dev-server/bin/we
bpack-dev-server.js --config ./webpack/dev.config.js --progress  & env NODE_PATH='./src' PORT=8000 node --expose-gc ./bi
n/server.js

 94% asset optimization./src/redux/create.js
Module not found: Error: Can't resolve './modules/reducer' in 'D:\ReactProj\QuranFrontend\quran.com-frontend\src\redux'
resolve './modules/reducer' in 'D:\ReactProj\QuranFrontend\quran.com-frontend\src\redux'
  using description file: D:\ReactProj\QuranFrontend\quran.com-frontend\package.json (relative path: ./src/redux)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\ReactProj\QuranFrontend\quran.com-frontend\package.json (relative path: ./src/redux)
    using description file: D:\ReactProj\QuranFrontend\quran.com-frontend\package.json (relative path: ./src/redux/modul
es/reducer)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\ReactProj\QuranFrontend\quran.com-frontend\src\redux\modules\reducer doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\ReactProj\QuranFrontend\quran.com-frontend\src\redux\modules\reducer.js doesn't exist
      as directory
        D:\ReactProj\QuranFrontend\quran.com-frontend\src\redux\modules\reducer doesn't exist
[D:\ReactProj\QuranFrontend\quran.com-frontend\src\redux\modules\reducer]
[D:\ReactProj\QuranFrontend\quran.com-frontend\src\redux\modules\reducer.js]
[D:\ReactProj\QuranFrontend\quran.com-frontend\src\redux\modules\reducer]
 @ ./src/redux/create.js 26:4-28:6 27:27-55
 @ ./src/client.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server babel-polyfill react-hot-loader/patch
webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server bootstrap-loader/lib/bootstrap.loader?config
FilePath=D:/ReactProj/QuranFrontend/quran.com-frontend/src/styles/bootstrap.config.json!bootstrap-loader/no-op.js ./src/
client.js
Terminate batch job (Y/N)? ^C

**Comment by osaid-ahmad** [comment]
npm run dev with lines commented, produces no error but app not loading

D:\ReactProj\QuranFrontend\quran.com-frontend>npm run dev

> quran@1.0.0 dev D:\ReactProj\QuranFrontend\quran.com-frontend
> cross-env NODE_PATH='./src' PORT=8000 UV_THREADPOOL_SIZE=100 node --expose-gc ./node_modules/webpack-dev-server/bin/we
bpack-dev-server.js --config ./webpack/dev.config.js --progress  & env NODE_PATH='./src' PORT=8000 node --expose-gc ./bi
n/server.js

 95% emittingHash: 8643de069a2209110df9
Version: webpack 2.7.0
Time: 14672ms
                        Asset     Size  Chunks                    Chunk Names
          pdf-footer-chunk.js   2.4 kB      15  [emitted]         pdf-footer
        images/background.jpg  17.6 kB          [emitted]
          images/index-bg.jpg  17.6 kB          [emitted]
         images/logo-lg-w.png  20.1 kB          [emitted]
           images/logo-lg.png  17.1 kB          [emitted]
           images/madinah.jpg   167 kB          [emitted]
            images/makkah.jpg   270 kB          [emitted]  [big]
    images/mockup-desktop.png   167 kB          [emitted]
 images/mockup-desktop@2x.png   564 kB          [emitted]  [big]
 images/mockup-desktop@3x.png  1.09 MB          [emitted]  [big]
    images/mockup_desktop.png   222 kB          [emitted]
 images/mockup_desktop@2x.png   743 kB          [emitted]  [big]
     images/mockup_mobile.png  67.6 kB          [emitted]
  images/mockup_mobile@2x.png   233 kB          [emitted]
     images/ornament-left.png  15.8 kB          [emitted]
    images/ornament-right.png    16 kB          [emitted]
        images/quran-logo.png  22.2 kB          [emitted]
      images/quranloading.gif  16.9 kB          [emitted]
         images/thumbnail.png   487 kB          [emitted]  [big]
     globalnav-surah-chunk.js   361 kB    0, 6  [emitted]  [big]  globalnav-surah
                   1-chunk.js   248 kB       1  [emitted]
              mobile-chunk.js  22.7 kB       2  [emitted]         mobile
             contact-chunk.js  16.2 kB       3  [emitted]         contact
           donations-chunk.js  5.97 kB       4  [emitted]         donations
         smartbanner-chunk.js   172 kB       5  [emitted]         smartbanner
           globalnav-chunk.js   175 kB       6  [emitted]         globalnav
                 pdf-chunk.js   197 kB       7  [emitted]         pdf
         ayatulkursi-chunk.js   205 kB       8  [emitted]         ayatulkursi
              search-chunk.js   203 kB       9  [emitted]         search
       globalsidebar-chunk.js    76 kB      10  [emitted]         globalsidebar
         VerseTafsir-chunk.js    18 kB      11  [emitted]         VerseTafsir
         chapterinfo-chunk.js  17.5 kB      12  [emitted]         chapterinfo
               error-chunk.js  6.59 kB      13  [emitted]         error
               about-chunk.js  11.6 kB      14  [emitted]         about
images/app-banner-android.png  92.8 kB          [emitted]
          topoptions-chunk.js   104 kB      16  [emitted]         topoptions
         audioplayer-chunk.js   119 kB      17  [emitted]         audioplayer
           surahinfo-chunk.js   101 kB      18  [emitted]         surahinfo
            pageview-chunk.js    15 kB      19  [emitted]         pageview
                  20-chunk.js   100 kB      20  [emitted]
      repeatdropdown-chunk.js  81.4 kB      21  [emitted]         repeatdropdown
                  22-chunk.js  11.1 kB      22  [emitted]
                  23-chunk.js  2.82 kB      23  [emitted]
                      main.js  3.52 MB      24  [emitted]  [big]  main
 globalnav-surah-chunk.js.map   324 kB    0, 6  [emitted]         globalnav-surah
               1-chunk.js.map   238 kB       1  [emitted]
          mobile-chunk.js.map  21.5 kB       2  [emitted]         mobile
         contact-chunk.js.map  9.18 kB       3  [emitted]         contact
       donations-chunk.js.map  3.86 kB       4  [emitted]         donations
     smartbanner-chunk.js.map   182 kB       5  [emitted]         smartbanner
       globalnav-chunk.js.map   186 kB       6  [emitted]         globalnav
             pdf-chunk.js.map   200 kB       7  [emitted]         pdf
     ayatulkursi-chunk.js.map   199 kB       8  [emitted]         ayatulkursi
          search-chunk.js.map   208 kB       9  [emitted]         search
   globalsidebar-chunk.js.map  72.9 kB      10  [emitted]         globalsidebar
     VerseTafsir-chunk.js.map  15.3 kB      11  [emitted]         VerseTafsir
     chapterinfo-chunk.js.map  14.8 kB      12  [emitted]         chapterinfo
           error-chunk.js.map  3.37 kB      13  [emitted]         error
           about-chunk.js.map  7.28 kB      14  [emitted]         about
      pdf-footer-chunk.js.map  1.08 kB      15  [emitted]         pdf-footer
      topoptions-chunk.js.map   117 kB      16  [emitted]         topoptions
     audioplayer-chunk.js.map   110 kB      17  [emitted]         audioplayer
       surahinfo-chunk.js.map   114 kB      18  [emitted]         surahinfo
        pageview-chunk.js.map  9.34 kB      19  [emitted]         pageview
              20-chunk.js.map   116 kB      20  [emitted]
  repeatdropdown-chunk.js.map  82.1 kB      21  [emitted]         repeatdropdown
              22-chunk.js.map  7.15 kB      22  [emitted]
              23-chunk.js.map  1.72 kB      23  [emitted]
                  main.js.map  3.92 MB      24  [emitted]         main

**Comment by najiboun** [comment]
Salam, I have the exact same issue

**Comment by sabeurthabti** [comment]
@mmahalwy do we know anyone currently running the app via windows? 

@osaid-ahmad can you try making a new file with the content of  './modules/reducer'` and try importing it /? my thinking is the windows file system might be confused or something.  Another solution is to try to install bash on windows,  https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10 and running the app that way.

**Comment by osaid-ahmad** [comment]
@sabeurthabti installing bash didn't help but yes looks like prob is related to cross-env
Probably multiple commands are not getting executed in windows this way:
`"dev": "cross-env NODE_PATH='./src' PORT=8000 UV_THREADPOOL_SIZE=100 node --expose-gc ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --config ./webpack/dev.config.js --progress  & env NODE_PATH='./src' PORT=8000 node --expose-gc ./bin/server.js",`

I tried tweeking this but no success, I will spend some more time exploring https://stackoverflow.com/questions/30950032/how-can-i-run-multiple-npm-scripts-in-parallel and see if it works.

**Comment by osaid-ahmad** [comment]
`"dev": " start cross-env NODE_PATH='./src' PORT=8000 UV_THREADPOOL_SIZE=100 node --expose-gc ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --config ./webpack/dev.config.js --progress  && start cross-env NODE_PATH='./src' PORT=8000 node --expose-gc ./bin/server.js",`

doing this did run the commands in 2 windows but resulting in following error:

raven@1.1.1 alert: no DSN provided, error reporting disabled
raven@1.1.1 alert: Enabled automatic breadcrumbs for console
raven@1.1.1 alert: Enabled automatic breadcrumbs for http
[piping] can't execute file: D:\ReactProj\QuranFrontend\quran.com-frontend\bin\server.js
[piping] error given was: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:501:7)
    at exports.default (express.js:80:12)
    at Object.<anonymous> (server.js:45:1)
    at Module._compile (module.js:635:30)
    at loader (D:\ReactProj\QuranFrontend\quran.com-frontend\node_modules\babel-register\lib\node.js:148:5)
    at require.extensions.(anonymous function) (D:\ReactProj\QuranFrontend\quran.com-frontend\node_modules\babel-registe
r\lib\node.js:158:7)
    at Object._module2.default._extensions.(anonymous function) [as .js] (D:\ReactProj\QuranFrontend\quran.com-frontend\
node_modules\require-hacker\babel-transpiled-modules\require hacker.js:260:68)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Module._load (module.js:489:3)
    at Function.module._load (D:\ReactProj\QuranFrontend\quran.com-frontend\node_modules\piping\lib\launcher.js:32:16)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at D:\ReactProj\QuranFrontend\quran.com-frontend\bin\server.js:37:5
    at check (D:\ReactProj\QuranFrontend\quran.com-frontend\node_modules\webpack-isomorphic-tools\babel-transpiled-modul
es\index.js:922:14)
    at wait_for (D:\ReactProj\QuranFrontend\quran.com-frontend\node_modules\webpack-isomorphic-tools\babel-transpiled-mo
dules\index.js:937:5)
    at Immediate._onImmediate (D:\ReactProj\QuranFrontend\quran.com-frontend\node_modules\webpack-isomorphic-tools\babel
-transpiled-modules\index.js:969:12)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[piping] further repeats of this error will be suppressed...
raven@1.1.1 alert: getContext called without context; this may indicate incorrect setup - refer to docs on contexts
raven@1.1.1 alert: uncaughtException: 570e019955cb440083bcf35225828033
Terminate batch job (Y/N)?
^C
D:\ReactProj\QuranFrontend\quran.com-frontend>

**Comment by mmahalwy** [comment]
@sabeurthabti I don't know any. Perhaps @naveed-ahmad ? 

@osaid-ahmad try pulling master again, I just merged a PR. I think there was an error in master

**Comment by osaid-ahmad** [comment]
@mmahalwy 
I have merged the upstream in local but both the issues persists

@sabeurthabti i managed to run both the "dev" commands in windows both parallel and consecutive but `"cross-env NODE_PATH='./src' PORT=8000 node --expose-gc ./bin/server.js"` is resulting in the following 

`[piping] can't execute file: D:\ReactProj\QuranFrontend\quran.com-frontend\bin\server.js
[piping] error given was: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:501:7)
    at exports.default (express.js:80:12)
    at Object.<anonymous> (server.js:45:1)
    at Module._compile (module.js:635:30)
    at loader (D:\ReactProj\QuranFrontend\quran.com-frontend\node_modules\babel-register\lib\node.js:148:5)
    at require.extensions.(anonymous function) (D:\ReactProj\QuranFrontend\quran.com-frontend\node_modules\babel-registe
r\lib\node.js:158:7)`

full CLI log:
[err.txt](https://github.com/quran/quran.com-frontend/files/1587271/err.txt)

**Comment by sabeurthabti** [comment]
any luck googling `https://www.google.nl/search?q=error+given+was%3A+TypeError%3A+Path+must+be+a+string.+Received+undefined+at+assertPath+babel&oq=error+given+was%3A+TypeError%3A+Path+must+be+a+string.+Received+undefined+at+assertPath+babel&aqs=chrome..69i57.2417j0j7&sourceid=chrome&ie=UTF-8` ?

Wish I could help, travelling for the holidays :(

**Comment by mmahalwy** [comment]
@osaid-ahmad I think this is the fix: https://github.com/quran/quran.com-frontend/pull/918

**Comment by najiboun** [comment]
I tested the last fix on bash linux on (Windows 10 64 bit build 16299.125), there is no reducer error anymore.
npm run dev outpout  
`root@DESKTOP-4IM9BP8:/mnt/d/quran.com-frontend-master# npm run dev

> quran@1.0.0 dev /mnt/d/quran.com-frontend-master
> cross-env NODE_PATH='./src' PORT=8000 UV_THREADPOOL_SIZE=100 node --expose-gc ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --config ./webpack/dev.config.js --progress  & env NODE_PATH='./src' PORT=8000 node --expose-gc ./bin/server.js

 64% building modules 714/793 modules 79 active .../quran-components/lib/Loader/index.jsraven@1.1.1 alert: no DSN provided, error reporting disabled
raven@1.1.1 alert: Enabled automatic breadcrumbs for console
raven@1.1.1 alert: Enabled autom 64% building modules 718/793 modules 75 active .../quran-components/lib/Loader/index.jsraven@1.1.1 alert: getContext called without context; this may indicate incorrect setup - refer to docs on contexts
==> 🌎  ENV=development
==> ✅  Server is listening at http://localhost:8000
==> 🎯  API at http://staging.quran.com:3000
==> host localhost
==> port 8000
==> api http://staging.quran.com:3000
==> oneQuran http://localhost:3030
==> sentryClient
==> sentryServer
==> facebookAppId 1599019233731707
==> fontsURL //quran-1f14.kxcdn.com
==> defaultLocale en
==> isProduction false           95% emittingHash: e62cd78983599bba3f82
Version: webpack 2.7.0
Time: 16769ms
                        Asset     Size  Chunks                    Chunk Names
          pdf-footer-chunk.js  2.36 kB      15  [emitted]         pdf-footer
        images/background.jpg  17.6 kB          [emitted]
          images/index-bg.jpg  17.6 kB          [emitted]
         images/logo-lg-w.png  20.1 kB          [emitted]
           images/logo-lg.png  17.1 kB          [emitted]
           images/madinah.jpg   167 kB          [emitted]
            images/makkah.jpg   270 kB          [emitted]  [big]
    images/mockup-desktop.png   167 kB          [emitted]
 images/mockup-desktop@2x.png   564 kB          [emitted]  [big]
 images/mockup-desktop@3x.png  1.09 MB          [emitted]  [big]
    images/mockup_desktop.png   222 kB          [emitted]
 images/mockup_desktop@2x.png   743 kB          [emitted]  [big]
     images/mockup_mobile.png  67.6 kB          [emitted]
  images/mockup_mobile@2x.png   233 kB          [emitted]
     images/ornament-left.png  15.8 kB          [emitted]
    images/ornament-right.png    16 kB          [emitted]
        images/quran-logo.png  22.2 kB          [emitted]
      images/quranloading.gif  16.9 kB          [emitted]
         images/thumbnail.png   487 kB          [emitted]  [big]
     globalnav-surah-chunk.js   355 kB    0, 6  [emitted]  [big]  globalnav-surah
                   1-chunk.js   240 kB       1  [emitted]
              mobile-chunk.js  22.6 kB       2  [emitted]         mobile
             contact-chunk.js    15 kB       3  [emitted]         contact
           donations-chunk.js  5.94 kB       4  [emitted]         donations
         smartbanner-chunk.js   171 kB       5  [emitted]         smartbanner
           globalnav-chunk.js   175 kB       6  [emitted]         globalnav
                 pdf-chunk.js   194 kB       7  [emitted]         pdf
         ayatulkursi-chunk.js   198 kB       8  [emitted]         ayatulkursi
              search-chunk.js   200 kB       9  [emitted]         search
       globalsidebar-chunk.js  75.5 kB      10  [emitted]         globalsidebar
         VerseTafsir-chunk.js  17.9 kB      11  [emitted]         VerseTafsir
         chapterinfo-chunk.js  17.4 kB      12  [emitted]         chapterinfo
               error-chunk.js  6.51 kB      13  [emitted]         error
               about-chunk.js  11.6 kB      14  [emitted]         about
images/app-banner-android.png  92.8 kB          [emitted]
          topoptions-chunk.js   103 kB      16  [emitted]         topoptions
         audioplayer-chunk.js   114 kB      17  [emitted]         audioplayer
           surahinfo-chunk.js   101 kB      18  [emitted]         surahinfo
            pageview-chunk.js    15 kB      19  [emitted]         pageview
                  20-chunk.js   100 kB      20  [emitted]
      repeatdropdown-chunk.js  80.3 kB      21  [emitted]         repeatdropdown
                  22-chunk.js  10.6 kB      22  [emitted]
                  23-chunk.js  2.78 kB      23  [emitted]
                      main.js   3.5 MB      24  [emitted]  [big]  main
 globalnav-surah-chunk.js.map   322 kB    0, 6  [emitted]         globalnav-surah
               1-chunk.js.map   232 kB       1  [emitted]
          mobile-chunk.js.map  21.2 kB       2  [emitted]         mobile
         contact-chunk.js.map  8.83 kB       3  [emitted]         contact
       donations-chunk.js.map  3.71 kB       4  [emitted]         donations
     smartbanner-chunk.js.map   182 kB       5  [emitted]         smartbanner
       globalnav-chunk.js.map   185 kB       6  [emitted]         globalnav
             pdf-chunk.js.map   198 kB       7  [emitted]         pdf
     ayatulkursi-chunk.js.map   194 kB       8  [emitted]         ayatulkursi
          search-chunk.js.map   206 kB       9  [emitted]         search
   globalsidebar-chunk.js.map  72.4 kB      10  [emitted]         globalsidebar
     VerseTafsir-chunk.js.map  15.1 kB      11  [emitted]         VerseTafsir
     chapterinfo-chunk.js.map  14.6 kB      12  [emitted]         chapterinfo
           error-chunk.js.map  3.23 kB      13  [emitted]         error
           about-chunk.js.map  7.04 kB      14  [emitted]         about
      pdf-footer-chunk.js.map  1.04 kB      15  [emitted]         pdf-footer
      topoptions-chunk.js.map   117 kB      16  [emitted]         topoptions
     audioplayer-chunk.js.map   108 kB      17  [emitted]         audioplayer
       surahinfo-chunk.js.map   114 kB      18  [emitted]         surahinfo
        pageview-chunk.js.map  8.98 kB      19  [emitted]         pageview
              20-chunk.js.map   116 kB      20  [emitted]
  repeatdropdown-chunk.js.map  81.4 kB      21  [emitted]         repeatdropdown
              22-chunk.js.map  7.04 kB      22  [emitted]
              23-chunk.js.map  1.65 kB      23  [emitted]
                  main.js.map  3.89 MB      24  [emitted]         main`

When I try accessing http://localhost:8000 I got 

`Warning: Failed prop type: Invalid prop `juzs.errored` of type `boolean` supplied to `Home`, expected `object`.
    in Home
Warning: Failed prop type: Invalid prop `chapters` of type `array` supplied to `ChaptersList`, expected an object.
    in ChaptersList
Warning: Failed prop type: Invalid prop `title` of type `object` supplied to `Tab`, expected `string`.
    in Tab
Warning: Failed prop type: Invalid prop `juzs` of type `array` supplied to `JuzList`, expected an object.
    in JuzList
Warning: Each child in an array or iterator should have a unique "key" prop. Check the top-level render call using <styled.ul>. See https://fb.me/react-warning-keys for more information.
    in ChapterItem
raven@1.1.1 alert: unhandledRejection: 4185eb9de50545ed83a06008e0eee226
{ TypeError: Cannot read property 'user' of undefined
    at Function.mapToProps (index.js:174:20)
    at mapToPropsProxy (/mnt/d/quran.com-frontend-master/node_modules/react-redux/lib/connect/wrapMapToProps.js:54:92)
    at Function.detectFactoryAndVerify (/mnt/d/quran.com-frontend-master/node_modules/react-redux/lib/connect/wrapMapToProps.js:61:19)
    at mapToPropsProxy (/mnt/d/quran.com-frontend-master/node_modules/react-redux/lib/connect/wrapMapToProps.js:54:92)
    at handleFirstCall (/mnt/d/quran.com-frontend-master/node_modules/react-redux/lib/connect/selectorFactory.js:37:18)
    at pureFinalPropsSelector (/mnt/d/quran.com-frontend-master/node_modules/react-redux/lib/connect/selectorFactory.js:85:81)
    at Connect.initSelector (/mnt/d/quran.com-frontend-master/node_modules/react-redux/lib/components/connectAdvanced.js:181:18)
    at new Connect (/mnt/d/quran.com-frontend-master/node_modules/react-redux/lib/components/connectAdvanced.js:120:15)
    at walkTree (/mnt/d/quran.com-frontend-master/node_modules/loadable-components/server/index.js:37:22)
    at walkTree (/mnt/d/quran.com-frontend-master/node_modules/loadable-components/server/index.js:76:7)
    at getQueriesFromTree (/mnt/d/quran.com-frontend-master/node_modules/loadable-components/server/index.js:102:3)
    at getLoadableState (/mnt/d/quran.com-frontend-master/node_modules/loadable-components/server/index.js:130:17)
    at /mnt/d/quran.com-frontend-master/node_modules/loadable-components/server/index.js:147:16
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7) queryErrors: [ [Circular] ] }`

![screen1](https://user-images.githubusercontent.com/10597994/34461347-013631d2-ee1f-11e7-866e-492aeb908431.PNG)
![screen2](https://user-images.githubusercontent.com/10597994/34461348-0159f5ea-ee1f-11e7-8411-79b8334a85ea.PNG)

**Comment by mmahalwy** [comment]
@najiboun great! That means we passed this issue of it not working but it's a problem with the code... I forgot to remove `state.user` from the code.

Working on a fix here: https://github.com/quran/quran.com-frontend/pull/920

**Comment by osaid-ahmad** [comment]
@mmahalwy good to see this passed.
somehow i have lost my machine. I will setup everything fresh on another one in a week. I will let u know if it works. 
[#918](https://github.com/quran/quran.com-frontend/pull/918) will solve the reducer issue.

**Comment by mmahalwy** [comment]
Perfect. Going to close this for now
