### ISSUE TITLE
Updating the CONTRIBUTING.md URL in README.md

### ISSUE THREAD

**Issue by MurshidMac** [quran/quran.com-frontend#917]
**I'm submitting a ...**

- [ ] other

**Salam Brother @mmahalwy and the team**

**Current behavior:**
While I was reading through the **README.md** file I noticed that current URL for **CONTRIBUTING.md** file
https://github.com/quran/quran.com-frontend/blob/master/CONTRIBUTING.md returns a 404 error. 

**Expected / new behavior:**
I think Contributing.md file should be in the master directory rather than  **./github**  or else adding this link https://github.com/quran/quran.com-frontend/blob/master/.github/CONTRIBUTING.md   
to **README.md** file will solve the issue.   

**Anything else:**
Could I do a pull request with these changes?
Should I remove the **heroku Slack** Link  https://quranslack.herokuapp.com/ in **README.md**  as it is not working. 
Could we create own slack channel?. any suggestions

**Comment by naveed-ahmad** [comment]
Wa Alakim o Salam brother. Feel free to open the PR to fix the links, and please leave slack URL as it is. Its known issue, working on it.

**Comment by Abdullah8006** [comment]
@naveed-ahmad The contributing.md is again un-accessible from the readme file.
