### ISSUE TITLE
Ability to choose different fonts

### ISSUE THREAD

**Issue by naveed-ahmad** [quran/quran.com-frontend#921]
**I'm submitting a ...**
- [x] feature request

**Current behavior:**
Current fonts looks great, but very difficult to select text etc.... 

**Expected / new behavior:**
Many feature from one.quran rely on selecting text. How about we add ability for users to select specific font(including current font)
Here are testing for available fonts, pdms and me_quran looks promosing. 

http://naveed-ahmad.github.io/test-arabic-fonts

**Comment by mmahalwy** [comment]
@naveed-ahmad would be great also if users can click the copy link and select for different texts/image. We had requests to copy the text as an image.

**Comment by naveed-ahmad** [comment]
> copy the text as an image

This sound more like export text as pdf or image. One day inshAllah.

**Comment by mmahalwy** [comment]
Not really, we do have the image urls, no?

**Comment by c16u** [comment]
The legacy site allowed copying images of verses.
