### ISSUE TITLE
https://quranicaudio.com/ - has horizontal scrolling .

### ISSUE THREAD

**Issue by gskls** [quran/quran.com-frontend#924]
Assalamu alaikum . 

whenever i select a hafiz and go to his section . Horizontal scrolling appears .
I found the solution. Please fix it . 

The header's negetive `margin-right` is taking it out of the normal flow . The header's style is -
`.YuRhw1tjUohnA3r6u0TTU {  
           background-size: cover;
           min-height: 350px;
    background: #009faa;
    padding-top: 8rem;
    color: #ffffff;
    padding-bottom: 5rem;
    background-color: #2CA4AB;
    margin-left: -15px;
    margin-right: -15px;
    margin-bottom: 20px;
    `

`margin-right = -15px` is causing the problem . If u wanna keep it just add `width=100%` . That will inshallah solve the problem . 

hope it helps

**Comment by ahmedre** [comment]
should this be filed at https://github.com/quran/audio.quran.com instead, and do you mind opening a pull request? cc @sabeurthabti

**Comment by gskls** [comment]
inshallah i will open a pull request
