### ISSUE TITLE
https://quran.com/ayatul-kursi not working from homepage

### ISSUE THREAD

**Issue by ghost** [quran/quran.com-frontend#927]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [ ] other

**Current behavior:**

**Expected / new behavior:**

**For issue, please provide steps to reproduce it:**
- Steps 
- to
- reproduce 

**Anything else:**

Now on mobile phone cant fix, dont want to forget.

**Comment by naveed-ahmad** [comment]
http://staging.quran.com:32932/ayatul-kursi

Working here, I really need to finish my PR :(
