### ISSUE TITLE
Surat Al-Mu'minūn Ayah 28 

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#93]
And when you have boarded the ship, you and those with you, then say, 'Praise to Allah who has saved us FORM the wrongdoing people.'

I think the "form" is suppose to be "from". Allah swt knows best

**Comment by abdelouali** [comment]
I think also it is suppose to be "from". But Allah swt knows best.

**Comment by ahmedre** [comment]
also fixed in revision 3 of sahih international, we should fix this.

**Comment by mmahalwy** [comment]
@ahmedre where can we get the revision 3?
