### ISSUE TITLE
Add verse details for social sharing.

### ISSUE THREAD

**Issue by sabeurthabti** [quran/quran.com-frontend#932]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other

**Current behavior:**

The Social Share content is generic

**Expected / new behavior:**
We should show the shared ayah text.

**Screenshot:**

![screenshot_20180121_222307](https://user-images.githubusercontent.com/2606228/35212201-5becf8c0-ff51-11e7-98bd-71e9241d59ed.png)

**Comment by tegirmon** [comment]
AA. Please review the change.  I was not able to run the app locally to test the changes.

**Comment by mmahalwy** [comment]
@tegirmon salam, how come you were unable to test locally? Didn't work?

**Comment by tegirmon** [comment]
No, the app hasnt started up successfully locally. I was running on win10. I am setting up ubuntu. Will see if I can run the app on ubuntu.

**Comment by tegirmon** [comment]
I was able to run the app on ubuntu. I see the text on twitter share (img below). Nothing on facebook share. I'll have a look tomorrow.

![image](https://user-images.githubusercontent.com/4622581/36649441-3b2d212a-1a6b-11e8-8ced-0f9e347c0125.png)

**Comment by atiqueansari1987** [comment]
Is this issue taken?

**Comment by tegirmon** [comment]
Feel free to take a look. Only the "via" for twitter is displaying the details. Fb one hasnt worked. We may need to update to later version of the share component.

**Comment by atiqueansari1987** [comment]
Insha Allah I will give it a try this weekend
