### ISSUE TITLE
The drawing of 5:76:2 lacks 'fill'

### ISSUE THREAD

**Issue by mustafa0x** [quran/quran.com-frontend#948]
As Salaamu Alaykum

See: https://quran.com/5/76

The issue is from the QPC's files.

Quran Android is good, but the following file also seems to have the issue: https://github.com/quran/quran.com-images/blob/master/res/fonts/QCF_P120.TTF

**Comment by mustafa0x** [comment]
How it looks:

![screen shot 2018-03-19 at 7 23 28 pm](https://user-images.githubusercontent.com/1473102/37611443-0ac9eaee-2bab-11e8-88f2-def6d5ae458e.png)

But I can't reproduce on my phone, so it seems to be an issue just with my installed copy.

**Comment by ahmedre** [comment]
broken on Safari on Mac for me, 100% of the time

**Comment by naveed-ahmad** [comment]
All three versions are broken :(

<img width="961" alt="2018-03-19_2231" src="https://user-images.githubusercontent.com/701567/37612048-d999c58c-2bc5-11e8-8533-90b7970940c2.png">

**Comment by mustafa0x** [comment]
This seems to be an extremely subtle bug that only presents itself on desktop (or just mac?) font rendering engines.

On android the character looks fine.

**Comment by aliasaria** [comment]
It seems there is an issue with the generated font itself. The path that appears hollow is duplicated. See gif below. Is it ok to just edit the font directly to fix? Or should we fix the generator that created it?

![fontissue](https://user-images.githubusercontent.com/213343/43877321-1b2b4802-9b67-11e8-854d-8a80614b9605.gif)

**Comment by aliasaria** [comment]
I believe this is a fixed file. Would need someone to generate everything again to test properly

@naveed-ahmad are you able to try?

[QCF_P120.ttf.zip](https://github.com/quran/quran.com-frontend/files/2272786/QCF_P120.ttf.zip)

**Comment by naveed-ahmad** [comment]
@aliasaria I believe you fetched this font from quran-images repo? This font has lots of unused glyph and weird stuff, we're no longer using these fonts.

Can you please remove duplicate path and reupload the following file again? 

https://github.com/quran/quran.com-frontend/blob/master/static/fonts/ttf/p120.ttf

**Comment by aliasaria** [comment]
Ok I believe I have fixed in it PR#1012

https://github.com/quran/quran.com-frontend/pull/1012

**Comment by mmahalwy** [comment]
@aliasaria awesome! thanks a bunch! About to merge my branch :)
