### ISSUE TITLE
After Changing Surah from Top Right Droddown, dropdown still shows old Selected Surah;

### ISSUE THREAD

**Issue by rashidrupani** [quran/quran.com-frontend#954]
After Changing Surah from Top Right Droddown, dropdown still shows old Selected Surah. This makes user confused if he selected the correct surah.
Check this video: https://www.screencast.com/t/zx4v9qjRf

Surah name should also be display as an heading before starting of the Surah name.

**Comment by mmahalwy** [comment]
Thanks for filing this! Will take a look!

**Comment by bahaa96** [comment]
@naveed-ahmad Close This Issue
