### ISSUE TITLE
502 again ("bad gateway")

### ISSUE THREAD

**Issue by phtan** [quran/quran.com-frontend#968]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other

**Current behavior:**
When I visited the web-site I saw an unexpected page. ("Bad gateway") I did not see this on staging.quran.com. Screenshot: 
![screenshot_20180414-032241](https://user-images.githubusercontent.com/3508975/38754299-ce53900e-3f93-11e8-9776-bcde6b54407d.png)

**Expected / new behavior:**
The usual

**For issue, please provide steps to reproduce it:**
- go to quran.com

**Anything else:**
- similar to issue #124

**Comment by naveed-ahmad** [comment]
Looks like a temporary server outage. Working for me.
