### ISSUE TITLE
"stops" shouldn't wrap without their corresponding word

### ISSUE THREAD

**Issue by ahmedre** [quran/quran.com-frontend#98]
in this screenshot:
<img width="998" alt="screen shot 2015-09-07 at 11 42 02 pm" src="https://cloud.githubusercontent.com/assets/47771/9728045/2254f966-55ba-11e5-80c7-cd96f7fdcce9.png">

you can see the "صلي" is on the next line instead of forcing the last word of the first line to also wrap with it. i realize this might be tricky to do but filing it anyway.

**Comment by mmahalwy** [comment]
this is contingent on the screen size, and probably will be difficult to try to fix. going to close for now
