### ISSUE TITLE
First load: Audioplayer mounted but no file available

### ISSUE THREAD

**Issue by SuperDzej** [quran/quran.com-frontend#983]
**I'm submitting a bug.**

- [ x] bug report

Bug screenshoot: [https://ibb.co/ce2dy8](url)

**Current behavior:**

On first load of surah Fatiha, Bakarah etc., I get **"Audioplayer mounted but no file available"**, I need to reload the page for play button to start playing surah.
[](url)

**Expected behavior:**

When play button after first load is clicked the recitation of ajah should start.

**Steps to reproduce:**

Select surah from dropdown menu and when it is loaded, loading screen should be stuck and developer tools should show the message.

**Anything else:**

Google Chrome, did not dive into the code yet because I have problem with installing dependencies, but will see if I find something usefull.

**Comment by naveed-ahmad** [comment]
Duplicated https://github.com/quran/quran.com-frontend/issues/786

**Comment by SuperDzej** [comment]
I wouldn't say this is a duplication of that issue, because this issue happens only on the first page load and I can not play any sound until I reload a page, the issue you are referring to happens when automatic switch from ayah to ayah happens.
