### ISSUE TITLE
Upside down tooltip on media player

### ISSUE THREAD

**Issue by nabeelvalley** [quran/quran.com-frontend#988]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other

**Current behavior:**

When hovering over the link icon on the Audio Controls the tooltip point is on the wrong side, as seen below:

<img width="352" alt="upsidedown tooltiip" src="https://user-images.githubusercontent.com/36758308/41114862-f428799e-6a85-11e8-8ae5-ad43b73020aa.png">

Also when scrolling this gets stuck to the page instead of the Audio Toolbar

<img width="516" alt="upsidedowntooltipposition" src="https://user-images.githubusercontent.com/36758308/41139558-a9babaee-6ae8-11e8-8527-7f580e280f36.png">

I've tested it on Opera, Chrome and Firefox DevEdition 

**Expected / new behavior:**

The Point on the tooltip should face down and towards the link icon, as well as stay fixed to the toolbar and not the screen

**For issue, please provide steps to reproduce it:**
- Go to Surah Page
- Hover over link icon in media controls

**Comment by naveed-ahmad** [comment]
Old bug, fixed on staging. Closing this.
