### ISSUE TITLE
Syed Abdul Ala Maududi Wrong Urdu Translation.

### ISSUE THREAD

**Issue by sikandarali94** [quran/quran.com-frontend#989]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x ] other

**Current behavior:**

My dad reads the Tafseer of Syed Abdul Ala Maududi in Urdu a lot, and he noticed that, for example, Surah Al-Imran does not contain the Urdu translation of Syed Abdul Ala Maududi, but is actually a literal
Arabic to Urdu translation. It's a real issue to show a translation of the Quran and wrongfully attribute it
to a scholar. This is because Syed Abdul Ala Maududi's translation of the Quran to Urdu is very fluent and pleasant to read, rather than the literal Arabic to Urdu translation.

**Expected / new behavior:**

Quran.com shows the actual Urdu text written by Syed Abdul Ala Maududi.

**For issue, please provide steps to reproduce it:**
- Open up Surah Al-Imran and compare the Urdu of Syed Abdul Ala Maududi on the site to the actual Urdu translation of the Quran he wrote. 

**Anything else:**

This issue will most likely be apparent in other Surahs as well.

**Comment by naveed-ahmad** [comment]
Salam, can you attach a screenshot or something with the difference?

**Comment by sikandarali94** [comment]
Walaikumussalam. Here are the screenshots:

**Quran.com**
![online urdu](https://user-images.githubusercontent.com/20622653/41632594-ff2f66ac-747d-11e8-8151-6f289b34ce1f.PNG)

**Tafheem-ul-Quran**
![actual urdu](https://user-images.githubusercontent.com/20622653/41632598-02056e3a-747e-11e8-8f88-46f0b4fe7893.PNG)

**Comment by sikandarali94** [comment]
One temporary solution to this would be that rather than stating "Abdul Ala Maududi (with Tafsir)" just call it "Urdu Translation (with Tafsir)".

**Comment by naveed-ahmad** [comment]
JazakAllah kharain for reporting @sikandarali94 

This is actually Tafsir e Usmani ( translation by Mahmood Ul Hasan and tafsir by Shabir Usmani ). Going to rename it to **Tafsir e Usmani** 

<img width="761" alt="2018-06-26_1551" src="https://user-images.githubusercontent.com/701567/41906935-c9753386-7958-11e8-8e24-f6c561de366e.png">

**Comment by naveed-ahmad** [comment]
https://archive.org/details/TafseerEUsmanicompleteUrdu
