### ISSUE TITLE
audiofile not found - API

### ISSUE THREAD

**Issue by bahaa96** [quran/quran.com-frontend#991]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other

I'm trying to fix the first 2 issues with "good first issue" label.
#673 #525 
I've added a stop button but I need to make sure that it's working. 
![](https://preview.ibb.co/eKfdwy/Capture621651.png)
this is the error I get when I try to play the Surah 

**Current behavior:**
It throws this error:
![](https://preview.ibb.co/gHhQby/Capture000.png)

**Expected / new behavior:**
The Surah get played properly.

**For issue, please provide steps to reproduce it:**
I want access to the database or mock of it as I'll mock it till you response 

**Anything else:**
I've tried to change the API_URL environment var to "https://quran.com/api" but I got that error

```
{
error: "proxy_error",
reason: "Hostname/IP doesn't match certificate's altnames: "Host: localhost. is not in the cert's altnames: DNS:audio.ayah.app, DNS:www.audio.ayah.app""
}
```
which I think that it's from your server.

**Comment by naveed-ahmad** [comment]
fixed https://github.com/quran/quran.com-frontend/pull/993
